### PR TITLE
Auto implement Group Traits

### PR DESCRIPTION
**Pull request by jettr**
### Pull Request Overview

Instead of each object providing an empty implementation for a group trait, auto implement the group trait if the object has all of the necessary sub-traits.

### Testing Strategy

`cargo check` on each CL

### Documentation Updated

- No documnetation update

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
This is great!

The only thing which this would effectively prevent is that implementers of these HILs can't opt out of certain marker traits. I don't think that's an issue, but want to mention it nonetheless.

**Review by alistair23 — APPROVED** [review]

**Review by bradjc — APPROVED** [review]
This seems like a net good thing.

**Review by hudson-ayers — APPROVED** [review]

**Comment by jettr** [comment]
> The only thing which this would effectively prevent is that implementers of these HILs can't opt out of certain marker traits. I don't think that's an issue, but want to mention it nonetheless.

I agree. We should only do this for convenience group traits, not marker traits. That is actually why I didn't implement this for the `Timestamp` trait since it seems like it might be a marker trait on `Time` instead of a group trait

**Pull request merged**
