### PR TITLE
capsule: start on console mux

### PR DESCRIPTION
**Pull request by bradjc**
There has been talk about a more specified method of sharing the UART channel between users and the board in Tock for a while, and this is a start towards that goal.

In the first iteration there is only a design comment at the top of the file. I won't squash these commits, so if the design changes we can preserve the history of how this feature came to be.

### Testing Strategy

tbd

### TODO

- [ ] Create a satisfactory initial design.
- [ ] Implement `ConsoleMux`.
- [ ] Update `ProcessConsole` and `Console` to use it.
- [ ] Implement `tockloader interact` to use the new console protocol.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make formatall`.

### CODE REVIEW

**Comment by brghena** [comment]
I think this is a great idea. I'm excited by the idea of being able to select a single application to "listen" to at a time. Creating a clean method for sending user input to a single application or capsule also sounds very useful.

One thing I think is very important about the proposed format is that it should still work fine with normal consoles, like miniterm. There will be a few junk characters appended to the start of each message, but they should overall still be readable without tockloader. One option we could consider is pushing farther in that direction and actually sending ID as three ascii digits followed by some separator.

A question I had was how other systems provide this kind of functionality and whether we could learn from their interfaces. For android phones, [`adb logcat`](https://developer.android.com/studio/command-line/logcat) handles this, for instance. Although its filter interface is not exactly straightforward and they don't care about supporting an underlying transport that's visualizable without adb. Similarly `/var/log/syslog` on linux just appends a _bunch_ of data to the start of each message and leaves it up to the user to filter. I think we're better off not going that route as it would increase UART transmit delays possibly substantially and in a way that's not obvious to the applications.

**Comment by alevy** [comment]
> One thing I think is very important about the proposed format is that it should still work fine with normal consoles, like miniterm.

I'm taking some liberties in interpreting _why_ this is important, but one option might be:

- By default, everything gets dumped out to the intermixed as it does now---i.e. all writes from capsules and processes just get serialized into a single stream with no headers...
- The console mux waits for a particular control packet that configures into a packet-oriented mode.
- Until this control packet, bytes coming from the host are just dropped

This would result in a setup where you could see a dump of everything coming out of a tock board using basic ol' tools, such as miniterm, but you could write anything to it. If you use a tool that understands the packetized format, you have all the features you want, and the protocol can still be as compact and low-resource to implement as we want it to be.

**Comment by alevy** [comment]
>  Similarly /var/log/syslog on linux just appends a bunch of data to the start of each 

We're basically proposing this, except it's a very small payload (identifier and length), but the hard part is to also handle sending bytes _to_ capsules and processes, which neither logcat, nor syslog handle.

**Comment by alevy** [comment]
@bradjc starting to look pretty good!

**Comment by bradjc** [comment]
One challenge I've run into is keeping support for `debug!()` as it currently exists. Since UART is just a byte stream, code like:

```rust
debug!("my dbg msg");
console_mux.tx("ProcessConsole Help Message");
```
can end up like:
```
my dbg msg\00\1B\02ProcessConsole Help Message
```
in the UART stream, which the receiver right now interprets as one long `debug!()` message and doesn't identify the actual console mux message appended to the stream.

One option is to make `debug!()` a console as well, but there is something nice about the simplicity of how `debug!()` currently works.

**Comment by alevy** [comment]
> One option is to make debug!() a console as well, but there is something nice about the simplicity of how debug!() currently works.

I think it really should just be a console. `debug!()` is already not very simple---it goes through the UART mux, and it's this special cased type of thing that the board needs to set up in a somewhat magical way (which works OK because we just copy and paste it everywhere, so the order doesn't get screwed up).

**Comment by bradjc** [comment]
Ok `debug!()` is a console. Since it is TX only it would actually be really easy to add a console->uart shim if you wanted to use debug on top of a raw uart.

Some open questions:
- What should the UI for this look like? What do you expect to happen when you run `tockloader listen`? Will it be too confusing if tockloader hides most output by default?
- Right now there is no way of knowing how many applications are on the board or providing that information to tockloader. How should console_mux get application info?

**Comment by ppannuto** [comment]
I think after listen, I would print a welcome and help banner, e.g.

    -----------
    Tockloader is a console multiplexer, support multiple streams, etc

    Some useful tips:
       --no-debug, suppress kernel debug messages
       --app NAME, only print messages from NAME app; may be used multiple
times for multiple apps
       --quiet, do not print this message
    -----------

Then I'd expect some kind of indicator for each app, probably padded to 16
spaces (I believe that's app name limit?):

[Kernel Debug]: Board init'd
[         c_hello]: Hello World
[               hail]: temp 33
[               hail]: lux: 1234

It'd be particularly neat I think to use `termcolor` or something like that
to give some visual indications. Maybe all the kernel debugs are gently
greyed, each app has the [ name ] bit colored, but not the output (as
that'd be annoying I think)


In the absence of a name, I'd expect just an app identifier (app 0, app 1,
kernel debug). I imagine that the debug console could be automatically used
by tockloader to query app id <> name mappings

**Comment by bradjc** [comment]
Well that works for one direction (board to user), but what about the other? What should the user's model be, should they use `tockloader listen` to interact with a very specific thing on the board (e.g. ProcessConsole or hello_loop app)? Or are they interacting with everything at once somehow? How do they decide which thing to target input to?

**Comment by ppannuto** [comment]
I wonder if it should evolve to two commands, `tockloader listen` is a simple one-way pipe that only listens, and `tockloader console` is interactive.

For the latter, I'd imagine that you start off in a top-level console where commands interact with tockloader itself, then you have an option such as `select APPNAME` which causes input to go to that app's console stream, probably `ctrl-c` to break out of it

Alternatively, at a certain point we're exceeding what's intuitive to do with a pure text-based interface -- one could imagine that `tockloader console` is a lightweight gui with text interfaces for each console stream. It's not the prettiest, but I have decent experience with tkinter, which has the advantage of being built-in to python so not introducing any cross-platform headaches

**Comment by bradjc** [comment]
I think your point that the base mechanism could have many different UIs (if someone was so inclined) is a good one.

My initial thought (and you can see this in the original PR description) is that there would be a separate tockloader command for interacting with processes. Then it seemed like keeping the existing familiar command made more sense. But it might be more confusing to try to combine them.

Sidenote: one challenge is knowing how long for tockloader to wait before sending a message to the `ConsoleMux`.

**Comment by bradjc** [comment]
Actually getting a list of application names is proving to be difficult. The `console` capsules knows what applications exist, but the `console_mux` capsule is what needs to send them to tockloader. 

Some ideas:
- Add an empty grant to `console_mux` so that it has a list of applications. This _might_ work, but is sort of clumsy.
- Give `console_mux` a capability and access to looping through each process to get the names. This would be nice because it's pretty straightforward, but would require adding a capability.
- Add some function to the `ConsoleClient` trait called something like `get_apps()` that returns an iterator of some sort that can be used to get the names. This will require (I think) touching a lot of internal kernel stuff to get all of the necessary functions.
- Follow Amit's lead and implement the `Console` syscall interface in `console_mux`. This I think would be pretty clean, but from a maintenance perspective I can't see duplicating the couple hundred lines of code in `Console`.

**Comment by samueljero** [comment]
We might be interested in leveraging the syslog protocol, or something closely related, for this, as a standard way to represent data from multiple streams that is also clear-text readable.

Spec is here: https://www.ietf.org/rfc/rfc3164.txt

**Comment by bradjc** [comment]
I found https://tools.ietf.org/html/rfc1963 which looks promising and pretty low overhead. However, I couldn't find any actual implementations of it so I'm not sure it is actually all that useful to us.

**Comment by ppannuto** [comment]
PPP is possibly quite interesting, it's built-in to Linux:
https://www.tldp.org/HOWTO/PPP-HOWTO/direct.html

If memory serves, most DSL connections were PPPoE, so while it's been a
minute, there's likely a lot of infrastructure out there to support PPP. If
it's lightweight enough, I think it's a great idea to use a standard
protocol over rolling our own.

**Comment by ppannuto** [comment]
Indeed, if we want to interface with the pppd daemon, that seems mature and
supported: https://pypi.org/project/python-pppd/

If we need to roll our own PPP stack, that betrays they protocol's age a
bit, but there is an older project on sourceforge:
https://sourceforge.net/projects/ppp4py/

**Comment by bradjc** [comment]
[This post](https://stackoverflow.com/questions/815758/simple-serial-point-to-point-communication-protocol) has some good discussion on a similar topic. [HDLC](https://en.wikipedia.org/wiki/High-Level_Data_Link_Control) seems to be a promising approach with what seems like a number of implementations.

**Comment by bradjc** [comment]
Closing this due to age and moving to a tracking issue #1336.

The branch contains a decent start, but I tend to get caught on implementing buffer conversion capsules (HDLC in this case) because I find working with buffers to be very tedious in Rust. Perhaps trying again with the leasable buffer capsule would help move things along.

**Pull request closed without merging**
