### PR TITLE
SAM4L: create GLOC peripheral driver

### PR DESCRIPTION
**Pull request by TPackard**
### Pull Request Overview

Created a new peripheral driver for SAM4L's Glue Logic Controller (GLOC). The GLOC offers two programmable lookup tables with four input pins and one output pin each.

A new variant of the imix board, imix_gloc, was also created to test the new GLOC driver's functionality. The GLOC driver cannot easily be tested on the standard imix board due to pin conflicts with the RF233 radio. The imix_gloc board is identical to the standard imix, except that all references to the radio have been removed and code for testing the GLOC driver has been added.

### Testing Strategy

The GLOC driver was tested using the new GLOC test on the imix_gloc board. This test enables and programs both lookup tables and prints out the state of both tables' output pins so that the correctness of the GLOC's operation can be manually verified. One table has one input pin disabled and the other table has output filtering enabled in order to test the full functionality of the GLOC driver. Note that the RF233 power jumper must be disconnected in order for the test to work properly.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by TPackard** [comment]
I could try adding it to the standard imix, but then you would have to manually remove all of the RF233 code every time you wanted to test the GLOC. I talked to @phil-levis about this, and he recommended creating the second imix_gloc board.

**Comment by bradjc** [comment]
I thought components would make this easy? It seems like it should just be commenting out one component and commenting in another...which is similar to how running a lot of board-level tests works (we comment in the test to run).

**Comment by TPackard** [comment]
I tried to just comment out the RF233 component, but that doesn't seem to work since there are a few other components that rely on the RF233 (namely the radio and udp driver). In order to get the GLOC test to run without the RF233 enabled, I had to remove the RF233, radio driver, udp driver, and associated constants/globals and also remove the radio and udp drivers from the imix struct.

Is there another easier way to do this? The RF233 driver cannot run at all because it messes with one of the pins that the GLOC needs to use.

**Comment by phil-levis** [comment]
We discussed whether it was better to have a different platform, or a set of comments on what you have to comment out in order to uncomment out something that's commented out (i.e., "if you want to uncomment the GLOC, you must comment out the radio driver and udp driver, remove them from the struct imix, and remove them from the system call dispatch"). Recall that components only help with initialization, not the other 2-3 places a driver might appear. We concluded, given that gloc is a narrow use case, it was better to not pollute the main imix board with this. Furthermore, if this is a feature we want to use a lot (which we might, it's part of a larger research project around software interlocks), forcing your main.rs to always differ from master is not great.

That being said, maybe one way to make the GLOC version of the kernel  more maintainable is to strip it down to just the GLOC, console, and some other key drivers.  We could also keep the GLOC version of the board on a branch, since it's not yet of general interest.

**Comment by bradjc** [comment]
It sounds like we can defer on how to integrate it in with a particular board, but we should be able to get the actual driver merged, and it is probably useful to have that in master. @TPackard can you update this PR or open a new one with all of the code that is not in the `boards/` folder?

**Comment by TPackard** [comment]
> The only difference I see is that some got converted to general GPIOs. Shouldn't they be mapped to the `GLOCINx` peripheral pins? Which pins conflict with the rf233?

The GLOC test reconfigures the pins it needs when the test is initialized. The GLOC OUT0 pin is PA08, which conflicts with RF233_IRQ.

I'll update this pull request to only include the peripheral driver.

**Pull request merged**
