### PR TITLE
Introducing Tock Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Tock Guru](https://gurubase.io/g/tock) to Gurubase. Tock Guru uses the data from this repo and data from the [docs](https://book.tockos.org) to answer questions by leveraging the LLM.

In this PR, I showcased the "Tock Guru", which highlights that Tock now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Tock Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Review by alexandruradovici — COMMENTED** [review]
The website does seem to be very slow and when asking about the code it seems to return deprecated code examples (our docs might be out if date).

I have to admit that I have mixed feelings about adding this.

**Comment by alevy** [comment]
Agree with all above, I don't think it's generally appropriate to advertise a third-party tool in the repo.

**Comment by kursataktas** [comment]
Thank you everyone for taking the time to review Tock Guru. The purpose of this PR is to inform you and to request your permission. If everything had gone well, I had hoped to see the badge on the Tock README as well. However, it seems your current stance is not positive, which is understandable based on your review results. Nevertheless, I've added some comments below.

We use an RAG-based approach, so we don’t send prompts directly to models like GPT-4. Because of this, having good data sources is really important. If the docs are outdated, there’s not much we can do. We’re constantly dealing with hallucinations and have made a lot of improvements. We’re always tweaking context search, trying out different embedding models, and testing new relevance algorithms to reduce these issues. It’s not perfect yet, but feedback like yours (especially with examples) really helps us get better. I believe we’ll get to a good place eventually.

I get the concerns about third-party access. We are planning to release a feature that will allow repository maintainers to manage their Gurus on Gurubase. This feature will let you edit data sources, view analytics on the types of questions users are asking, and gain other insights. Let me know if this would address the concerns you mentioned.

Just to clarify, this isn’t our main commercial product. As a startup, we focus on Anteon for the business side. We actually created Anteon Guru first for our users and saw it was even more useful than expected (our docs are up to date). Then we thought it’d be fun to make a central hub for all OSS projects, so we started Gurubase as a side project. 

if you’d prefer, I can disable Tock Guru on Gurubase. I’m also open to more feedback and happy to hear any thoughts if you’re interested.

**Comment by ppannuto** [comment]
Hi @kursataktas,

The Core Team had an opportunity to discuss the Tock Guru.

Regarding Tock’s presence on Gurubase, if Tock remains we would request a very prominent disclosure that the “Tock Guru” is unofficial and that its answers are non-authoritative and not representative of the Tock project. If you are unable or unwilling to include this disclosure, we would ask that you please remove Tock from Gurubase.

-Pat, on behalf of the Tock Core Team

**Comment by ppannuto** [comment]
Speaking personally now:

I don't really think our docs are that out of date. Our documentation team works pretty had to keep things current, and CI generally compile-tests code snippets in documentation. I don't know Alex's specific examples, but my guess/hope is that deprecated code in examples comes from code velocity versus training latency (or perhaps from doing something like including https://github.com/tock/tock-archive in the training set).

> We are planning to release a feature that will allow repository maintainers to manage their Gurus on Gurubase [...]

That said, our documentation team has enough work keeping our own resources up to date. It's a very big ask to police a third party site for correctness, and more so to ask free labor to correct/train the model.

Philosophizing, I do wonder if LLMs generally could be more useful as an accelerator for authoring primary documentation. i.e., some of the prompts I tried with the guru had some useful content we don't currently have, but enough substantially factually wrong information that I wouldn't ever point anyone to the tool at the moment. However, for some prompts, maybe having 2/3rd of the document written and editing the last third could be useful—hard to say whether the careful editing required would actually be faster than just taking the time to author the document in the first place though.

**Comment by kursataktas** [comment]
Hi @ppannuto,

> If you are unable or unwilling to include this disclosure, we would ask that you please remove Tock from Gurubase.

Since we currently don't have a feature to mark a guru to display this information on the UI, I have removed the Tock Guru from Gurubase.io. If we introduce this kind of flag in the future, I would be happy to re-create it and update you.

> Philosophizing, I do wonder if LLMs generally could be more useful as an accelerator for authoring primary documentation. i.e., some of the prompts I tried with the guru had some useful content we don't currently have, but enough substantially factually wrong information that I wouldn't ever point anyone to the tool at the moment. However, for some prompts, maybe having 2/3rd of the document written and editing the last third could be useful—hard to say whether the careful editing required would actually be faster than just taking the time to author the document in the first place though.

I’m not sure if this matches what you had in mind, but we have a feature concept that compares the codespace with the documentation. If it finds any missing pieces or inconsistencies, Guru would create a PR to bring them in sync. If this sounds like what you’re thinking, I can update this thread when it’s ready to test.

**Comment by ppannuto** [comment]
> I’m not sure if this matches what you had in mind, but we have a feature concept that compares the codespace with the documentation. If it finds any missing pieces or inconsistencies, Guru would create a PR to bring them in sync. If this sounds like what you’re thinking, I can update this thread when it’s ready to test.

Again speaking personally, I do think that sounds like something that would be interesting. In principle, we use various lints to require rustdoc comments on `pub`lic interfaces, and https://docs.tockos.org is auto-generated from that so it "shouldn't" be possible to have missing things; in practice, the CI enforcement there has broken many times.

**Comment by ppannuto** [comment]
> Since we currently don't have a feature to mark a guru to display this information on the UI, I have removed the Tock Guru from Gurubase.io. If we introduce this kind of flag in the future, I would be happy to re-create it and update you.

Thank you

**Pull request closed without merging**
