### PR TITLE
libraries: tickv: Convert panics to errors

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

Convert existing panics to instead return a useful error

This should fix: https://github.com/tock/tock/issues/3081

### Testing Strategy

CI

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Comment by phil-levis** [comment]
My experience going through the TBF code is doing a single check (the slice is long enough) then direct slice accesses can reduce code size. I observed that if there were 3 or more of the `get`/`ok_or` pattern, a check and direct accesses was smaller in terms of code, because those accesses would then not have panics. What is the code size effect of this change? I don't think it should block on that (this is a capsule), just wondering.

**Comment by hudson-ayers** [comment]
This PR reduces the size of the OT binary by almost 500 bytes (as a reminder, you can check the benchmark CI run for these numbers on any PR that passes all checks! https://github.com/tock/tock/runs/7643510896?check_suite_focus=true)

**Review by hudson-ayers — APPROVED** [review]
Big fan of removing panics, and this looks pretty mechanical.

**Review by twilfredo — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]
LGTM and pretty uncontroversial.

bors r+

**Review by phil-levis — APPROVED** [review]

**Pull request merged**
