### PR TITLE
Process Console New(ish) Commands

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This adds the `terminate` and `boot` commands from the app id PR to process console.

This also restores my panic command which was removed for some reason at some point.

### Testing Strategy

Using the process console on hail.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Looks good, though until AppId is in it seems like `boot` basically does nothing, since a process can never be unstarted while the process console is running?

**Comment by bradjc** [comment]
> Looks good, though until AppId is in it seems like `boot` basically does nothing, since a process can never be unstarted while the process console is running?

Aha, except for using the new `terminate` command with the process console!

**Comment by bradjc** [comment]
ping!

I really want the `panic` command back :)

**Pull request merged**
