### PR TITLE
Add Configuration Boards

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request is an attempt to implement a discussion from a [core call back in 2020](https://github.com/tock/tock/blob/master/doc/wg/core/notes/core-notes-2020-05-01.md?plain=1#L43): a method for making it easier to run kernel tests. My idea here is to create small kernel config boards in `boards/configurations` which include specific functionality for a specific purpose. The first one I have created is an nrf52840dk board with a SHA-256 AppID checker.

For each kernel feature we want to be able to test we would make a new "configuration board".

#### Motivation

Testing specific functionality if no boards use that functionality by default is difficult. It often means hacking a particular board for testing while creating a PR, then reverting those changes before opening a PR. That is ok, but if the PR discussion prompts changes, it's hard to then test those changes by somehow bringing the board-hack back.

It is also going to be hard for us to leverage our long-awaited hardware-CI platform to test many tock features on a small (at least to start) set of hardware boards. For example, we should test all schedulers, but a board can only have one.

This also means that we could have boards for tests, meaning all tests would always be compiled.

#### Alternatives

I think the main alternative is what the opentitan board uses, `custom_test_frameworks`. While these share many similarities, I don't think they solve the same problem. Specifically, it is still difficult for a single board to express a range of functionality (ie every credential checker, every scheduler, both console and ordered console, etc.) at the same time.

Also, explicitly creating configuration boards allows for using only minimal kernel "stuff", making the tests _more like_ a unit test. This in theory I think would make debugging easier if the test catches something as there should be less to examine.

#### Drawbacks

- More boards!! Yeah, this adds more crates, more boards, and more to maintain. I feel this is a worthwhile tradeoff, as components really simplify maintaining boards. I also think is actually good for us, as we should be making boards maintainable and reducing churn.

    I bet there is a way to simplify the implementations of boards too, and someone suitably savvy and motivated could reduce the overhead of these configuration boards.
- Discoverability. It might be hard to keep track of all of the board configurations and what they are meant to test. I think that using them in a hardware CI would help with this.

### Testing Strategy

Testing AppId checking.

### TODO or Help Wanted

RFC

Also, I have another "configuration board" in the works to run all of the nrf52840dk kernel tests. And the appid board is for the async process loading PR.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Comment by alistair23** [comment]
I think this is a big problem we have. We add components, but they are not connected or tested by default.

I'm not convinced this is the right approach though. This seems like it will end up with a **LOT** of boards. It also seems very prone to breakages as bits are updated/fixes in one board but not the other. We at least want to avoid as much code duplication as possible, which this currently doesn't do.

The other issue is that the boards will have a strange combination of what `configuration` board is created. Some things will only exist on the nRF, while some will only exist of OT. It seems like a weird mix-match of what is tested where

I don't think `custom_test_frameworks` is an alternative though. I think we want to use both. I think each board (including the main one) should use `custom_test_frameworks` to run tests for that configuration.

This does seem like a good use of `cfg` features. That would allow switching features of boards easily at build time. For example that would make it much easier to switch kernel schedulers, and every upstream board could support all schedulers. Adding credential checking also seems like something that could be an easily enabled feature, eventually supported in all (or at least most) boards

**Comment by bradjc** [comment]
> This does seem like a good use of `cfg` features. That would allow switching features of boards easily at build time. For example that would make it much easier to switch kernel schedulers, and every upstream board could support all schedulers. Adding credential checking also seems like something that could be an easily enabled feature, eventually supported in all (or at least most) boards

I'm not sure how cfg features would work here. They aren't designed to be mutually exclusive, so rust/cargo would expect we can have multiple schedulers enabled.

Also, using cfgs seems like it would only get us so far, and be difficult to maintain. We have mutually exclusive functionality (e.g. adc_virtual and adc_dedicated, console and console_ordered, 15.4 and BLE) that would be hard to include on the same board.

> The other issue is that the boards will have a strange combination of what `configuration` board is created. Some things will only exist on the nRF, while some will only exist of OT. It seems like a weird mix-match of what is tested where

This is very true, but won't any solution have this problem? One issue is different hardware has different functionality. But also, different developers will have different priorities and different access to hardware, and will setup tests for boards they have access to. This heterogeneity seems inevitable.

**Comment by alistair23** [comment]
> I'm not sure how cfg features would work here. They aren't designed to be mutually exclusive, so rust/cargo would expect we can have multiple schedulers enabled.

It would be a little clunky to handle the configs. It [seems](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618) like there one day might be improvements but we can't count on that.

I don't disagree that cfgs aren't great. I do feel like they are better though then duplicate 80% of a board file over and over again to support various combinations of features.

Especially for core stuff like appid checking. Which I think every board should eventually support as an option, not just a handful of boards.

> This is very true, but won't any solution have this problem? One issue is different hardware has different functionality. But also, different developers will have different priorities and different access to hardware, and will setup tests for boards they have access to. This heterogeneity seems inevitable.

There are a few parts here. Obviously if the hardware doesn't support it then there is nothing that can be done. For example let's say we have BLE support, there would be

```
    nrf52840k-ble
    apollo3-ble
```

boards and no `opentitan-ble` board. For some board specific features I think that makes sense.

But what about appid checking? Let's say we have


```
    nrf52840k-appid-sha256
    apollo3-appid-sha512
    opentitan-appid-hmac256
```

I feel that it is confusing for new devs to determine what is going on. Does `opentitan` only support hmac256 and not sha512? Or is that all that has been added? It just feels like a confusing combination.

While if instead we had a cfg that ideally works on every board then it's simpler to see it something that can be enabled/disabled.

**Comment by alistair23** [comment]
We might need config boards. Especially for some of the less common features. Appid checking to me seems more like something we should eventually allow supporting for all boards with a config

**Comment by hudson-ayers** [comment]
Unfortunately I think this is just too much added code for this to be the primary mechanism by which we add tests...the maintenance overhead of each additional board is not insignificant (though I realize you currently carry that burden more than anyone!), and it feels like adopting this as a primary mechanism for in-kernel tests would add so many boards as to be quite painful.

> I bet there is a way to simplify the implementations of boards too, and someone suitably savvy and motivated could reduce the overhead of these configuration boards.

I agree that this is sorely needed and also possible. Honestly we would ideally have something like Linux device trees, but better type-checked, to configure individual boards.

**Comment by hudson-ayers** [comment]
I will admit that is a much smaller proportion than I expected. My new position is that it doesn't seem crazy to try this for a few tests and see how it goes for a little while.

**Comment by bradjc** [comment]
Now that #3871 is merged, I can add the kernel tests board to the PR as another example.

**Comment by bradjc** [comment]
One idea that came up on the call that I think would be good is to have a policy that all config boards have the string "test" in their name so there is no ambiguity that a particular board is for testing.

**Comment by bradjc** [comment]
Re: naming and organization:

I would prefer to keep these in `boards/` because 1) adding the noise to the top level further pushes the readme down the page and makes what isn't really supposed to be public become more public and 2) all of the places you type "make" to build a board are in the same folder.

Please suggest alternative names if you have any. I've come to like "configuration" because 1) it is one word without annoying underscores, 2) it doesn't have "test" in the name which collides with many other meanings of the word "test" (most notably cargo test), and 3) it does a reasonable job of describing what these are: new kernel configurations.

**Comment by bradjc** [comment]
I added the nrf52840dk kernel test board.

**Comment by lschuermann** [comment]
> Please suggest alternative names if you have any.

Well, that's a bikeshedding opportunity too good to pass on. My personal proposal would be "variant", in lieu of a name that has "test" in it. "Configuration" and "variant" are similar in spirit, but with "configuration" I fear that it might communicate to users that this is the intended way to "configure" boards like many other projects do akin to `make menuconfig`, whereas really these boards are not supposed to be exposed to users at all. "Variant" encapsulates the same concepts, but is less ambiguous in that it's "just another variant" of a board (or just _one particular_ configuration), instead of a mechanism to create them.

**Comment by phil-levis** [comment]
> This seems like it will end up with a **LOT** of boards.

A lot of boards is desirable/necessary. They are the top-level composition of a system. Having many separate boards seems better than conditionally compiled boards.

**Review by alevy — APPROVED** [review]

**Comment by alevy** [comment]
This has been discussed extensively and at this point just needs a second approval. The name of the folder is not ideal, but we decided to stop bike-shedding.

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
