### PR TITLE
OpenTitan: Bump the FPGA bitstream

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This PR builds on top of https://github.com/tock/tock/pull/2634

This PR bumps the OpenTitan bitstream SHA. This means three things
 1. Some small changes to handle the new design
 2. The OTBN tests no longer work as OTBN has been removed from the FPGA build. This isn't ideal, but we can't hold the work back on this
 3. We can enable the flash tests as https://github.com/lowRISC/opentitan/issues/4730 is now fixed

### Testing Strategy

The built in OpenTitan tests

### TODO or Help Wanted

@jrvanwhy  or @silvestrst can someone please upload a new release to https://storage.googleapis.com/artifacts.opentitan.org/

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — DISMISSED** [review]

**Comment by hudson-ayers** [comment]
Is merging this blocked on a new artifact upload?

**Comment by alistair23** [comment]
> Is merging this blocked on a new artifact upload?

Yep, it is

**Comment by hudson-ayers** [comment]
I'm not sure what to do about this. It looks like getting an updated artifact in permanent storage will be difficult. I can think of 5 options moving forward:

1. Go back to relying on short-lived build artifacts, forcing us to update this much more frequently
2. Store OT artifacts ourselves each time we update, on tockos.org or something. I recall that there might be license concerns with this approach?
3. Remove QEMU-based testing on OT from CI
4. Try to build OT in our CI (sounds like a *huge* pain)
5. Continue waiting on an update, meaning that for 2.0 we will continue to use a much older OT bitstream

**Comment by ppannuto** [comment]
Option 6, perhaps?:

Switch this to a federated testing model (i.e. as part of what @AnthonyQ619 and @goodoomoodoo are working on). That shifts the onus of have "working hardware" (valid bitstream) to the CI runner rather than as part of the Tock repo.

**Comment by jrvanwhy** [comment]
I've made some progress on being able to upload to the GCS bucket. Alistair, how do I find a suitable snapshot to upload? I'm not familiar with the OpenTitan repository's CI.

**Comment by hudson-ayers** [comment]
> I've made some progress on being able to upload to the GCS bucket. Alistair, how do I find a suitable snapshot to upload? I'm not familiar with the OpenTitan repository's CI.

https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=47452&view=logs&jobId=abe4affc-2ee4-512c-3bef-c664b244c306 is the latest snapshot.

**Comment by jrvanwhy** [comment]
> > I've made some progress on being able to upload to the GCS bucket. Alistair, how do I find a suitable snapshot to upload? I'm not familiar with the OpenTitan repository's CI.
> 
> https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=47452&view=logs&jobId=abe4affc-2ee4-512c-3bef-c664b244c306 is the latest snapshot.

@alistair23, can you confirm the snapshot Hudson linked works with this PR?

**Comment by alistair23** [comment]
Hey @jrvanwhy the latest snapshot should be fine.

Ideally though can you use this: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=45621&view=artifacts&pathAsName=false&type=publishedArtifacts ? That is the same commit that I am using for this PR

**Comment by jrvanwhy** [comment]
> Hey @jrvanwhy the latest snapshot should be fine.
> 
> Ideally though can you use this: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=45621&view=artifacts&pathAsName=false&type=publishedArtifacts ? That is the same commit that I am using for this PR

Okay, I uploaded that new snapshot. The URL is:

https://storage.googleapis.com/artifacts.opentitan.org/opentitan-earlgrey_silver_release_v5-157-ga28c280bb.tar.xz

Please let me know if I made a mistake, such as accidentally grabbing the wrong archive file (the nested archives is a bit confusing).

**Comment by alistair23** [comment]
Thanks @jrvanwhy ! That works and the tests are now passing. This is ready to merge.

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
