### PR TITLE
make: simplify cargo doc rule

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

-D warnings now works so we don't need the custom version.

### Testing Strategy

This patch failed CI: https://app.netlify.com/sites/docs-tockosorg/deploys/668d9722ca0c450008a48095

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
From Netlify:

```
3:20:37 PM:  Documenting tock-registers v0.9.0 (/opt/build/repo/libraries/tock-register-interface)
3:20:37 PM: error: cannot specify the `--color` option with `--json`
3:20:37 PM: error: cannot specify the `--color` option with `--json`
```

**Comment by bradjc** [comment]
Fixed.

**Review by lschuermann — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]
I am not sad to see that mess go.

**Review by brghena — COMMENTED** [review]
A bit late now, but the `--target-dir=$(TARGET_DIRECTORY)` got dropped here. Was it not important?

**Pull request merged**
