### PR TITLE
Parameterize debug_writer

### PR DESCRIPTION
**Pull request by kevtan**
### Pull Request Overview

In development, I found that I often had to increase the size of the debug buffer in order to see the debug output that I needed. Instead of finding and replacing every time (which was error prone), I thought it would be a good idea to parameterize the size of the debug buffer in order to make it quick, easy, and less error-prone to change the size of the debug buffer.

### Testing Strategy

The correctness should be able to be verified at a glance; compilation is successful.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Comment by kevtan** [comment]
Oops I thought that was the next step after approval!

**Comment by lschuermann** [comment]
> Oops I thought that was the next step after approval!

Merging is limited to people with write access to the repository. More importantly PRs are left open for some time for other maintainers and people to take a look. The official rules appear to be documented [here](https://github.com/tock/tock/blob/067d1c6d5b7997fa251445fc3b873e4f57fcbe6a/doc/CodeReview.md#4-reviews) and [here](https://github.com/tock/tock/blob/0dae1170866c512e6d184b9a307208edc4a72007/doc/threat_model/Code_Review.md).

**Review by lschuermann — APPROVED** [review]

**Comment by kevtan** [comment]
@lschuermann Thanks for the helpful links!

**Pull request merged**
