### PR TITLE
boards/opentitan: bump to latest master RTL SHA

### PR DESCRIPTION
**Pull request by twilfredo**
### Pull Request Overview

This patch series adds support for OpenTitan [latest master](https://github.com/lowRISC/opentitan/commit/7550a3512290c3c4df978fcc70112b787c963076) (**as of this PR**).  Most of the heavy lifting for this was done in https://github.com/tock/tock/pull/3056.

This PR updates the since changes, registers/irqs etc... to bring Tock up to speed.

Going forward: Latest master of OT will most likely work, I'll test any major  changes (maybe weekly) and update here as necessary. 

### Testing Strategy

Running OpenTitan tests on Verilator (with the latest master build of OT).

```
I00000 test_rom.c:98] Version: earlgrey_silver_release_v5-7719-g7550a3512, Build Date: 2022-09-29 11:24:47
I00001 test_rom.c:180] Test ROM complete, jumping to flash!
Unable to find otbn-rsa, disabling RSA support
OpenTitan initialisation complete. Entering main loop
check run AES128 CCM... 
AES CCM* encryption/decryption tests
aes_ccm_test passed: (current_test=0, encrypting=true, tag_is_valid=true)
aes_ccm_test passed: (current_test=0, encrypting=false, tag_is_valid=true)
aes_ccm_test passed: (current_test=1, encrypting=true, tag_is_valid=true)
aes_ccm_test passed: (current_test=1, encrypting=false, tag_is_valid=true)
aes_ccm_test passed: (current_test=2, encrypting=true, tag_is_valid=true)
aes_ccm_test passed: (current_test=2, encrypting=false, tag_is_valid=true)
    [ok]
check run AES128 ECB... 
aes_test passed (ECB Enc Src/Dst)
aes_test passed (ECB Dec Src/Dst)
aes_test passed (ECB Enc In-place)
aes_test passed (ECB Dec In-place)
    [ok]
check run AES128 CBC... 
aes_test passed (CBC Enc Src/Dst)
aes_test passed (CBC Dec Src/Dst)
aes_test passed (CBC Enc In-place)
aes_test passed (CBC Dec In-place)
    [ok]
check run AES128 CTR... 
aes_test CTR passed: (CTR Enc Ctr Src/Dst)
aes_test CTR passed: (CTR Dec Ctr Src/Dst)
    [ok]
check run CSRNG Entropy 32... 
Entropy32 test: first get Ok(())
Entropy test: obtained all 8 values. They are:
[00]: 735b27a0
[01]: 497b246f
[02]: 9a8f9420
[03]: 91618fe9
[04]: e07e680b
[05]: 01aec0b9
[06]: 3ca6b2a0
[07]: 19078a9d
    [ok]
[FLASH_CTRL] Test page read/write....
    [ok]
[FLASH_CTRL] Test page erase....
    [ok]
check hmac load binary... 
    [ok]
check hmac check verify... 
    [ok]
start multi alarm test...
    [ok]
check otbn run binary...
    [FAIL] No OTBN binary
Not running RSA tests
Not running RSA tests
check rsa key import... 
    [ok]
check rsa 4096 bit key import... 
    [ok]
Not running RSA tests
start SHA256 verify test
Sha256Test: Setting slice to 12..24
Sha256Test: Setting slice to 24..36
Sha256Test: Setting slice to 36..48
Sha256Test: Setting slice to 48..60
Sha256Test: Setting slice to 60..72
Sha256Test: Verification result: Ok(true)
    [ok]
check SipHash 2-4... 
    [ok]
[SPI] Setup spi_host0 partial_transfer... 
    [ok]
[SPI] Setup spi_host0 transfers... 
    [ok]
[SPI] Setup spi_host0 transfer...x2 
    [ok]
trivial assertion... 
    [ok]
```

### TODO 

Although QEMU still works for the tests we have now, we need to update some of the IRQs (patches to QEMU).

### Documentation Updated
The README changes required by this PR are all documented in https://github.com/tock/tock/pull/3220 .  No major changes required since last OT bump. I will send new update to update some OT paths when #3220 merges. 
 
- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by twilfredo** [comment]
@alistair23

**Comment by twilfredo** [comment]
Updates: 

- Disable `rsa_4096` testing as there's a hardware bug preventing functionality. See: https://github.com/lowRISC/opentitan/issues/15331
- Rebased on master
- Bumped to a newer OT commit <ef2c138e048e191c4fe9d3bba0bc4fd869346fd0> [Passing all tests on Verilator] - Needs to double check on HW
- Updates commit sha in README

**Comment by bradjc** [comment]
@alistair23

**Comment by alistair23** [comment]
It looks like https://github.com/lowRISC/opentitan/issues/15331 is almost fixed (PR is pending) so let's wait for https://github.com/lowRISC/opentitan/issues/15331 to be fixed

**Comment by twilfredo** [comment]
> It looks like [lowRISC/opentitan#15331](https://github.com/lowRISC/opentitan/issues/15331) is almost fixed (PR is pending) so let's wait for [lowRISC/opentitan#15331](https://github.com/lowRISC/opentitan/issues/15331) to be fixed

oh great! moving to draft for now

**Comment by hudson-ayers** [comment]
Looks like the upstream fix was merged

**Comment by twilfredo** [comment]
Updates: 
- Rebased
- Bumped to the latest OT with the RSA fixes (Updated commit SHA in readme)
- Ran Verilator tests (without RSA) - All OK

Todo:
- Run RSA tests on HW make sure things work! @alistair23

**Review by bradjc — APPROVED** [review]

**Comment by twilfredo** [comment]
@alistair23 I was able to replicate the `otbn` failure on Verilator, but it only occurs only if we ran the `csrng` tests prior. So if you just ran the `otbn` tests by itself it would pass (at-least on Verilator). Either way this fixes that https://github.com/tock/tock/pull/3249/commits/09b379f8cf36ee124a499ffd76a337abdf80829b

**Comment by twilfredo** [comment]
With these changes, all tests are now be passing on Verilator (even the RSA ones). I let the tests run overnight took ~10-12 hours to complete (on a 5950X).

**Review by hudson-ayers — DISMISSED** [review]

**Comment by twilfredo** [comment]
@alistair23  should be ready now!
Updates:

- Force the `flash_ctrl` tests to run last to not overwrite the peripheral handle.
- Squashed all the commits.

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
