### PR TITLE
kernel: move main to sched.rs

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

`main()` was in lib.rs, which was a little tricky to find. Also `do_process()` in sched.rs had to be public, but is only called in one place. This merges the two, so all scheduling and main loop code is in the same place, and renames the file to main.rs so it is obvious where everything starts.

### Testing Strategy

This pull request was tested by compiling.

### TODO or Help Wanted

I think this is easier to understand, but there may be good reasons to leave it as it was.

### Documentation Updated

- [x] Kernel: Updated the relevant files in `/docs`, or no updates are required.
- [x] Userland: Added/updated the application README, if needed.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
Small thoughts:

Maybe something like main_loop instead of main -- I'm afraid that "main" is
overloaded an people might somehow think it's the actual entry point.

Isn't src/main.rs reserved to be the file that Cargo uses to find the entry
point for standalone executables? I'm on highly dubious Internet at the
moment, so hard to google, but I thought src/main.rs was special / at least
a convention in Rust in a way that we aren't using here.

Agree with the general restructure, just think we need to be careful to not
conflict with broader expectations in the Rust community.

**Comment by phil-levis** [comment]
I agree with the concerns about main() as a name. This really really isn't main; it's the entry point. Among other things, it doesn't have string command line arguments! I'd suggest kernel_loop.

**Comment by bradjc** [comment]
Really there are maybe three issues here:

1. Where should the function currently called `main` be?
2. What should the function currently called `main` be named?
3. What should the file that the function currently called `main` is in be named?

I'm most invested in moving `main` out of lib.rs since I find that to be confusing, non descriptive, and inconsistent with our other crates.

Therefore, I propose:
- Moving the function currently called `main` to sched.rs.
- Renaming the function currently called `main` to `kernel_loop`.
- Leaving the filename of sched.rs as is.

Thoughts?

**Comment by ppannuto** [comment]
That sounds like a good plan to me.

**Pull request merged**
