### PR TITLE
Question: do we want to use shorter operation style?

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request changes instances of `a = a + 1` to `a += 1`. I think it is reasonable to use a constant style here, but I wanted to see what people think.

https://rust-lang.github.io/rust-clippy/master/index.html#assign_op_pattern

### Testing Strategy

This pull request was tested by travis.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
If anything, I think I'd want to enforce the other way. I've been trained long enough on it that `+=` is fine, but I have a real hard time reading `>>=` or `&=`, especially the latter as `&` does so much other reference-related magic that now I'm spending a minute thinking about whether that's doing something magic to the assingment, not seeing it as a bitwise operator.

**Comment by phil-levis** [comment]
I think this exactly the kind of very low-level thing that’s so setting dependent that it’s detrimental to try to standardize. I mean, are we going to block a PR for a = a + 1? 

Eg much better would be to standardize our uses of Cell types so they are fully consistent. 

Phil [sent from a phone]

**Comment by ppannuto** [comment]
Agreed generally, but in this case it's towards the configuration of an
automated tool (built-in to the rust ecosystem) that will run as part of
`make format` -- I'm much more inclined to support this kind of consistency
if the bar to enable it is basically none.

I don't think this is the type of thing that should be enforced manually

**Comment by bradjc** [comment]
Ok well this might be something to revisit then, I'm not sure we can reliably automatically update code yet.

**Pull request closed without merging**
