### PR TITLE
nrf51: Update uart to new regs interface

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

nrf51: Update uart to new regs interface

### Testing Strategy

Compile-tested only.

### TODO or Help Wanted

Someone with nrf51 HW make sure this doesn't break anything.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] ~~Ran~~ Battled `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
Anyone have an nrf51dk board to test this on?

**Comment by niklasad1** [comment]
@ppannuto @bradjc I have but `nRF51-DK` doesn't work on master so I assume this doesn't work either!

**Comment by alevy** [comment]
I'll be able to test Monday...

**Comment by niklasad1** [comment]
Tested successfully with https://github.com/tock/libtock-c/tree/master/examples/tests/printf_long

**Pull request merged**
