### PR TITLE
capsules: split into `core/` and `extra/` (implementing #3346)

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

This pull request splits capsules into `core/` and `extra/` as proposed and discussed in #3346 for #3312.

### Testing Strategy

This pull request was tested by `cargo check`.

### TODO or Help Wanted

This PR is still in development. Specifically, I'd like to check whether it actually moves capsules into the correct crates, and update documentation pointing to capsules, as well as updating the capsules (now `core/`) README.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
Took a quick look through this and I think it is pretty much exactly what I had in mind! 

> updating the capsules (now core/) README.

I think we probably want a capsules/README as well as a capsules/core/README and a capsules/extra/README. The top level one should just explain the basic division of capsules and where new capsules should be placed.

**Comment by lschuermann** [comment]
I have split up the README between `core/` and `extra/` accordingly, and also introduced a new top-level capsules README file.

One additional thing to note: as part of this refactoring, I needed to promote the `stream` module, implementing a macro-infrastructure for encoding & decoding byte-streams, to a module in `core`. This is because `virtual_aes_ccm` uses this module, and all virtualizers are to be kept in `core`. I don't think that is going to cause issues, but am open to other approaches.

Also, this PR currently does not move all virtualizers into their own module. I'm personally in favor of doing that, as it helps to separate the different reasoning behind a given module being in core: either it's a well-vetted module crucial to a given boards' operation, or it is a virtualizer and thus only bridging kernel-internal interfaces and not interacting with external hardware or userspace directly. I'd appreciate feedback on this.

**Review by alevy — DISMISSED** [review]

**Review by bradjc — DISMISSED** [review]
I like the change, but I think having the default in boards as "capsules_core" and "capsules_extra" makes sense (particularly if we have more crates in the future).

**Comment by lschuermann** [comment]
I will rename `{core,extra}_capsules` to `capsules_{core,extra}`, and split the virtualizers into their own module, as discussed on today's call. Thanks for the feedback!

**Comment by lschuermann** [comment]
Okay, I think the discussed changes should be addressed now.

**Review by hudson-ayers — APPROVED** [review]

**Review by brghena — DISMISSED** [review]

**Comment by brghena** [comment]
Okay, this is a dumb question, but what makes it so that the module is named "capsules-core", but when you import it inside rust code it's "capsules_core"? Is that some Rust rule that I just didn't know?

**Comment by lschuermann** [comment]
> but what makes it so that the module is named "capsules-core", but when you import it inside rust code it's "capsules_core"?

According to the [Rust reference on external crates](https://doc.rust-lang.org/reference/items/extern-crates.html), apparently this is a hard-coded rule: "When naming Rust crates, hyphens are disallowed. However, Cargo packages may make use of them. In such case, when Cargo.toml doesn't specify a crate name, Cargo will transparently replace - with _".

**Comment by brghena** [comment]
Thanks for the link. Makes me feel a little better that I didn't understand what was happening.

There's no reason to "fix" anything. I was just trying to figure out how it worked and couldn't find it in the code anywhere.

**Review by hudson-ayers — APPROVED** [review]

**Review by bradjc — APPROVED** [review]

**Pull request merged**
