### PR TITLE
capsules: remove virtual_[digest|flash|sha].rs which do not virtualize

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

These capsules do not actually provide virtualized digest resources, and I think it's better to not give the impression that we support virtualized digest resources when we do not currently.

### Testing Strategy

n/a

### TODO or Help Wanted

Thoughts? Obviously another option is to re-write the virtualizers, but someone needs to be willing to do that.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Review by lschuermann — APPROVED** [review]
We can always resurrect these from git.

**Comment by hudson-ayers** [comment]
Wait, so like...what do these do now?

**Comment by bradjc** [comment]
> Wait, so like...what do these do now?

Nothing, really. They insert a little code when a HIL function is called, but for the most part the code isn't used. This is because the callbacks are not handled by these capsules, but instead passed directly to the upper layer.

**Review by alevy — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Comment by hudson-ayers** [comment]
This still breaks CI

**Comment by bradjc** [comment]
Yeah if there is consensus to doing this then I can remove their uses.

**Comment by hudson-ayers** [comment]
I am on board

**Review by phil-levis — APPROVED** [review]

**Pull request merged**
