### PR TITLE
chip: rename Ibex to EarlGrey

### PR DESCRIPTION
**Pull request by silvestrst**
Currently EarlGrey is the first and only OpenTitan SoC design, with Ibex CPU at the heart.

Ibex being a CPU does not have any knowledge of EarlGrey peripherals, and hence was misrepresented in Tock. This has caused some confusion to how exactly it was intended to be used, and did not achieve the goals of being stand alone crate, as it was coupled to heavily with the OpenTitan board.

### Pull Request Overview

This pull request renames Ibex crate to EarlGrey, because de facto - that's what it is.

This change also makes #1741 more reasonable.

### Testing Strategy

- [x] Should be tested on FPGA or verilator before merging.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
It looks like there are a few references to ibex still around that should probably change (especially the ones in doc comments and the one in tools)
```
hudson: ~/tmp_tock ((HEAD detached at s2/silvestrs/tock-ibex-to-earlgrey)) $ rg ibex
tools/update_chip_support.py
27:            'lowrisc': ['ibex'],

capsules/src/hmac.rs
7://! let hmac = &ibex::hmac::HMAC;
10://! digest::Digest::set_client(&ibex::hmac::HMAC, mux_hmac);

capsules/src/mlx90614.rs
9://! let mux_i2c = components::i2c::I2CMuxComponent::new(&ibex::i2c::I2C)

boards/components/src/hmac.rs
9://!    let mux_hmac = components::hmac::HmacMuxComponent::new(&ibex::hmac::HMAC).finalize(

doc/wg/opentitan/README.md
55:- `chips/ibex`

capsules/src/usb/cdc.rs
39:/// Platform-specific packet length for the `ibex` USB hardware.

capsules/src/usb/usbc_client.rs
32:/// Platform-specific packet length for the `ibex` USB hardware.

hudson: ~/tmp_tock ((HEAD detached at s2/silvestrs/tock-ibex-to-earlgrey)) $ rg Ibex
boards/README.md
23:| [Nexys Video OpenTitan](opentitan/README.md)                         | RISC-V RV32IMC  | Ibex           | custom     | custom         |

chips/earlgrey/README.md
4:Ibex RISC-V compliant processor.

boards/opentitan/src/main.rs
102:    // Ibex-specific handler
```

**Comment by silvestrst** [comment]
@hudson-ayers good catch, thank you!

**Comment by silvestrst** [comment]
I have changed most references of ibex to earlgrey, I think the ones that are left - are justified.

**Pull request merged**
