### PR TITLE
Travis memory reporting example, don't merge

### PR DESCRIPTION
**Pull request by hudson-ayers**
This is an example PR to show how #1701 will work once merged into master.

The example PR here modifies 3 boards. It removes the RNG from Imix and Hail, and increases the APP_MEMORY size for a nucleo board by 20kB. Because APP_MEMORY is not counted as part of kernel memory, there is no diff shown for the nucleo board.

Click "see statuses" to see the reported diff of code size / memory for each board.

### CODE REVIEW

**Comment by brghena** [comment]
Now that the change to the nucleo is ignored, could you add to that PR so that it requires additional (or less) RAM?  (keep the change to app_memory too so we can see that it's discounted)

**Comment by brghena** [comment]
I'm pretty dubious about whether kernel RAM counting is working here. You changed 4 to 2000 and it grew by _precisely_ 100%?

**Comment by hudson-ayers** [comment]
> I'm pretty dubious about whether kernel RAM counting is working here. You changed 4 to 2000 and it grew by _precisely_ 100%?

Well, I am just using the output of the script from #1695 . 
I tried smaller changes (4 -> 2 and even 4 -> 200) and it had no impact on kernel RAM counting because it just changed the amount of RAM wasted after the `DebugWriteComponent`. I think it growing by exactly 100% is an artifact of how this amount of wasted RAM is determined (which I am not sure about).

(snippet of outout with PROCESSES = 2 elements)
```
Kernel occupies 101920 bytes of RAM
    4096        stack
   95872        uninitialized variables
    1952        initialized variables
   97824        variables total
Applications allocated 85536 bytes of RAM

  ! 3 bytes wasted after nucleo_f429zi::io::WRITER
  ! 6528 bytes wasted after components..debug_writer..DebugWriterComponent
Variable groups (RAM): 89929 bytes
  capsules::console::READ_BUF:             64 bytes
  capsules::console::WRITE_BUF:            64 bytes
  capsules::virtual_uart::RX_BUF:          64 bytes
  kernel::common::deferred_call:           4 bytes
  kernel::common::dynamic_deferred_call:   4 bytes
  kernel::debug::DEBUG_WRITER:             4 bytes
  nucleo_f429zi::APP_MEMORY:               85536 bytes
  nucleo_f429zi::CHIP:                     4 bytes
  nucleo_f429zi::PROCESSES:                16 bytes
```
(snippet of output with PROCESSES = 200 elements)
```
Kernel occupies 101920 bytes of RAM
    4096        stack
   95872        uninitialized variables
    1952        initialized variables
   97824        variables total
Applications allocated 85536 bytes of RAM

  ! 3 bytes wasted after nucleo_f429zi::io::WRITER
  ! 4944 bytes wasted after components..debug_writer..DebugWriterComponent
Variable groups (RAM): 91513 bytes
  capsules::console::READ_BUF:             64 bytes
  capsules::console::WRITE_BUF:            64 bytes
  capsules::virtual_uart::RX_BUF:          64 bytes
  kernel::common::deferred_call:           4 bytes
  kernel::common::dynamic_deferred_call:   4 bytes
  kernel::debug::DEBUG_WRITER:             4 bytes
  nucleo_f429zi::APP_MEMORY:               85536 bytes
  nucleo_f429zi::CHIP:                     4 bytes
  nucleo_f429zi::PROCESSES:                1600 bytes
```

However I think that raises a good point -- perhaps I should be subtracting out "wasted" RAM, because this RAM is likely to be used when additional variables are added that are stored in RAM? Thoughts?

**Comment by brghena** [comment]
I think subtracting out wasted RAM like you did is exactly the correct call. That space only exists due to  MPU alignment issues for app memory anyways.

**Pull request closed without merging**
