### PR TITLE
arch: add cortex-m4f crate

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

This adds a separate crate for ARM Cortex-M4F (aka Cortex-M4 with FPU extensions). This is ARM lingo for hard float support. Currently, Tock does not take advantage of hard float capability. This M4F crate does not change that, it's basically a clone of the M4 crate, but it allows us to differentiate which chips do have FPUs and is step zero for adding hard float support.

### Testing Strategy

This pull request was tested by compiling.

### TODO or Help Wanted

N/A.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by alistair23** [comment]
The Apollo3 is also a M4F

**Comment by ppannuto** [comment]
Added apollo3

**Review by alistair23 — APPROVED** [review]

**Review by alevy — APPROVED** [review]

**Review by alevy — COMMENTED** [review]
I guess my one question is whether this should really be a separate crate rather than, say, something like a feature or a different struct or something in the same crate.

I think we can maybe determine this after the fact when it's been implemented more fully.

**Comment by alevy** [comment]
@ppannuto what are the remaining steps to implement this? Is it "just" twiddling a bit to enable hard FPU and modifying register stacking/popping/saving to include FPU registers in interrupt handlers?

**Comment by ppannuto** [comment]
Re separate crate, it's really just a quirk of naming* that it's cortex-m4f rather than something like cortex-m5. I made it a separate crate for the same reasons we have m0, m3, and m4 crates, from ARM's perspective they're all different [and progressive supersets]:

image
(Ugh, now noting that that slide from one of my class lectures really should have the M4 arrow in the bottom end at the red, and an M4F arrow that goes out to the yellow...)

> *Indeed, a Cortex M4 is really a "Cortex M3 with DSP extensions" and a M4F is a "Cortex M3 with DSP and FPU extensions", but one got a dedicated name 🤷🏼 

We made the call to have a dedicated crates for this a while ago [which I think is good for clarity], this just continues the trend.

**Comment by ppannuto** [comment]
I think the minimal next step is actually a version where hard float is enabled in kernel mode but disabled in userspace. That lets the kernel take advantage where (and if) it makes sense without complicating any of the ABI questions.

ARM has a bunch of interesting features for mixed code (e.g., when context switching to userspace, there's a sentinel bit that's set if any hard floating point instructions run, and if it's still clear when an interrupt fires, it won't bother stacking the floating state) — I think there's a bit of exploring the design space of mixing soft-or-hard kernel and soft-or-hard apps to be done.

Step zero here is just flagging which chips are really M4F's and not M4's and categorizing them correctly. I suspect where features might become most relevant is for boards that have M4F's to opt in or out of allowing hard float in kernel, userspace, etc.

**Comment by alevy** [comment]
> I think the minimal next step is actually a version where hard float is enabled in kernel mode but disabled in userspace. That lets the kernel take advantage where (and if) it makes sense without complicating any of the ABI questions.

(just discussing here, doesn't block this PR or necessarily future work)

Maybe? The typical "optimization" is to enable floating point in userspace and no the kernel, since it's more rare for the kernel to need floating point (some of the sensor computations are maybe anomalous in Tock, so maybe), and if only userspace uses the FPU you can avoid saving those registers whenever you plan to switch back to the same processes (since the kernel is trusted not to trample them).

If the kernel uses the FPU, unless you can guarantee that processes aren't able to access those registers at all, you have to always store them on context switch, no?

**Comment by lschuermann** [comment]
I would have appreciated some more discussion on the concrete net steps that follow this PR prior to merge. For instance, is it safe to switch the Rust toolchain to compile for hard-float targets? I guess mostly likely the answer is yes, with perhaps some changes to the arch crate that enables floating point support for while the target is in the kernel.

While the changes themselves here are uncontroversial and unlikely to break anything in isolation, it's slightly weird to have chips use a "hard-float" arch crate, but potentially not work when compiled for a hard-float target triple.

**Comment by lschuermann** [comment]
An orthogonal remark, I may have a different understanding of what the "P-Upkeep" label is indicating. My intuition was that this is solely for changes that, e.g., fix spelling, comments, or other such minor mechanical changes. I guess that, again, this change is non-breaking and uncontroversial in isolation, but it's part of a larger effort for which "P-Upkeep" seems less appropriate to me. :smile:

**Comment by lschuermann** [comment]
Okay, this makes sense, I appreciate the clarification.

**Pull request merged**
