### PR TITLE
boards: add wm1110-dev board

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This is a new board with nRF52840 and LoRa: https://www.seeedstudio.com/Wio-WM1110-Dev-Kit-p-5677.html

Pretty easy to bring up because it's based on the nrf52840.

We've verified being able to use the temperature sensor and communicate with the LR1110 radio.

Code for userspace under development and will be based on https://github.com/Seeed-Studio/Seeed_Wio_WM1110_Dev_Board/tree/master.

### Testing Strategy

running on the board

blink and c_hello work

### TODO or Help Wanted

~~I need to get the bootloader and directions sorted out. Barebones directions now but need to make them more user friendly.~~

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by lschuermann — APPROVED** [review]
Seems pretty uncontroversial, seeing this is -- for now -- just another nRF52840DK board.

**Comment by bradjc** [comment]
I'm waiting on re-writing the artifact publish CI task for tock-bootloader so I can add installing the bootloader to these instructions.

**Comment by bradjc** [comment]
Ok this is ready to merge. This board file works, and we've verified the temperature sensor works and that we can communicate with the LR1110.

I think at this point we can work on the library in userspace without needing to change the board definition.

**Review by ppannuto — APPROVED** [review]

**Comment by bradjc** [comment]
Last call!

**Pull request merged**
