### PR TITLE
Sam4l based addrs

### PR DESCRIPTION
**Pull request by hudson-ayers**
### Pull Request Overview

This PR modifies main.rs for the Imix such that each Imix generates a 16 bit short address for its source MAC address from the serial number of the sam4l on the board. It also adds a utility function to generate link local IPv6 addresses from an EUI 64 (mac address), and uses this to set one of the possible ipv6 source addresses for the device (by adding it to the interface list). This PR goes hand-in-hand with an upcoming PR that will add udp send/rx apps for use at the Sensys tutorial. This PR also updates documentation for the networking stack to reflect the updated interface for configuring addresses.

### Testing Strategy

I tested this by flashing multiple Imixes with the app and confirming that each generated a unique, but consistent address, and that I could use these addresses to send/receive UDP packets as expected.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
@bradjc so you are suggesting I assign each board a number at random (or sequentially), label the boards accordingly, and then program it into the bootloader attr page for each device? It seems like that is as much of a pain as using the sam4l serial number and then labeling each board with the last 4 hex digits of that number, unless I am misunderstanding

**Comment by bradjc** [comment]
>@bradjc so you are suggesting I assign each board a number at random (or sequentially), label the boards accordingly, and then program it into the bootloader attr page for each device? It seems like that is as much of a pain as using the sam4l serial number and then labeling each board with the last 4 hex digits of that number, unless I am misunderstanding

Yup 😄. This is just based on my experience, that getting the ID off of a board is more work than putting one on. Also, I _strongly_ recommend putting the full ID on the label on the board, and not just the part that changes between boards. This is again from experience, the first board I made I only used the last couple hex digits, which was fine for a while until some time passed and I had other devices, and it became a pain to lookup the whole ID when I could no longer remember it.

**Comment by ppannuto** [comment]
+1 to the full ID on the board, if not for you for the rest of us :D

**Comment by bradjc** [comment]
Alas, I overstated a bit on the call yesterday about reading attributes from the kernel. Here is the code I was referring to: https://github.com/lab11/signpost-software/blob/master/signpost/kernel/signpost_drivers/src/signpost_tock_firmware_update.rs

All of the properties for that particular firmware upload mechanism were stored in the next page of flash, and not as attributes. So the reading/writing flash code is applicable, there isn't tock/rust code that parses the key-value attribute structure (although the format is pretty simple).

**Comment by hudson-ayers** [comment]
@bradjc sounds good, I think you are right that eventually we should be flashing the boards with sequential serial numbers in the attributes page and reading those from the kernel. I have been assigning a 48-bit serial number on each of the new Imixes that we flash, and labeling the bags of those Imixes accordingly (this was already handled by the existing Imix commissioning script). Given that I have 4 days before I fly to Sensys, and a lot going on in that time, I still think we should probably merge this code now, and then I can write the code to parse the bootloader attributes and assign the address that way for post-sensys

**Pull request merged**
