### PR TITLE
Clippy: Move configuration to Cargo.toml

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

As of last year I think (https://github.com/rust-lang/rfcs/pull/3389) we can now control clippy configs in the workspace Cargo.toml. This means we do not need our run_clippy script and that `cargo clippy` just works.

The downside is every Cargo.toml needs

```
[lints]
workspace = true
```

but what can you do.

### Testing Strategy

travis

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by lschuermann — APPROVED** [review]
Woohoo! Fewer magic Makefile incantations!

**Review by ppannuto — APPROVED** [review]

**Comment by brghena** [comment]
Looks like others have run into the inheritance problem as well: https://github.com/oxidecomputer/omicron/pull/5715

This seems to be the relevant issue for inheritance: https://github.com/rust-lang/cargo/issues/12208

**Review by brghena — APPROVED** [review]
I wonder how often we're going to forget to add this to a `Cargo.toml` when making a new one? Hopefully that you've added them to every example in Tock means people will just copy-paste and won't forget it.

**Comment by bradjc** [comment]
Worse, if you do forget, you might end up fixing clippy lints that seem "odd" because they are on by default but all other tock code doesn't use them.

**Review by alevy — APPROVED** [review]

**Comment by hudson-ayers** [comment]
the best things about this is that `cargo clippy --fix` just works now, which is sooo nice

**Pull request merged**
