### PR TITLE
boards/redboard_artemis_nano: Setup initial tests

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

Setup the Rust tests for the Apollo3 board

### Testing Strategy

Run the tests on the board

### TODO or Help Wanted

N/A

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
I think its great to have this simple approach to testing more boards. We should eventually move the multi-alarm test into `capsules/` in some non-board specific way rather than duplicating the file for every board.

**Review by bradjc — APPROVED** [review]
I assume if we have to remove `#![feature(custom_test_frameworks)]` from one board someday it isn't much more difficult to remove it from two.

**Comment by alistair23** [comment]
Ping!

**Pull request merged**
