### PR TITLE
Remove &dyn references from GPIO-related HILs and capsules.

### PR DESCRIPTION
**Pull request by gendx**
### Pull Request Overview

This pull request experiments with removing `&dyn` references from GPIO-related capsules, as a supporting example for #1761.

Until now, the capsules were using dynamic references to use GPIO pins, even though for a given board/chip the GPIOs have a type known at compile time. This pull request proposes to replace such dynamic references with explicit types.

The resulting code is a bit more verbose, but surprisingly not so much. Most of the extra code comes from components, where `static_init_half` is now necessary to instantiate the static types that are now generic.

By applying this refactoring to the most common capsules (GPIO, button, LED), savings of the order of ~1KB can be obtained on the boards (depending on how many GPIOs are declared by the board). More savings could be obtained by extending this refactoring to all capsules using GPIOs. And more generally many HILs in the kernel rely on `&dyn` references, so removing them from HILs and capsules in general could achieve even bigger savings.

Before:

```
   text	   data	    bss	    dec	    hex	filename
 102400	   3196	  62336	 167932	  28ffc	/tock/target/thumbv7em-none-eabi/release/hail
 164864	   3272	  54072	 222208	  36400	/tock/target/thumbv7em-none-eabi/release/imix
  68609	   1952	  79968	 150529	  24c01	/tock/target/thumbv7em-none-eabi/release/nucleo_f429zi
```

After:

```
   text	   data	    bss	    dec	    hex	filename
 101888	   3196	  62336	 167420	  28dfc	/tock/target/thumbv7em-none-eabi/release/hail
   -512       =       =            -200
 163840	   3272	  54072	 221184	  36000	/tock/target/thumbv7em-none-eabi/release/imix
  -1024       =       =            -400
  66561	   1952	  79968	 148481	  24401	/tock/target/thumbv7em-none-eabi/release/nucleo_f429zi
  -2048       =       =            -800
```

### Testing Strategy

This pull request was tested by building a few boards and checking the binary size. Not much more testing at this stage.

### TODO or Help Wanted

This pull request still needs:
- Feedback about such a revamp of the HIL.
- Feedback about whether reducing code size by this method is useful (see also #1663).
- Feedback about the components.
- Updating the documentation.
- Testing on physical boards.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by gendx** [comment]
Note: it seems that these capsules used to be parameterized by the GPIO pin type before the last revamp of the HIL (#1297). However:
- At that time, dynamic references were not explicitly marked as such in the code, so this aspect might have been overlooked.
- The HIL redesign also changed many other things.
- I here propose some code size measurements that show some gains, and code size is of interest at least for some Tock users (#1663).

**Comment by gendx** [comment]
Awesome!

Before I extend this to the other boards, any feedback on the components changes? I moved the GPIO pins from the `finalize()` to the `new()` part, but maybe that's not the intended use (I'm still confused by the semantics of `new` vs. `finalize`)?

**Comment by ppannuto** [comment]
> Before I extend this to the other boards, any feedback on the components changes? I moved the GPIO pins from the finalize() to the new() part, but maybe that's not the intended use (I'm still confused by the semantics of new vs. finalize)?

🤷 it looks fine to me -- then again, I'm also in support of collapsing those into one function as proposed in #1618. Maybe @bradjc has opinions.

**Comment by bradjc** [comment]
> Awesome!
> 
> Before I extend this to the other boards, any feedback on the components changes? I moved the GPIO pins from the `finalize()` to the `new()` part, but maybe that's not the intended use (I'm still confused by the semantics of `new` vs. `finalize`)?

Looks good to me.

**Comment by ppannuto** [comment]
This does technically touch a HIL, so it probably qualifies as significant. It's also been in the review queue for a while though, so I think we can move reasonably quickly on this once updated and fully implemented.

**Comment by gendx** [comment]
Rebased and migrated all boards. Where is the size report summary supposed to show?

**Comment by hudson-ayers** [comment]
Click  "details" next to the "benchmarks" check, then click the "size report" step. (I included your change to print the git diff there, but it has made the report a little cluttered).

**Comment by gendx** [comment]
> Click "details" next to the "benchmarks" check, then click the "size report" step. (I included your change to print the git diff there, but it has made the report a little cluttered).

Ok, thanks. I thought there was some pipeline to show the results directly on GitHub.

**Comment by hudson-ayers** [comment]
> > Click "details" next to the "benchmarks" check, then click the "size report" step. (I included your change to print the git diff there, but it has made the report a little cluttered).
> 
> Ok, thanks. I thought there was some pipeline to show the results directly on the pull request page.

That pipeline currently only works for PRs submitted from branches on the upstream repo, due to limitations with how Github allows commit status posting. A plan is in the works to get around this limitation by hosting part of the CI on a local server where secrets can safely be stored.

**Comment by gendx** [comment]
I updated the usage of affected components as well. Will wait a day in case anyone has something to say.

**Comment by alistair23** [comment]
This PR is still marked as RFC. Is it no longer an RFC?

**Comment by gendx** [comment]
> This PR is still marked as RFC. Is it no longer an RFC?

Indeed.

**Pull request merged**
