### PR TITLE
netlify: try cacheing the build if we can

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

This should hopefully speed up netlify builds.

### Testing Strategy

You're looking at it.

### TODO or Help Wanted

Ignore this while I iterate on netlify if needed.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make format`.
- [ ] Fixed errors surfaced by `make clippy`.

### CODE REVIEW

**Comment by lschuermann** [comment]
> You're looking at it.

Awesome :tada: 

---

The ever pressing issue with caching: what happens if the cache is corrupt, the tooling incorrectly does not consider the cache outdated or something breaks in an unexpected way? I've never seen that with `rustdoc`, `cargo` failed me a few times here. I've not run that many `rustdoc` builds though.

How easy is clearing the cache? Do we want to peridoically (after `n` days / after `x` runs) clear the cache to avoid carrying dead/invalid/corrupt artifacts from build to build?

**Comment by ppannuto** [comment]
Same as any other CI infra, there's a button on netlify's site to clear the cache (restricted to netfliy project owners; but Tock has an organization account in netlify that several core members are part of).

**Comment by ppannuto** [comment]
There seems to be an upstream error with caching. I've submitted a support issue:
https://community.netlify.com/t/error-with-cache-using-build-plugin-hangs-when-cache-asked-to-list-after-store/15327

**Comment by ppannuto** [comment]
Tracking upstream:
 - https://community.netlify.com/t/build-plugin-cache-not-actually-cacheing-anything/15721
 - https://github.com/netlify/build/issues/1225

**Comment by bradjc** [comment]
Closed for #2028

**Comment by ppannuto** [comment]
I don't really want to close this PR as github seems to eventually age-out and remove stale branches without something active pointing to them (I haven't completely figured out when this happens). This code is still correct once Netlify fixes the issues upstream.

**Comment by hudson-ayers** [comment]
The upstream issue has been fixed!

This still needs a rebase and to be tested again though

**Comment by hudson-ayers** [comment]
The cache now works! This reduces total deploy time from ~6 minutes 20 seconds on the last pre-cache deploy to ~4 minutes 40 seconds on the cached deploy. More importantly, it probably extends the number of builds we can run without exceeding any limits on our account.

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
