### PR TITLE
bump up nightly version to 2020-09-16

### PR DESCRIPTION
**Pull request by JOE1994**
### Pull Request Overview

This PR bumps up the nightly Rust version for Tock.
(From `nightly-2020-06-03` to `nightly-2020-09-16`)

#### Motivation for bumping up the nightly version
Current version of nightly (`2020-06-03`) does not fully support the new `asm!` macro syntax described in the [inline-asm RFC](https://github.com/Amanieu/rfcs/blob/inline-asm/text/0000-inline-asm.md).
**Writing multi-line inline asm as described in the RFC is not supported by the current nightly version.**

* Example (compiles in latest nightly, does not compile in `nightly-2020-06-03`)
```rust
// ~~~~
asm!(
        "mov    r1, 0     /* r1 = 0 */",
        "tst    lr, #4    /* bitwise AND link register to 0b100 */"
);
```
* Error message from `nightly-2020-06-03`
```
error: expected one of `const`, `in`, `inlateout`, `inout`, `lateout`, `options`, `out`, or `sym`, found `"tst    lr, #4    /* bitwise AND link register to 0b100 */"`
   --> arch/cortex-m/src/lib.rs:402:9
    |
401 |         "mov    r1, 0     /* r1 = 0 */",
    |                                         - expected one of 8 possible tokens
402 |         "tst    lr, #4    /* bitwise AND link register to 0b100 */"
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected token
```

### Testing Strategy

This PR was tested by building the Tock kernel for the `hail` board and testing the `blinky` example on it.

### TODO or Help Wanted
Are there any checks to be done before bumping up the nightly version?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by alistair23** [comment]
You need to update the version in a few other places as well. There is a script in Tock to help with this: https://github.com/tock/tock/blob/master/tools/update_rust_version.sh

**Comment by alistair23** [comment]
@bradjc is looking at doing a 1.6 release soon. I'm not sure if this should be before or after the release.

Considering the alarm PR isn't yet merged maybe this should go first?

**Comment by JOE1994** [comment]
> @bradjc is looking at doing a 1.6 release soon. I'm not sure if this should be before or after the release.

Since this PR is not an urgent one, I can close this PR for now and try again later after the new release lands to master.

p.s. I'm also not sure how to resolve the CI error on macos.

**Comment by bradjc** [comment]
Yeah let's update the version first thing after 1.6.

**Pull request closed without merging**
