### PR TITLE
Tock Register Interface: help ensure correct use

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates the tock register interface in two ways:

1. It removes the `new()` functions for `ReadWrite`, `ReadOnly` and `WriteOnly` register types. Calling `new()` on these is useless, as the result is the same as having any normal variable since `new()` is not setting the _address_ of the underlying value, just a temporary value.

2. It sets `ReadWrite`, `ReadOnly` and `WriteOnly` as `#[repr(transparent)]` since for the aliasing we do to work we want to ensure that they only take up `T` worth of memory.

### Testing Strategy

This pull request was tested by travis.

### TODO or Help Wanted

The USB library for the SAM4L seems to use `new()`. I'm not sure why, what it is trying to do, and if it actually works. This needs to be changed (perhaps to a `LocalRegisterCopy`).

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
```rust
    // The following fields are not actually registers
    // (they may be placed anywhere in memory),
    // but the register interface provides the volatile
    // read/writes and bitfields that we need.
    pub packet_size: ReadWrite<u32, PacketSize::Register>,
    pub control_status: ReadWrite<u32, ControlStatus::Register>,
```

This is interesting, and kind of a neat use of the register interface. If I understand how those are used correctly, there are fields on the wire in the USB protocol that require some bit manipulation to craft. So the USB interface creates a "register" in memory, uses the nice bit twiddling interfaces to set up stuff, then copies the bytes into the memory buffer to be sent on the USB channel.

I actually think this is quite useful, and a somewhat compelling case for keeping `new` around, although perhaps renamed as `new_regsiter_like_memory` (or perhaps something less wordy)

**Comment by bradjc** [comment]
Well we have `LocalRegisterCopy` which is pretty well suited for this case, however, that was only design to be read. So we could add the write functions, or create a new register in memory type.

**Comment by ppannuto** [comment]
I am curious why that comment suggested that `volatile` was relevant for stuff held in memory (oh! maybe DMA also has access to those buffers, so when reading a new USB message placed in arbitrary memory, the register interface is useful for picking it apart, but is volatile memory due to DMA writes).

But yes, I agree that an explicit `RegisterLikeMemory` type is a good path forward, dropping `new` from the physical register type

**Comment by alevy** [comment]
@ppannuto if memory servers, that is exactly the reason. The USB hardware includes a bunch of registers which pointers (configured by software) to memory buffers that are manipulated similar to regular registers, including by the hardware. Kind of like a page table.

**Comment by ppannuto** [comment]
@alistair23 this still needs some work to update the USB driver's use, as discussed above. Hopefully should be a reasonably self-contained change if it's something you're interested in working on though!

**Comment by alistair23** [comment]
I can have a look next week. I don't have a way to test it though.

**Comment by bradjc** [comment]
Ok I added a new type to support the SAM4L USB case. How does that look?

**Comment by alevy** [comment]
@bradjc this is not passing travis for some reason

**Pull request merged**
