### PR TITLE
kernel: add public process_map_or_external fn

### PR DESCRIPTION
**Pull request by jettr**
### Pull Request Overview

Add a version of process_map_or that is publicly available with the appropriate ProcessManagementCapability.

We need this to support carrying code out of tree that needs to loop through processes

This does not need to make it by Tock OS 2.0

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]
bors d+

Tagging blocked (which will stop bors from merging), but should be good to go after 2.0

**Comment by jettr** [comment]
> bors d+
> 
> Tagging blocked (which will stop bors from merging), but should be good to go after 2.0

I got a little excited and tried too soon. I see what you mean now about the `blocking` label. Just testing out the system ;)

I'll merge after 2.0 :)

**Pull request merged**
