### PR TITLE
boards/Makefile: remove relative libtock-c path assumptions

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

Removes any assumptions about application TBFs or `libtock-c` trees using relative paths outside of the Tock repository. In the cases where Tockloader is not supported (yet), the TBF file to include should be passed using the `APP` variable instead, as done in `clue_nrf52840`.

### Testing Strategy

This pull request was tested by running make targets.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
Looks good, look forward to the remaining change

**Comment by lschuermann** [comment]
To give an update why this has been pending for so long: I'm not really confident to make these changes to the `imxrt1050-evkb` board without testing it first (for instance, will the tools still work if there's an `elf` extension instead of `axf`, etc.?). Unfortunately NXP's user experience for downloading their MCUXpresso software is entirely broken, and after what have been at least 15 attempts I've managed to start a download with 150kbit/s of a 800MB file. I'll try to have it done by tomorrow.

**Comment by lschuermann** [comment]
I couldn't test the actual flashing process on the `imxrt1050-evkb` unfortunately as I have a slightly different chip than the one supported here, but I did manage to get NXP's flashing tool to complain about the chip and not the input file, so I'm positive these changes should work. Updated the documentation accordingly.

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
