### PR TITLE
[WIP] Add in-kernel AES abstraction layer

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview
This PR adds an entirely HW-independent AES kernel abstraction layer. It represents a key component for building a unified AES kernel infrastructure, ranging from software implementations, over HW drivers, up to userspace drivers and kernel security components.

This was also discussed [on the Tock ML](https://groups.google.com/forum/#!topic/tock-dev/cRh7XH6znPc).

This is WIP and a rough sketch of what the final version could look like. I think the ideas behind it are in a state where a technical discussion would be appropriate. Hence this PR.

As a design goal this isn't supposed to do any dynamic crypto routing or implement a crypto registry of sorts. All of this should be inlineable and not require any memory allocation at runtime, except where absolutely required (for instance, the software mode implementations).

### Explanation (from the ML posting)
The basic idea is to have a flexible layer, which can accomodate any
combination of supported AES key sizes and modes by the hardware, and
even support software implementations where the hardware does not
support the desired mode / key size.

This works by creating a strongly typed interface for AES keys, to be
used by the rest of the infrastructure.
Following that, two types of traits are used:

  - "key traits" /^AES[0-9]*Engine$/
    These traits provide methods for expanding the AES key, which is
    required prior to any encryption or decryption operation. If a
    hardware only supports a certain key length, the implementer may
    choose to only implement for instance the "AES128Engine" trait. For
    supporting all key sizes, it is sufficient to implement the
    "AESEngine" trait.

  - "block cipher mode traits" /^AES[A-Z]*Mode$/
    If a hardware directly supports a given AES mode, the proper trait
    can be directly implemented, providing methods for setting all
    required parameters, such as initialisation vectors etc.  However,
    implementing the basic building block called "AESBlockEngine", all
    other mode traits are implemented automatically.

For any given AES hardware or software implementation, it should be
sufficient to provide any combination of both key- and mode traits. This
implicitly describes the implementations' capabilities and can be used
to derive other possible modes.

This architecture appears to be fitting, as key expansion is AFAIK
generally independent of the chosen block cipher mode. Also, every mode
has different parameters and constraints, hence an individual trait per
mode. The abstraction should not incur a significant runtime cost,
although this is to be investigated.

Future improvements include terminology (trait names), more traits for
complex AES modes (currently only ECB is supported), a userspace driver
for each mode, support of existing HW implementations, and other changes
(i.e. make set_client() take an Option<>, etc.). 

### Testing Strategy

This pull request will be tested by building infrastructure around it. I have a software AES implementation ready, which will be released as another draft PR shortly. I plan to build userspace drivers using this layer in the upcoming days. This should not be merged before many pitfalls / weaknesses have been discovered through implementations and fixed accordingly.

### TODO or Help Wanted
- [ ] Should something like this be included as a capsule or in the kernel crate? It doesn't really count as a driver or helper, but rather an interface specification. However, it's probably a good idea to keep the kernel crate small, also this doesn't and should never be able to include any unsafe code.
- [ ] Add further AES mode abstractions and respective software "polyfills" (i.e. `SoftAESCTR` etc.)
- [ ] Publish the software AES implementation exposing interfaces as defined by this layer.
- [ ] Implement userspace drivers using this layer.
- [ ] Abstract real HW (Atmel / Nordic AES) using this layer, exposing those to userspace.
- [ ] Implement a userspace test program for determining supported AES modes on a kernel and testing the implementations properly.
- [ ] Think about security impact.
- [ ] Improve documentation.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by lschuermann** [comment]
I've added CBC support and revamped the software "polyfill" (what's a better word here?) ECB buffer handling as well. Thanks to some excellent advise from @jmichelp we are now also reporting whether the implementation is entirely HW (if the mode is done directly in HW), if we're HW accelerated (primitives done in HW) or entirely built on software crypto.

**Comment by bradjc** [comment]
In general having interfaces in /capsules or /chips or /boards etc. is fine, particularly when the interface is new or we are otherwise unsure of it, and we want to keep it local to where it is used. However, I think we want to avoid having an interface in two locations, in this case the AES HIL and this proposed interface in capsules.

I'm not the best person to comment here, but my sense is the interface here should be merged with the AES HIL and specified in kernel/hil. The software implementation should be left in the capsules crate.

**Comment by lschuermann** [comment]
> the interface here should be merged with the AES HIL and specified in kernel/hil. The software implementation should be left in the capsules crate.

That is my impression too. Ultimately, I'd like to get rid of the old AES hil, as it is very HW specific and in my humble opinion does not make good use of the Rust type system and is quite confusing. It's fine as a hardware abstraction, but not fit to build an in-kernel crypto infrastructure.

I can imagine two ways of transitioning:
- Changing the chip-crates to directly offer interfaces as described in this PR.
- Create a bridge struct for using those old interfaces with the new layer.

The next tasks would be to create a userspace driver for AES-CBC and to port some AES peripheral to offer this API, next to #1721. That should sufficiently validate my ideas. I'm still open to suggestions, a lot can be improved!

**Comment by vsukhoml** [comment]
There are several things to consider - HW support for AES can be as simple as just ECB (electronic code book mode) and can include other modes like CTR, CBC, etc. There are modes of operation which may require software assist. Some AES implementation provide hooks to accelerate GCM mode (compute GHASH). So there may be multiple layers of AES depending on capabilities and some applications may need all of them (like TPM), some may need just one or none at all.

From other side, various certifications like FIPS 140-2, Common Criteria CSP, etc require recertification if cryptographic implementation changes. Recompiling TockOS (especially with LTO) will trigger this. It can be beneficial if sensitive code can be compiled separately (probably as position independent code or placed at fixed location in linker script), and Tock core will just provide a unified API to that code. 

I'm not sure what is the best design to address both requirements, but tend to think that code in Tock core shouldn't be more than just a wrapper to a lower level code built as a library exposing cryptographic primitives specific for particular board despite changes to build system.

**Comment by lschuermann** [comment]
@vsukhoml I understand your concerns. AES HW has a large variability, especially regarding the supported modes and key sizes. That doesn't make providing a good abstraction an easy task. However, I've put a lot of thought into this architecture and I think it could cover a reasonable surface of what's out there and of what makes sense to have an abstraction over. We can _never_ cover everything (even with the current AES HIL), for exotic algorithms nothing stops you from rolling out your own interface, private to your project and your specific needs.

> From other side, various certifications like FIPS 140-2, Common Criteria CSP, etc require recertification if cryptographic implementation changes.

I personally am not necessarily too worried about certifications. However, in it's basic variant this is just a collection of traits, which one can implement based on the capabilities of the hardware. Hence I don't see why you couldn't write code that is statically linked with the rest of the binary and exposes interfaces according to those traits? Again, here I'd guess that we'd be unable to provide something covering all possible scenarios. If you are a company worried about certifying crypto code under Tock, check if the interface fits - but it's probably best to have an extremely stable out-of-tree interface anyways to avoid having to re-certify. I'm guessing a two-layer API approach could also be possible here, though I don't know the specific requirements of the aforementioned certifications. Besides that there are probably other things to be worried about: even with a simple HIL, the Rust traits will change over time with updated compilers, so you'd have to resort to C with ABI stability anyways - not something we should require Tock developers to use in the kernel. It is an important issue, I just don't think we can possibly work around that in an upstreamed, safe-Rust solution.

> I'm not sure what is the best design to address both requirements, but tend to think that code in Tock core shouldn't be more than just a wrapper to a lower level code built as a library exposing cryptographic primitives specific for particular board despite changes to build system.

An important goal of this is that it's all opt in. The wrapper structs _can_ be used to wrap an ECB-capable HW and expose a CBC-trait. However, you're free to implement the CBC trait directly in whatever code you have. Cryptography in software can be extremely problematic (even if the primitives are done in HW), so those wrappers are provided to fill gaps and increase portability - whether you'd like to trust them is a different story. I think this distinction will be more clear once I separate the wrappers into their own capsule.

Striking a balance between a secure, portable, extensive and safe interface is a difficult problem. In this case, we really can't have our cake and eat it too.

**Comment by bradjc** [comment]
Can this be re-worked as a change to the existing HIL?

**Comment by lschuermann** [comment]
> Can this be re-worked as a change to the existing HIL?

That's a question I've been thinking about while developing this. The current HIL uses a vastly different approach, namely having one data-path for a given AES HW or SW implementation. Basically you're having a common trait for basic operation, and extend this with other traits for feeding in mode-specific data (and setting the operation mode). While it has some advantages, distributing mode options over different traits and not coupling the encryption and decryption methods together with the other mode specific methods increases the need for dynamic checks during runtime.

Ultimately, this has developed in a drastically different direction. If we'd choose to go in this direction, I think it would be easier to replace the current HIL. I'd of course migrate any existing code to the new HIL.

**Comment by bradjc** [comment]
From a practical standpoint, I don't know where the momentum is going to come from to replace the AES HIL, particularly now that the digest HIL follows a similar format. Is that something you want to take on?

**Comment by lschuermann** [comment]
If I'm not mistaken there have been some comments by @phil-levis regarding the single data-path approach vs. what I'm trying to do, he planned on wrting an ML post. I can try to restart the respective discussion on tock-dev around this.

I think this PR is still applicable, I'm vouching in favor of looking into this. Unfortunately - Tock being a project I'm doing in my free time - I didn't get around to implementing more infrastructure using these traits and comparing that to the implementations with the current HIL. Is it okay if I take some more time?

**Comment by vsukhoml** [comment]
I've been thinking about good solution for variety of hardware implementations and lack of thereof. The  desired property of solution is to expose stable API for applications so no changes would be needed if used on another board. This can be achieved say by providing a high-level wrapper capsule which would be board-specific, but expose API with standard syscalls. Also, provide software implementations of various modes CTR/CBC/OFB/etc working on top of basic ECB mode. Everything with internally standard APIs, so boards can reuse software modes not supported in hardware or expose hardware-backed modes with same API. There is dependency on syscall ABI's ability to efficiently pass multiple in-memory parameters.

There can be 2 execution modes - livestream and 'one shot' - first one split into start/{process}/finalize  and latter - do everything in single call. There should be a notion of 'context' which would either indicate hardware nature of processing, may be resource mutex reference, or store software state.  This context should be probably on kernel side for security if dealing with software keys not available to applications.

This also leads to 'key management' API which should exist and fulfill needs of HMAC, AES at start, and potentially public key crypto in future.

**Comment by lschuermann** [comment]
@vsukhoml From what I can tell, your mission to build a kernel crypto infrastructure is very similar to what I'm trying to accomplish here.

> I've been thinking about good solution for variety of hardware implementations and lack of thereof.

I agree to what you've said. I think that this - in it's current form - captures this idea reasonably well. The HIL provides specific interfaces for each operation mode of symmetric ciphers; in contrast to the current approach, which is one trait for common methods across all ciphers, and implementing another to specify mode-specific behavior (say _yeah, I can do CTR, give me IV and counter using the CTR-trait and provide data using the AES-trait_). Nothing in what I propose actually mandates any specific implementation type or strategy. This simply defines the HIL. It is special in that it's _designed_ to be layered easily. Basically it's up to you whether you'll want to back a CTR implementation by specific hardware, ECB hardware, or all software. The key is to make it possible to do every **reasonable** combination. A board will choose the implementation appropriately, up to the security requirements.

I fear you're trying to think through the entire stack. Understanding how userspace apps and capsules will interact with this API is important for sure, but this interface is designed with kernel-usage and implementation for (software/hardware) devices in mind first. We can look at capsules, syscalls, etc. in a second step, improving this layer.

> The desired property of solution is to expose stable API for applications so no changes would be needed if used on another board. This can be achieved say by providing a high-level wrapper capsule which would be board-specific, but expose API with standard syscalls.

This PR proposes a set of interfaces which are designed to be stable and usable even in the kernel. By creating a good in-kernel symmetric cryptography API, the issue of supporting multiple boards is solved without writing multiple capsules, but simply providing a single cross-board capsule using this API. This is a common paradigm with Tock: `[Userspace] <stable syscall ABI> capsule <stable HIL> (possibly other layers) <stable HIL> hardware implementation`.

@vsukhoml If this proposal does not suit your needs, I would kindly ask to you to point out specifically what some of the issues are. I will gladly add a usage example of a layered (meaning, for instance CTR on top of a HW ECB implementation) examples if that helps.

> There can be 2 execution modes - livestream and 'one shot'

I am not entirely sure how to capture that in a HIL. Such a different mode of operation would mean a different usage pattern of the HIL, and therefore is best encapsulated in a second separate interface.
Those two different modes of operation are nonetheless relevant regarding the syscall interface, as well as the actual HW implementation, both of which are not subject of this PR.

**Comment by bradjc** [comment]
Is there any interest in still including this? Or did the AES HIL discussion address the issues?

**Comment by lschuermann** [comment]
This still has a lot of interesting ideas for sure, but it's a different approach compared to the current AES HIL, which also works.
As I'm currently not actively developing the project which this was part of anymore, I'll close the PR. If some of the limitations of the current HIL become apparent in the future again, this will be a good reference to refer to. :)

**Pull request closed without merging**
