### PR TITLE
RFC: Moving some flags from Makefile to build.rs

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request is a companion to #2962 and looks at what moving more flags from the Makefile to a common build.rs file could look at.

This is an initial implementation to get feedback. The [cargo build.rs instructions](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) are somewhat limited, so there isn't too much we can move (at least right now). 

I'm targeting build.rs because it is not a hidden file, and because we can use a shared common_build.rs.

### Testing Strategy

todo

### TODO or Help Wanted

Since we can't move too much out of Makefile right now, should we bother? Or is shrinking our custom Makefile and using standard rust infrastructure still a net improvement?

If we find a version we like it needs to be propagated to all boards.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Comment by ppannuto** [comment]
Is there any sense of priority in the Rust community of getting more options added to the `build.rs + cargo:` interface?

It feels like this move doesn't really buy us anything at this stage, and it's a minor regression to have half the options set in one place, and half in another. We could add 'tracking comments' to the flags in the Makefile perhaps, something like each line being `-C link-arg=-Tlayout.ld \   # println!("cargo:rustc-link-arg=-Tlayout.ld");` so that once every config has an equivalent, we can switch over easily?

Conceptually, I like the idea of eventually getting to a build that is rust-native, but driven by make as a glorified shell scripts that ease use.

**Comment by bradjc** [comment]
> Is there any sense of priority in the Rust community of getting more options added to the `build.rs + cargo:` interface?

I don't know. I'm guessing that since they are OK with their build configurations sequestered in hidden files they are in no hurry to support more general build.rs files. But you never know.

Also, does it change anything if you consider #2962 too? That one does have the "this should move" flag in the makefile.

**Comment by hudson-ayers** [comment]
I think there are some other small upsides to this change with regards to the amount of rust code that gets rebuilt when manually changing linker args, but I think those upsides are not worth having half the flags set in one place and half in another.

**Comment by bradjc** [comment]
Same issue as #2962.

**Pull request closed without merging**
