### PR TITLE
boards/opentitan: Remove support for Nexys Video

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

The Nexys video is no longer supported (see
https://github.com/lowRISC/opentitan/issues/7814) so let's remove
support for it from Tock.

### Testing Strategy

CI

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Huh, it is too bad that OT has to deprecate this before support for another lower-cost FPGA is added, but it makes sense we should drop this support so we can continue to update as OT does.

**Comment by bradjc** [comment]
I support this, but would like to see it moved via PR to tock-archive.

**Review by lschuermann — APPROVED** [review]

**Review by thulithwilfred — APPROVED** [review]
Gone, but not forgotten :^)

**Comment by alistair23** [comment]
Ping!

**Comment by lschuermann** [comment]
Going to merge this and open a PR to tock-archive.

bors r+

**Comment by hudson-ayers** [comment]
Allows us to merge https://github.com/tock/tock/pull/3025

**Comment by hudson-ayers** [comment]
I think we had a race on this @lschuermann , just opened a tock-archive PR: https://github.com/tock/tock-archive/pull/3

**Comment by alistair23** [comment]
Aw, whoops. I missed Brad's comment. Thanks for doing that

**Pull request merged**
