### PR TITLE
chips/qemu_rv32_virt_chip: implement basic UART RX and add process console to board

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

Implements basic UART RX support (without abort) and adds the process console component to the board. I didn't want to invest time in supporting receive-abort, as this needs to be migrated to the new UART HIL anyways (#3046).

### Testing Strategy

This pull request was tested by using the process console.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by twilfredo — DISMISSED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Comment by lschuermann** [comment]
Rebased accordingly, merging if checks succeed.

bors r+

**Review by hudson-ayers — APPROVED** [review]
bors r+

**Review by alistair23 — APPROVED** [review]

**Comment by lschuermann** [comment]
@hudson-ayers Could you give another approval perhaps? This time the Netlify CI didn't glitch out, so maybe fourth time's the charm? :laughing:

**Review by hudson-ayers — APPROVED** [review]
bors r+

**Pull request merged**
