### PR TITLE
Add cargo test for capsules on ci-travis.

### PR DESCRIPTION
**Pull request by gendx**
### Pull Request Overview

This pull request adds `cargo test` for the `capsules` crate to the Makefile.

I added a simple test in the virtual alarm capsule, but in general I think that capsules should be of great interest for functional unit tests, due to the non-trivial logic and the abstraction provided by HILs. In particular, one can write mock implementations of HILs to simulate various behaviors and test that the capsules react as expected.

### Testing Strategy

This pull request was tested by running `make ci-travis` and checking that unit tests indeed appear in the log.

### TODO or Help Wanted

- This pull request still needs fixing a bunch of doc tests in capsules.
- I hope that we can agree on the usefulness of such tests now that a lot of discussion happened on https://github.com/tock/tock/pull/1393. 

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by gendx** [comment]
I gave a try to fix the plethora of existing doc tests in capsules.

But it turns out that these tests are **way out-of-date** for the most part. Sources of errors include:
- API changes. For example `kernel::Grant::create()` doesn't exist anymore.
- Changes in the signatures of functions or types. Parameters have been removed, have changed types, etc.
- Renamed types/functions.
- Invalid syntax, such as missing parentheses.

Another annoying part is that these examples rely on dependencies such as `sam4l` (or `nrf5x`) to show how to instantiate the HIL, but `sam4l` isn't a dependency of `capsules`, so it's hard to make the doc tests build.

Ultimately, it's possible to make Cargo ignore these doc tests, e.g. with the `ignore` flag (https://github.com/rust-lang/rust/pull/49532). But not testing examples means that they will quickly get out-of-date again, and then aren't really useful.

All in all, I question the value of the existing "how to instantiate capsule *foo*" examples.
- The examples **greatly overlap with the components** (https://github.com/tock/tock/pull/1338), except that the actual components are up-to-date.
- The examples are low-level, but developers of boards should use the higher-level components instead.
- The examples don't seem to bring much value in terms of logic, besides "how to use `static_init`" and to be redundant with the signature of the capsule's constructor. If something non-trivial happens, one should check the component's code instead (or a board that uses them if the capsule wasn't migrated to a component yet).
- Given how outdated the examples are, nobody seems to rely on them. So removing them would make the code base easier to maintain.

Therefore, I **propose to remove the code examples showing how to instantiate each capsule**. Documentation about what each capsule does (i.e. the explanation in English) should be more interesting. And unit tests about the actual logic should be more useful.

**Comment by torfmaster** [comment]
I did the same in #1499. As this it is unclear whether the PR will be merged you can cherry pick more tests if you like.

**Comment by bradjc** [comment]
Components are a huge help for instantiating capsules, and the documentation in the capsule itself predates having components. I agree that if there is a component available for a capsule then we do not need the `static_init` example and can instead refer to just the component. However, given how complicated Rust syntax is, having even a broken example of how to setup a capsule is better than just expecting someone to read and understand the `new()` function. So I think leaving the examples for capsules that do not have components is useful until components are made.

**Comment by bradjc** [comment]
I do think we should merge these changes since gendx put the effort in to update them.

**Comment by ppannuto** [comment]
I agree with basically all of what @bradjc, however, in the immediate-term we either need to fix the rest of these or pull out the `Makefile` changes and not actually run the tests before we can merge this :/.

I think a good first step would be to delete the examples for everything that does have a component, then we can see what the scope of the remaining work actually is?

**Comment by alevy** [comment]
A couple points:

1. I agree with @ppannuto and @bradjc that we basically shouldn't regress in documentation, and that these examples actually are useful even if not totally up to date (they are typically not far, and I've personally used them).

2. I agree that removing that marking which capsules _do_ have components associated with them, and them writing new examples with components makes sense.

3. Unfortunately, Rust docs don't seem to give us the ability to make sure that a doc-test type-checks without actually running it and, as a result, I don't believe it's possible to use dummy variables for lower-level components as opposed to specific chip implementations...

4. > The examples are low-level, but developers of boards should use the higher-level components instead.

    It depends who you think the developers are. Board developers should probably use components if they exist, but what about component developers? In general, documentation for a module should document using _the module_ itself, rather than some higher level module that happens to use it.

4. > The examples don't seem to bring much value in terms of logic, besides "how to use static_init" and to be redundant with the signature of the capsule's constructor. If something non-trivial happens, one should check the component's code instead (or a board that uses them if the capsule wasn't migrated to a component yet).

    I disagree with this. A constructor is _not_ sufficient for initializing most capsules, as capsules typically have circular dependencies that need to be instantiated separately from their constructor. Sometimes, as is the case with, say the `virtual_` capsules, it may not be obvious how to do so without an example, or some other explicit documentation.

**Comment by ppannuto** [comment]
Okay, I rebased this on latest master; looks like there is a manageable number of these that need to update:
> test result: FAILED. 3 passed; 50 failed; 0 ignored; 0 measured; 0 filtered out
I probably won't do these today but will start trickle-fixing them in spare time

**Comment by hudson-ayers** [comment]
I took a look at these, and it still seems like a fundamental issue that we cannot use chip-specific code in capsules, but chip-specific code is required for almost all initialization examples, so most of these cannot be fixed, and at best can be ignored. @ppannuto was your plan to just check that the initialization code is correct, update it if not, and then add an ignore flag to each?

**Comment by ppannuto** [comment]
Yeah.., I do look at this and then circle away from time to time. I think the dream in the back of my mind was to use this as a component-ification checklist. That is, to start with (2) as Amit suggested, then maybe start migrating things to components as-possible.

**Comment by hudson-ayers** [comment]
One potential idea before we have components for everything is to run `cargo test --lib` for the capsules crate, which runs all tests except doc tests. That would make sure that at least the unit tests pass (though I think we only have those for alarm right now).

**Comment by gendx** [comment]
> One potential idea before we have components for everything is to run `cargo test --lib` for the capsules crate, which runs all tests except doc tests. That would make sure that at least the unit tests pass (though I think we only have those for alarm right now).

This would already be an improvement! And allow writing more unit tests.

**Comment by bradjc** [comment]
Can we merge the doc changes and move the remainder of this to an issue? (or is there already an issue?) It would be good to get the comment fixes in before they become too out of date.

**Comment by bradjc** [comment]
Moved to #1927.

**Pull request closed without merging**
