### PR TITLE
boards: reduce stack frame size of main()

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

Re: #2425

Updates the main.rs files for boards that have a large stack frame for main.

### Testing Strategy

travis

### TODO or Help Wanted

Please contribute fixes for more boards that need it. I think we can merge this when all boards have reasonable stack frame sizes for `main()`.

To do:

- [x] nrf52dk
- [x] nrf52840_dongle
- [x] nrf52840dk
- [x] nano33ble
- [x] teensy40
- [x] weact-f401ccu6
- [x] nucleo_f429zi
- [x] microbit_v2
- [x] imxrt1050-evkb
- [x] acd52832
- [x] nucleo_f446re
- [x] clue_nrf52840

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
Current state:

```
$ make allstack
earlgrey-nexysvideo
----------------------
reset_handler stack frame:

5 largest stack frames:
          592     _ZN6kernel5sched6Kernel11kernel_loop17h85c04e8208f83212E
          560     _ZN6kernel7process14load_processes17h802cad3d142bdf40E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17habcfa4038d4e3ce2E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h4d61618cb65116c9E
          288     _ZN7lowrisc6usbdev3Usb11free_buffer17hd64f035f484241d6E

nrf52dk
----------------------
reset_handler stack frame:

5 largest stack frames:
         1400     main
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17hbf6b09961b6f4ae0E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h42573d318638eacfE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h4772febcba750fd0E

nrf52840_dongle
----------------------
reset_handler stack frame:

5 largest stack frames:
         2048     main
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hd9d71de97551b600E
          792     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h9756fd5600f4faeeE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17h9b1ff71070dd05f7E
          616     _ZN6kernel7process14load_processes17ha81cd5dc59d5817fE

nrf52840dk
----------------------
reset_handler stack frame:

5 largest stack frames:
         2064     main
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h7837e1852f7e6747E
          784     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17ha20b654575b3b94aE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17hb7e4f496f3cb25f9E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E

stm32f3discovery
----------------------
reset_handler stack frame:

5 largest stack frames:
         2416     _ZN16stm32f3discovery15get_peripherals17h76e1df034eb1630fE
         2120     rust_begin_unwind
          616     _ZN6kernel7process14load_processes17h6c5f00aa5426a4f4E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h21c42f1bb6cff9b3E

redboard_artemis_nano
----------------------
reset_handler stack frame:

5 largest stack frames:
          616     _ZN6kernel7process14load_processes17h319ae32007289075E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hc3537f44838fc5e6E
          296     main
          264     _ZN86_$LT$cortexm..syscall..SysCall$u20$as$u20$kernel..syscall..UserspaceKernelBoundary$GT$13print_context17h1a81e51819915de7E

nano33ble
----------------------
reset_handler stack frame:

5 largest stack frames:
         2040     main
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h562f5518313f77d0E
          784     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h6696d9e26443dbb5E
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17hd5588df3c8758489E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E

info: downloading component 'rust-std' for 'riscv32imac-unknown-none-elf'
info: installing component 'rust-std' for 'riscv32imac-unknown-none-elf'
info: using up to 500.0 MiB of RAM to unpack components
hifive1
----------------------
reset_handler stack frame:

5 largest stack frames:
          496     _ZN6kernel7process14load_processes17ha84cf9baeb6ba1deE
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17h5faec61885575280E
          288     _ZN6kernel5debug15panic_cpu_state17hacbf74fd7ae84310E
          272     _ZN6kernel5sched6Kernel11kernel_loop17hec38ca52c2d9a7e9E
          256     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hffca459a82b516fcE

teensy40
----------------------
reset_handler stack frame:

5 largest stack frames:
         2384     main
         1016     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hba51bef5b5fbdedaE
          864     _ZN6kernel7process14load_processes17h4b3a043931cc247bE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          488     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h46d8365963ef9b65E

info: downloading component 'rust-std' for 'thumbv7em-none-eabihf'
info: installing component 'rust-std' for 'thumbv7em-none-eabihf'
info: using up to 500.0 MiB of RAM to unpack components
weact-f401ccu6
----------------------
reset_handler stack frame:

5 largest stack frames:
         3200     main
         2784     rust_begin_unwind
          632     _ZN6kernel7process14load_processes17hfaa3aad0d42bf5baE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17h701fe4c59cce0efcE
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h77ea81f862b17295E

stm32f412gdiscovery
----------------------
reset_handler stack frame:

5 largest stack frames:
         3200     _ZN19stm32f412gdiscovery15get_peripherals17h76397328bb61e6eeE
         2784     rust_begin_unwind
          632     _ZN6kernel7process14load_processes17h474a4d3a0fa635b2E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17he7db392babdcfe2dE

hail
----------------------
reset_handler stack frame:

5 largest stack frames:
         1064     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hb5a3216c622528a3E
         1016     _ZN72_$LT$kernel..ipc..IPCData$LT$_$GT$$u20$as$u20$core..default..Default$GT$7default17h0111ce36fa01b1aaE
          616     _ZN6kernel7process14load_processes17he2276ec1368dc6e2E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h734bf6d34776bfa4E

arty_e21
----------------------
reset_handler stack frame:

5 largest stack frames:
          480     _ZN6kernel7process14load_processes17h97be39c2a47a4231E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17hd57140269b8ff373E
          288     _ZN6kernel5debug15panic_cpu_state17h07a7245856bf3386E
          272     _ZN6kernel5sched6Kernel11kernel_loop17h7e19f5df7eb805bbE
          240     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$16print_memory_map17hbb0df8982ebb28bdE

nucleo_f429zi
----------------------
reset_handler stack frame:

5 largest stack frames:
         3208     main
         2784     rust_begin_unwind
          616     _ZN6kernel7process14load_processes17h119e538f069ae859E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hc0761acaee297ec3E

microbit_v2
----------------------
reset_handler stack frame:

5 largest stack frames:
         1776     main
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17hc18cff78f42d2f2dE
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hb6f2e8c6d2b2887bE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hae61da99ed6c3574E

imxrt1050-evkb
----------------------
reset_handler stack frame:

5 largest stack frames:
         2384     main
         1016     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17he6cb50d1e03759d4E
          832     _ZN6kernel7process14load_processes17hb6d4daf39c2cd832E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          480     _ZN79_$LT$cortexm..mpu..CortexMConfig$LT$_$GT$$u20$as$u20$core..default..Default$GT$7default17he11732d64b21a6b6E

acd52832
----------------------
reset_handler stack frame:

5 largest stack frames:
         1400     main
          608     _ZN6kernel7process14load_processes17h4e3abc424751c0c4E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hef404037b35b635eE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h54cbae7ffa30b798E
          272     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17ha9a81e4de45b1d76E

imix
----------------------
reset_handler stack frame:

5 largest stack frames:
          616     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h4442597958d62218E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17h73fbed6e3b9582e4E
          568     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17h9ee7a40920b611e7E
          536     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17haa4f9cfedb6df7c6E

nucleo_f446re
----------------------
reset_handler stack frame:

5 largest stack frames:
         3192     main
         2784     rust_begin_unwind
          624     _ZN6kernel7process14load_processes17h9bced38b7d22546fE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h7b16317de605bb3fE

litex_arty
----------------------
reset_handler stack frame:

5 largest stack frames:
          560     _ZN6kernel7process14load_processes17ha17b6a3c33765e34E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17h758234199a7207a5E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h31bc9feaa3370525E
          288     _ZN6kernel5sched6Kernel11kernel_loop17habc387240d65dec4E
          288     _ZN6kernel5debug15panic_cpu_state17h5f488ccdd45dca36E

info: downloading component 'rust-std' for 'riscv32i-unknown-none-elf'
info: installing component 'rust-std' for 'riscv32i-unknown-none-elf'
info: using up to 500.0 MiB of RAM to unpack components
litex_sim
----------------------
reset_handler stack frame:

5 largest stack frames:
          560     _ZN6kernel7process14load_processes17h879c3514fa7cb2e7E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17he0c92594b0489dcaE
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hf299a644a0e112aaE
          288     _ZN6kernel5sched6Kernel11kernel_loop17hacb6db99f3d8a0feE
          288     _ZN6kernel5debug15panic_cpu_state17hd837d658473d36ddE

swervolf
----------------------
reset_handler stack frame:

5 largest stack frames:
          464     _ZN6kernel7process14load_processes17h5258ffb0dca12b17E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17hbb5c8c294b078effE
          288     _ZN6kernel5debug15panic_cpu_state17he8c24492ac1a427fE
          240     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$16print_memory_map17h2fa2e294000bfc88E
          240     _ZN6kernel5sched6Kernel11kernel_loop17h0d715ff986c30c50E

clue_nrf52840
----------------------
reset_handler stack frame:

5 largest stack frames:
         2056     main
         1128     _ZN94_$LT$components..cdc..CdcAcmComponent$LT$U$C$A$GT$$u20$as$u20$kernel..component..Component$GT$8finalize17h964230a41c8c7401E
          792     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h2d536cd5242d665cE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17ha0bb5c6b9dce8feeE
          616     _ZN6kernel7process14load_processes17hab545c6c65b58d43E

msp-exp432p401r
----------------------
reset_handler stack frame:

5 largest stack frames:
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17h33965391790ace80E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h638dfccb8d826a07E
          440     main
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h360a839dcb81adb4E
```

**Comment by hudson-ayers** [comment]
This approach looks good to me, but should we just use it everywhere given that the compiler optimization is not guaranteed to always apply on boards where don't use this?

**Comment by bradjc** [comment]
Updated version:

```
earlgrey-nexysvideo
----------------------
reset_handler stack frame:

5 largest stack frames:
          592     _ZN6kernel5sched6Kernel11kernel_loop17h85c04e8208f83212E
          560     _ZN6kernel7process14load_processes17h802cad3d142bdf40E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17habcfa4038d4e3ce2E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h4d61618cb65116c9E
          288     _ZN7lowrisc6usbdev3Usb11free_buffer17hd64f035f484241d6E

nrf52dk
----------------------
reset_handler stack frame:

5 largest stack frames:
         1344     _ZN7nrf52dk15get_peripherals17h9ccb2d69ce01aa4cE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17hbf6b09961b6f4ae0E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h42573d318638eacfE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h4772febcba750fd0E

nrf52840_dongle
----------------------
reset_handler stack frame:

5 largest stack frames:
         2008     _ZN15nrf52840_dongle15get_peripherals17h3b70478a14a948afE
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hd9d71de97551b600E
          792     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h9756fd5600f4faeeE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17h9b1ff71070dd05f7E
          616     _ZN6kernel7process14load_processes17ha81cd5dc59d5817fE

nrf52840dk
----------------------
reset_handler stack frame:

5 largest stack frames:
         2008     _ZN10nrf52840dk15get_peripherals17h389ed5e0962e655cE
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h7837e1852f7e6747E
          784     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17ha20b654575b3b94aE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17hb7e4f496f3cb25f9E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E

stm32f3discovery
----------------------
reset_handler stack frame:

5 largest stack frames:
         2416     _ZN16stm32f3discovery15get_peripherals17h76e1df034eb1630fE
         2120     rust_begin_unwind
          616     _ZN6kernel7process14load_processes17h6c5f00aa5426a4f4E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h21c42f1bb6cff9b3E

redboard_artemis_nano
----------------------
reset_handler stack frame:

5 largest stack frames:
          616     _ZN6kernel7process14load_processes17h319ae32007289075E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hc3537f44838fc5e6E
          296     main
          264     _ZN86_$LT$cortexm..syscall..SysCall$u20$as$u20$kernel..syscall..UserspaceKernelBoundary$GT$13print_context17h1a81e51819915de7E

nano33ble
----------------------
reset_handler stack frame:

5 largest stack frames:
         2008     _ZN9nano33ble15get_peripherals17h8ff67e61b773b3aaE
          872     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h562f5518313f77d0E
          784     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h6696d9e26443dbb5E
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17hd5588df3c8758489E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E

hifive1
----------------------
reset_handler stack frame:

5 largest stack frames:
          496     _ZN6kernel7process14load_processes17ha84cf9baeb6ba1deE
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17h5faec61885575280E
          288     _ZN6kernel5debug15panic_cpu_state17hacbf74fd7ae84310E
          272     _ZN6kernel5sched6Kernel11kernel_loop17hec38ca52c2d9a7e9E
          256     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hffca459a82b516fcE

teensy40
----------------------
reset_handler stack frame:

5 largest stack frames:
         2336     _ZN8teensy4015get_peripherals17hd4f57c49c04de49eE
         1016     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hba51bef5b5fbdedaE
          864     _ZN6kernel7process14load_processes17h4b3a043931cc247bE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          488     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h46d8365963ef9b65E

weact-f401ccu6
----------------------
reset_handler stack frame:

5 largest stack frames:
         3184     _ZN14weact_f401ccu615get_peripherals17h3171dcd78e8dcbc3E
         2784     rust_begin_unwind
          632     _ZN6kernel7process14load_processes17hfaa3aad0d42bf5baE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17h701fe4c59cce0efcE
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h77ea81f862b17295E

stm32f412gdiscovery
----------------------
reset_handler stack frame:

5 largest stack frames:
         3200     _ZN19stm32f412gdiscovery15get_peripherals17h76397328bb61e6eeE
         2784     rust_begin_unwind
          632     _ZN6kernel7process14load_processes17h474a4d3a0fa635b2E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17he7db392babdcfe2dE

hail
----------------------
reset_handler stack frame:

5 largest stack frames:
         1064     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hb5a3216c622528a3E
         1016     _ZN72_$LT$kernel..ipc..IPCData$LT$_$GT$$u20$as$u20$core..default..Default$GT$7default17h0111ce36fa01b1aaE
          616     _ZN6kernel7process14load_processes17he2276ec1368dc6e2E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h734bf6d34776bfa4E

arty_e21
----------------------
reset_handler stack frame:

5 largest stack frames:
          480     _ZN6kernel7process14load_processes17h97be39c2a47a4231E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17hd57140269b8ff373E
          288     _ZN6kernel5debug15panic_cpu_state17h07a7245856bf3386E
          272     _ZN6kernel5sched6Kernel11kernel_loop17h7e19f5df7eb805bbE
          240     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$16print_memory_map17hbb0df8982ebb28bdE

nucleo_f429zi
----------------------
reset_handler stack frame:

5 largest stack frames:
         3184     _ZN13nucleo_f429zi15get_peripherals17h8d482e87aeb27f02E
         2784     rust_begin_unwind
          616     _ZN6kernel7process14load_processes17h119e538f069ae859E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hc0761acaee297ec3E

microbit_v2
----------------------
reset_handler stack frame:

5 largest stack frames:
         1712     _ZN11microbit_v215get_peripherals17h3b4c27a2b28b64b4E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17hc18cff78f42d2f2dE
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hb6f2e8c6d2b2887bE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17hae61da99ed6c3574E

imxrt1050-evkb
----------------------
reset_handler stack frame:

5 largest stack frames:
         2360     _ZN14imxrt1050_evkb15get_peripherals17h4bff313617eaa687E
         1016     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17he6cb50d1e03759d4E
          832     _ZN6kernel7process14load_processes17hb6d4daf39c2cd832E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          480     _ZN79_$LT$cortexm..mpu..CortexMConfig$LT$_$GT$$u20$as$u20$core..default..Default$GT$7default17he11732d64b21a6b6E

acd52832
----------------------
reset_handler stack frame:

5 largest stack frames:
         1344     _ZN8acd5283215get_peripherals17hd9dedb4c54c19ce7E
          608     _ZN6kernel7process14load_processes17h4e3abc424751c0c4E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hef404037b35b635eE
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h54cbae7ffa30b798E
          272     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17ha9a81e4de45b1d76E

imix
----------------------
reset_handler stack frame:

5 largest stack frames:
          616     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h4442597958d62218E
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17h73fbed6e3b9582e4E
          568     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17h9ee7a40920b611e7E
          536     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17haa4f9cfedb6df7c6E

nucleo_f446re
----------------------
reset_handler stack frame:

5 largest stack frames:
         3184     _ZN13nucleo_f446re15get_peripherals17h2ae6de21ded1c9beE
         2784     rust_begin_unwind
          624     _ZN6kernel7process14load_processes17h9bced38b7d22546fE
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h7b16317de605bb3fE

litex_arty
----------------------
reset_handler stack frame:

5 largest stack frames:
          560     _ZN6kernel7process14load_processes17ha17b6a3c33765e34E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17h758234199a7207a5E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h31bc9feaa3370525E
          288     _ZN6kernel5sched6Kernel11kernel_loop17habc387240d65dec4E
          288     _ZN6kernel5debug15panic_cpu_state17h5f488ccdd45dca36E

litex_sim
----------------------
reset_handler stack frame:

5 largest stack frames:
          560     _ZN6kernel7process14load_processes17h879c3514fa7cb2e7E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17he0c92594b0489dcaE
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17hf299a644a0e112aaE
          288     _ZN6kernel5sched6Kernel11kernel_loop17hacb6db99f3d8a0feE
          288     _ZN6kernel5debug15panic_cpu_state17hd837d658473d36ddE

swervolf
----------------------
reset_handler stack frame:

5 largest stack frames:
          464     _ZN6kernel7process14load_processes17h5258ffb0dca12b17E
          384     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$18print_full_process17hbb5c8c294b078effE
          288     _ZN6kernel5debug15panic_cpu_state17he8c24492ac1a427fE
          240     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$16print_memory_map17h2fa2e294000bfc88E
          240     _ZN6kernel5sched6Kernel11kernel_loop17h0d715ff986c30c50E

clue_nrf52840
----------------------
reset_handler stack frame:

5 largest stack frames:
         2008     _ZN13clue_nrf5284015get_peripherals17h7201ba6d23c0ff9eE
         1128     _ZN94_$LT$components..cdc..CdcAcmComponent$LT$U$C$A$GT$$u20$as$u20$kernel..component..Component$GT$8finalize17h964230a41c8c7401E
          792     _ZN98_$LT$capsules..ieee802154..framer..Framer$LT$M$C$A$GT$$u20$as$u20$kernel..hil..radio..RxClient$GT$7receive17h2d536cd5242d665cE
          696     _ZN8capsules10ieee8021546framer19Framer$LT$M$C$A$GT$18step_receive_state17ha0bb5c6b9dce8feeE
          616     _ZN6kernel7process14load_processes17hab545c6c65b58d43E

msp-exp432p401r
----------------------
reset_handler stack frame:

5 largest stack frames:
          608     _ZN7cortexm24kernel_hardfault_arm_v7m17hf8c557e3e1a7d761E
          608     _ZN6kernel7process14load_processes17h33965391790ace80E
          568     _ZN82_$LT$kernel..process..Process$LT$C$GT$$u20$as$u20$kernel..process..ProcessType$GT$11try_restart17h638dfccb8d826a07E
          440     main
          296     _ZN6kernel5grant21AppliedGrant$LT$T$GT$15get_or_allocate17h360a839dcb81adb4E
```

`main()` is no longer the top on any board!

**Review by hudson-ayers — APPROVED** [review]
Thanks for taking this on!

**Pull request merged**
