### PR TITLE
Allow apps to handle interrupts at any time*

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

As [documented ](https://github.com/tock/tock/blob/master/doc/Userland.md#callbacks) currently apps must register a callback then `yield` before the kernel will call the callback. This means that if an app registers a callback for an interrupt (such as a GPIO input) but then performs a long running task the app won't get the interrupt. Even though the kernel has received the interrupt and added it to the processes queue.

This current method works well for anything that is event driven, such as an app that registers callbacks then `yields`.
Apps that do need to force an event to happen (like printing) can use `yield_for` but it doesn't work too well for nondeterministic interrupts on long running processes (like waiting for a GPIO to stop a long calculation).

This PR changes the current implementation to allow apps to run the callbacks without yielding. NOTE: This will still not interrupt a running application. When we call `do_process()` in the Tock kernel to schedule a process we will run the first item in the queue, saving the current state (if we weren't running a callback) onto the queue.

### Testing Strategy

Not tested. This works somewhat on RISC-V but will eventually crash, completely untested on ARM. It probably breaks ARM.

### TODO or Help Wanted

Review and comments please.

### Documentation Updated

The documentation has not been updated. That will have to be done as well as inline comments.

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make formatall`.

### CODE REVIEW

**Comment by gendx** [comment]
> Apps that do need to force an event to happen (like printing) can use `yield_for` but it doesn't work too well for nondeterministic interrupts on long running processes (like waiting for a GPIO to stop a long calculation).

I was also confused about how to interrupt a long calculation. My take is that the current "Tock way" of doing that is with multiple processes and IPC. Although the "GPIO handling" process cannot really stop the long calculation, it can still handle other events and signal the other process to stop whenever it's done. However, I haven't experimented with multiple processes so far so I'm not much familiar with Tock's IPC.

Maybe we could imagine some new syscall(s) allowing a process A to "terminate" another process B? Let's say B first authorizes A to terminate it, then B starts its long calculation, and if A gets the GPIO event it tells the kernel to terminate B (using B's authorization). This could also go together with [efforts to support other schedulers](https://github.com/tock/tock/issues/1441).

> Not tested. This works somewhat on RISC-V but will eventually crash, completely untested on ARM. It probably breaks ARM.

I don't think that the fact of interrupting an app at any execution point to call an arbitrarily complex callback is sound in general. Even if we get the saving/restoring of the app's context (registers) right.

Let's say that an app is in the process of mutating some data structure X, and that in the meantime it gets pre-empted to call some callback. If this callback itself wants to access X this causes memory corruption, undefined behavior, etc. On the contrary, an app calling `yield` is a convention to tell the kernel "I'm in a safe state to receive callbacks".

To take an analogy, Linux signal handlers are restricted in that they are only allowed to perform "async signal safe" operations - precisely because signals can preempt the process at any time. I'm not sure we want to put similar constraints on callbacks written in libtock-c/libtock-rs, nor how to model that to be safe from memory corruption. I don't think allowing the kernel to trigger memory corruption in an app because a too-powerful callback was called at the wrong time is in accordance with Tock as a **secure** embedded OS (see also https://github.com/tock/tock/pull/1376 for an example of what could go wrong with callbacks called at the wrong time).

Another question is how do you plan to handle recursive preemption, i.e. an app being interrupted again while it handles a callback? I guess you need to store the app's state in some sort of stack, which can overflow if too many interrupts happen too fast. That's a new failure mode of apps to consider. On the contrary, this can be avoided with the current execution model, with the app not calling `yield` within a callback handler (I'd even say that not calling any syscall from a callback handler is the "safe" thing to do). Instead, if too many events happen too fast, the process' callback queue (`Process::tasks`) will currently fill up until some events are dropped.

**Comment by alistair23** [comment]
> Maybe we could imagine some new syscall(s) allowing a process A to "terminate" another process B? Let's say B first authorizes A to terminate it, then B starts its long calculation, and if A gets the GPIO event it tells the kernel to terminate B (using B's authorization). This could also go together with [efforts to support other schedulers](https://github.com/tock/tock/issues/1441).

That sounds like what this PR is allowing. This PR allows Tock to run something from the queue without the app having to yield. Currently we don't look at IPCs, but that is easy to add, we could only add IPC and not queue support and that would get us what you are describing.

Without something like this even with a new syscall there is no way to affect a process while it's running a long task as no queue or IPC is handled.

> I don't think that the fact of interrupting an app at any execution point to call an arbitrarily complex callback is sound in general. Even if we get the saving/restoring of the app's context (registers) right.

This just allows us to run something from the queue when we switch back to the app. We still won't actually interrupt the app. The app either has to run a syscall or have the time slice expire and be scheduled out. This doesn't change too much from today.

I agree that the time slice can occur at any time though.

> Let's say that an app is in the process of mutating some data structure X, and that in the meantime it gets pre-empted to call some callback. If this callback itself wants to access X this causes memory corruption, undefined behavior, etc. On the contrary, an app calling `yield` is a convention to tell the kernel "I'm in a safe state to receive callbacks".

Yes, that won't work. Maybe this functionality could be an opt in thing? As in I opt for this callback to be ready to run whenever. Maybe something for Tock2.0?

> Another question is how do you plan to handle recursive preemption, i.e. an app being interrupted again while it handles a callback? I guess you need to store the app's state in some sort of stack, which can overflow if too many interrupts happen too fast. That's a new failure mode of apps to consider. On the contrary, this can be avoided with the current execution model, with the app not calling `yield` within a callback handler (I'd even say that not calling any syscall from a callback handler is the "safe" thing to do). Instead, if too many events happen too fast, the process' callback queue (`Process::tasks`) will currently fill up until some events are dropped.

I guess right now I am assuming the callback won't be interrupted. If it is whatever didn't finish won't be run.

You bring up some good points. For complex callbacks this gets hard to manage, but there are simple callbacks where something like this would be useful. Maybe it's worth having a simple callback call that can then allow the callback to be run whenever?

**Comment by phil-levis** [comment]
I think this is a can of worms we really do not want to open anytime soon. Tock userspace callbacks essentially have the semantics of UNIX signals. The one thing that makes them not insanely hard to use is they are deferred until yield.

If a callback can preempt a process at any time, we will need the equivalents of sigsuspend and the sigsetmask family to protect shared variables between callbacks and the main thread. The reason these work with signals is they have a dense namespace that can map to bitmasks. We don't have that for callbacks. So managing these sets would likely devolve to dynamic allocation and linked lists, unless we have a deterministic (compile-time generated) acceleration structure that maps existing callbacks to a bit array.

Put another way, this introduces unsolvable race conditions in processes, which would require a whole new set of (complex) APIs to protect against.

**Comment by rajivr** [comment]
For our use-case, we have just started initial design work largely inspired by Xen hypervisor architecture. I don't think I'll be ready in the Tock 2.0 timeframe, but this is something we can potentially consider for Tock 3.0 as we will have implementation experience by then.

The hypervisor-kernel boundary in Xen (which would be kernel-user boundary for us) has a number of interesting properties.

1. There is only one upcall into lesser privileged mode. In TockOS, in the process struct, we currently have a hard limit of a maximum 10 callbacks which can result in a scenario of dropped callbacks.

2. Xen has something known as [event channels](https://wiki.xen.org/wiki/Event_Channel_Internals). The current design is documented [here](https://xenbits.xen.org/people/dvrabel/event-channels-H.pdf). It uses an array like structure to implement a linked list. With event channels, we can avoid the potential for dropped callbacks and we also get `select` like semantics for free.

3. In Xen, the kernel (process in our case) gets to decide if an upcall handler should be called or not when the kernel (process) is scheduled out and rescheduled back in. So, the responsibility of ensuring that race conditions do not occur is left to the process. Typically, the first thing the upcall handler will do is to disable a flag, dispatch based on events from event channel and re-enable the flag. So incase the scheduler decides to yank the process when its in the upcall handler, after it is scheduled back in, it will continue where it left-off and the upcall handler is not called again.

**Comment by alistair23** [comment]
I think the current callbacks only work when yielded implementation has too many issues.

I agree that this type of thing can open a can of worms, but what about something that imposes restrictions to simplify things. Either (or both) of these?

1. A new "RunningAndInterruptable" state for a process to be running and free to receive callbacks.
 - A process can tell the kernel that it is happy to be interrupted and then tell the kernel later when it wants to keep running but not be interrupted.
2. async callbacks, a special kind of callback that can be called at any time (standard callbacks remain unchanged)
 - These callbacks must be safe to be run whenever and if interrupted while running won't be rescheduled. Like the UDP of callbacks

**Comment by phil-levis** [comment]
This is a really well understood and long-standing challenge that's appeared in many places in systems software; let's not repeat mistakes. 

One of the challenges that comes up is the interactions with enabling/disabling callbacks and yield(). You need to be able to atomically yield and re-enable callbacks. This is to prevent deadlock race conditions, when you wait for a callback that never arrives. 

Global enable/disable is tricky, in particular due to nesting. I.e., if your function calls a function that has to disable callbacks because it modifies shared state, it's important that it doesn't re-enable them, but rather restore them to the previous state. Otherwise code like this breaks:

```
disable_callbacks();
x += 1;
library_function();
x -= 1;
enable_callbacks();
```

where `x` is modified in a callback. If the library function re-enables callbacks then x is no longer protected. So you end up with something like sigprocmask, although you could just use a global flag.

Except a global flag will also break things. Because if you call a blocking library function, it will need to re-enable callbacks. If this causes your callback to be invoked, and modify state, then what you thought was an atomic block isn't. But if you don't re-enable callbacks the blocking call will never return.

async callbacks are not possible to program: they cannot share state with the main loop, unless you use only flags or race-free data structures. You're asking for interrupts without any way to disable them.

**Comment by alistair23** [comment]
I don't think async callbacks are impossible to program. Assuming that Tock will remain single threaded (at least for a application and all it's callbacks) then async calls shouldn't be impossible. From a libtock-rs perspective I think we can use Rust to ensure safety (C is a different issues). There are Rust threading libraries that handle this nicely and ours isn't actually multithreaded so it should be easier.

**Comment by phil-levis** [comment]
Unmaskable asynchronous callbacks are not impossible to program. They do, however, have unsolvable race conditions. I.e., it can be nearly impossible to write code that executes correctly, unless you drop down to assembly, in the same way that interrupts do if you can't mask them. Single threaded doesn't matter because the issue here is asynchronous preemption of a user thread.

All I'm saying is that this problem is not a new one. There are well-known problems and challenges. There are some well-known solutions which tackle them. Unfortunately those solutions won't work well as-is in Tock. So if we want to apply one we'll need to add some more kernel mechanisms (e.g., callback namespace compression). But if we're going to invent something new, the first thing to do is check off that it solves the well-known problems.

**Comment by jrvanwhy** [comment]
> From a libtock-rs perspective I think we can use Rust to ensure safety (C is a different issues).

I'm 90% confident you would need to implement a mutex type to prevent a callback from accessing the same data as the thread it interrupted. I'm not 100% sure that's possible without atomics. Even if it is, if the signal finds the mutex is locked it has no way to yield to the higher-level thread, which will lead to complex "did a signal try to access this Mutex we are unlocking" logic.

> There are Rust threading libraries that handle this nicely and ours isn't actually multithreaded so it should be easier.

Would you mind giving an example?

I'm not entirely opposed to making `libtock-rs` a multithreaded runtime. However, those threads would either need to be cooperative (which doesn't solve the "interrupt a long-running computation" problem) or they would need kernel support (e.g. to implement mutexes). A multithreaded runtime would also be expensive, though probably less expensive than multiple apps and IPC.

**Comment by phil-levis** [comment]
> I'm 90% confident you would need to implement a mutex type to prevent a callback from accessing the same data as the thread it interrupted. I'm not 100% sure that's possible without atomics. Even if it is, if the signal finds the mutex is locked it has no way to yield to the higher-level thread, which will lead to complex "did a signal try to access this Mutex we are unlocking" logic.

This is correct. It's why, for example, interrupt handlers can't acquire mutexes. Because they are pushed on top of an existing stack, if that stack is what holds the mutex you have deadlock. Rather than using mutexes to protect state between the main thread of control and interrupts, you disable/enable interrupts. So, to go back to my original point, we would need a way to enable/disable callbacks dynamically. The mechanisms would look a lot like `sigprocmask(2)` and `sigsuspend(2)`. Also going back to my original point, since we have a sparse identifier space (unlike signals, which are dense), maintaining and storing masks is going to be more complicated than it is with signals (we will need either a linked list or a mapping/lookup table).

**Comment by alistair23** [comment]
> Would you mind giving an example?

From memory the [`std::thread::spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html) function will error if you pass anything in that isn't `Sync/Send`.
The [rust glib wrapper](https://gtk-rs.org/docs/glib/source/fn.idle_add.html) has a similar thing.

**Comment by gendx** [comment]
I'd again emphasize that **multi-threading** isn't the same thing as **reentrancy** (see for example [Wikipedia's examples](https://en.wikipedia.org/wiki/Reentrancy_(computing)#Examples)).

Rust captures well concepts related to multi-threading (with `Sync/Send`) and has good support to write multi-threaded applications (with building blocks like `Mutex`, `Arc`, `std::thread::spawn` among others).

However, what we're talking about here is reentrancy. This is a somewhat more complex problem, because you can't just solve it by throwing mutexes at it (which would deadlock if not reentrant). As such, one is for example only allowed to call a [small subset of functions](http://man7.org/linux/man-pages/man7/signal-safety.7.html) within Linux signal handlers (a.k.a. async-signal-safety).

I'm not aware of Rust concepts to capture reentrancy - solutions will mostly be ad-hoc. As mentioned by @phil-levis, this generally involves masking/enabling/disabling the "signals" (be it *hardware interrupts*, or *callbacks* in Tock's userspace). But because Rust doesn't capture reentrancy (as far as I know), it'll be hard to safely generalize synchronous callbacks without having developers introducing bugs along the way.

As an example, as far as I understand, the [generic interrupt handler in Tock](https://github.com/tock/tock/blob/master/arch/cortex-m4/src/lib.rs#L73-L142) (at least on Cortex-M4) disables the interrupt that fired and sets a pending bit somewhere for the kernel scheduler to later pick it up. So nothing happens synchronously at the time the interrupt triggers, there is just a kernel scheduling loop that will check for pending interrupts once it's done with its current task.

**Comment by phil-levis** [comment]
@gendx Great summary.

**Comment by alevy** [comment]
Dropping a note that @alistair23, @jrvanwhy, @ppannuto and I are discussing and will prototype one or more holistic solutions to the general user-space multi-threading problem.

**Comment by alistair23** [comment]
Yep, I will hopefully have more info in a week or two. I need to scope out some things internally first.

**Comment by alistair23** [comment]
Closing this PR. After some other discussions I'm going to move this to the back burner as I have other things to do first.

**Pull request closed without merging**
