### PR TITLE
use `usize::checked_next_multiple_of`

### PR DESCRIPTION
**Pull request by folkertdev**
### Pull Request Overview

use `usize::next_multiple_of` instead of a custom macro. this function has been stable for a while.

```rust
        pub const fn next_multiple_of(self, rhs: Self) -> Self {
            match self % rhs {
                0 => self,
                r => self + (rhs - r)
            }
        }
```

### Testing Strategy

nothing to test really

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by alexandruradovici — COMMENTED** [review]
I think this makes sens, I have two observations:

- this will make Tock incompatible with any rust version below 1.73
- ~it does not handle the case when `tlv_header.length` is 0, as `next_multiple_of` will panic and while the macro does not~

**Comment by folkertdev** [comment]
> this will make Tock incompatible with any rust version below 1.73

is that not already the case? Also is that important? 1.78 is released this week so this is a fair number of rust versions back.

> it does not handle the case when tlv_header.length is 0, as next_multiple_of will panic and while the macro does not

I think this only panics when the `rhs` is zero (which is the constant 4 in practice). So that panic is statically unreachable?

**Comment by alexandruradovici** [comment]
> > this will make Tock incompatible with any rust version below 1.73
> 
> is that not already the case? Also is that important? 1.78 is released this week so this is a fair number of rust versions back.

I'm not saying that this is a bad thing, but as for now Tock compiles with stable Rust (for ARM targets), we should specify the MSRV somehow, maybe in `Cargo.toml`.

> 
> > it does not handle the case when tlv_header.length is 0, as next_multiple_of will panic and while the macro does not
> 
> I think this only panics when the `rhs` is zero (which is the constant 4 in practice). So that panic is statically unreachable?

My mistake here, never mind this.

**Comment by bradjc** [comment]
We should use [checked_next_multiple_of](https://doc.rust-lang.org/std/primitive.usize.html#method.checked_next_multiple_of). Even if we can convince ourselves panic-ing is not an issue in this case, the TBF crate strives to be as panic-free as possible, in part to serve as an example of how to write panic-less rust code.

**Comment by alevy** [comment]
@alexandruradovici does MSRV impact things like, idk... the ability to use some certified compiler? If so, that's probably worth worrying about. If not, I agree we should still specify an MSRV (separately from this PR probably)

**Comment by alevy** [comment]
> We should use [checked_next_multiple_of](https://doc.rust-lang.org/std/primitive.usize.html#method.checked_next_multiple_of).

What would we do in the `None` case? It kind of doesn't matter, because that branch is _also_ unreachable, but we still would have to write something

**Comment by bradjc** [comment]
> > We should use [checked_next_multiple_of](https://doc.rust-lang.org/std/primitive.usize.html#method.checked_next_multiple_of).
> 
> What would we do in the `None` case? It kind of doesn't matter, because that branch is _also_ unreachable, but we still would have to write something

`?`

**Comment by alevy** [comment]
@bradjc sure, except the return type of the function this is in is a `Result` and and the return type of `checked_next_multiple_of` is an `Option`, so to use `?` we'd first have to `.ok_or([SOME_ERROR])`. That seems OK actually.

It's not as pretty as Rust having a `no_panic` option that fails to compile _if_ any panics are reachable, but... cest la vie

**Comment by bradjc** [comment]
> @bradjc sure, except the return type of the function this is in is a `Result` and and the return type of `checked_next_multiple_of` is an `Option`, so to use `?` we'd first have to `.ok_or([SOME_ERROR])`. That seems OK actually.

Yessir. The error should be the not enough memory error. That type of code is probably ~50% of the lines in the TBF parsing crate (since rustfmt puts .function() on its own line quite often).

> It's not as pretty as Rust having a `no_panic` option that fails to compile _if_ any panics are reachable, but... cest la vie

AGREED. While rust is great about forcing `unsafe`, it's happy to panic everywhere.

**Comment by folkertdev** [comment]
I picked `InternalError`, it's description seems to fit best 

>     /// Internal kernel error. This is a bug inside of this library.

**Review by alevy — APPROVED** [review]

**Review by alexandruradovici — APPROVED** [review]

**Comment by bradjc** [comment]
> I picked `InternalError`, it's description seems to fit best
> 
> > ```
> > /// Internal kernel error. This is a bug inside of this library.
> > ```

Ok on second thought because `tbf_header.length` is a `u16`, adding 3 can't overflow a `usize`. So I agree that internal error is appropriate.

**Pull request merged**
