### PR TITLE
OpenTitan: Update the bitstream SHA

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

Update the OpenTitan bitstream SHA. As part of the update also update
the UART baud rate and clock speeds to match the new times.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### Testing Strategy

Starting to run the 1.6 release tests on OpenTitan.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Looks good; out of curiosity, do you know why the clock frequencies were slowed?

**Comment by alistair23** [comment]
They couldn't meet timing with the previous clocks.

**Comment by bradjc** [comment]
So this SHA resolves the timing uncertainties? Do you think this is the best candidate to use for 1.6?

**Comment by alistair23** [comment]
Yes, this is a better candidate for 1.6. It is what I have used for release testing.

**Comment by alistair23** [comment]
Ping! Tock builds are failing with the old boot ROM.

**Review by ppannuto — APPROVED** [review]
bors r+

**Pull request merged**
