### PR TITLE
Add Pico Explorer Base development board

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request adds the Pico Explorer Base, a test board around the Raspberry Pi Pico.

The Raspberry Pi Pico is not an actual development board, but rather a PCB around the RP2040. Except one single LED, it has no other sensors, buttons or display. The Pico Explorer Base is built around the Pico and provides:
- 4 buttons
- 240x240 LCD
- breadboard

### Testing Strategy

This pull request was tested using a Pico Explorer Base.

### TODO or Help Wanted

This pull request requires 
- [x] #2678 
- [x] #2679.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by phil-levis — APPROVED** [review]
Looks good. Just blocked on #2679

**Comment by phil-levis** [comment]
Can we pause on merging this until after 2.0?

**Comment by alexandruradovici** [comment]
> Can we pause on merging this until after 2.0?

As this is mostly identical to the Raspberry Pi Pico, is there any particular reason for pausing this?

**Comment by phil-levis** [comment]
Following the discussion on the core call, the goal is to include this in the 2.0 release.

**Review by phil-levis — APPROVED** [review]

**Pull request merged**
