### PR TITLE
rust: update to 2020-10-25

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates the rust nightly version to 2020-10-25.

I had to add a feature in two places. I have no idea why or what changed, but the compiler instructed me to add them.

Two issues:

```
error[E0658]: mutable references are not allowed in constant functions
  --> chips/lowrisc/src/hmac.rs:87:21
   |
87 |             digest: Cell::new(None),
   |                     ^^^^^^^^^^^^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
   = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable

error[E0658]: mutable references are not allowed in constant functions
  --> chips/lowrisc/src/hmac.rs:87:31
   |
87 |             digest: Cell::new(None),
   |                               ^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
   = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `lowrisc`
```

and 
```
error[E0658]: mutable references are not allowed in constant functions
  --> libraries/tock-cells/src/take_cell.rs:21:18
   |
21 |             val: Cell::new(None),
   |                  ^^^^^^^^^^^^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
   = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable

error[E0658]: mutable references are not allowed in constant functions
  --> libraries/tock-cells/src/take_cell.rs:21:28
   |
21 |             val: Cell::new(None),
   |                            ^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
   = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `tock-cells`
```

### Testing Strategy

This pull request was tested by travis.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by alistair23** [comment]
Should we just change the `new()` to not be a const and not add the new feature?

**Comment by hudson-ayers** [comment]
> Should we just change the `new()` to not be a const and not add the new feature?

We can't do this because `new()` has to be `const` in order to initialize a `pub static mut Hmac` (or, similarly, to use `TakeCell` in any `pub static mut` object). Once my peripheral instantiation PRs are merged we can make that change.

**Review by alistair23 — APPROVED** [review]

**Comment by hudson-ayers** [comment]
Pushed a fix so that clippy passes, using the guide here: https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html for correctly implementing `PartialOrd` on a type that manually implements `Ord`

**Review by hudson-ayers — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Pull request merged**
