### PR TITLE
Fix restarting apps

### PR DESCRIPTION
**Pull request by hudson-ayers**
### Pull Request Overview

This pull request fixes how app restarting is handled by re-initializing the context switching state when the process is being restarted.

This change does this by calling the initialize function in the `UserlandKernelBoundary` trait. However, the process is no longer "new" so I renamed the function. Also, we can't rely on the constructor for the stored state to initialize values, and the `initialize_process()` function must do that.

This also updates the example code in hail to enable restarting all apps.

### Testing Strategy
Using the restart all apps capsule to restart blink, c_hello, and hello_loop on hail.

### TODO or Help Wanted

- I can revert the function name change if that is too big of a change.
- ~~`hello_loop` doesn't restart correctly, but I'm not sure why.~~ fixed now

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by phil-levis** [comment]
Can you describe what the problem was and how this code solves it?

**Comment by hudson-ayers** [comment]
The problem is mostly described in issue #1524 , but the gist of is that using the debug_process_restart capsule to restart apps no longer works. Prior to the change to the UserspaceKernelBoundary, enabling that capsule meant that you could press a button to restart all apps on the board. PR #1318 broke this functionality, and instead the board would panic when apps were restarted.  This PR mostly fixes the issue, which appears to be that the Process.state field was not being reset when apps were restarted (all credit to @bradjc for finding the fix though).

**Comment by bradjc** [comment]
There is an additional pointer that was added (`allow_high_water_mark`) that wasn't getting reset correctly but now is.

**Comment by bradjc** [comment]
This should be a relatively straightforward bug fix if others want to have a look. Once this is in we can get to the more interesting #1534.

**Comment by hudson-ayers** [comment]
I can't leave a review because this is technically my PR but I think the code looks good and I have confirmed it fixes the restart bug for the examples that inspired my original issue.

**Comment by ppannuto** [comment]
this is leftover from the window when netlify intergration was broken

**Pull request merged**
