### PR TITLE
Update rust-toolchain to 2021-12-04

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

This pull request updates the Rust toolchain to version `1.59.0-nightly (efec54529 2021-12-04)`. The motivation for this change is that the `litex-sim-ci` breaks when compiling `elf2tab` on the previous toolchain version:

```
error[E0658]: use of unstable library feature 'proc_macro_is_available'
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.33/src/detection.rs:28:21
   |
28 |     let available = proc_macro::is_available();
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71436 <https://github.com/rust-lang/rust/issues/71436> for more information
   = help: add `#![feature(proc_macro_is_available)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `elf2tab v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-installl05bA0`
```

Now, I'm not entirely sure as to why this happens. We haven't upgraded either of the Rust toolchain or `elf2tab`, and -- as far as I understand -- `cargo install elf2tab` should use the `Cargo.lock` file, so dependencies shouldn't change.

In any case, this update seems to fix it. Besides the failing `litex-sim-ci` workflow, it seems like a good idea to pin a `rustc` version on which vital tools such as `elf2tab` properly compile. I can also reproduce the `elf2tab` build failure locally while the `rust-toolchain` of the Tock repository is used.

### Testing Strategy

This pull request was tested by CI.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]

**Comment by lschuermann** [comment]
Huh, it would seem like this PR fails because #2912 isn't merged yet! What a coincidence to discover it in CI just after I found it locally, but we didn't otherwise notice it for many months. :laughing:

**Review by bradjc — DISMISSED** [review]
:+1:

We need to update the rust stable tracking issue after this.

**Comment by hudson-ayers** [comment]
Rust recently switched to using LLVMs new pass manager, which has led to a lot of changes around what does/does not get inlined (https://github.com/rust-lang/rust/issues/89742, https://github.com/rust-lang/rust/issues/91128, https://reviews.llvm.org/D98481), so that failure is not too surprising

**Comment by lschuermann** [comment]
With #2912 in, I've kicked off these workflows again. Hopefully there won't be a red X on the current HEAD for long. :)

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
