### PR TITLE
make: remove nonexistent target

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This target seems to not exist?

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

I'm not sure this is the correct fix.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — CHANGES_REQUESTED** [review]
This does exist. Lines 40/41 say: run `make {target}` from the *board directory*. Go to any boards/x directory and this target works correctly (the targets are in Makefile.common). They were referenced here for discoverability

**Comment by hudson-ayers** [comment]
I think this is correct as-is and we should close this PR

**Comment by lschuermann** [comment]
We might want to include a warning that these can't be issued from this Makefile instead?

**Comment by bradjc** [comment]
Oh geez I don't have time to read all of that! Why did we even name them differently in the first place.

**Pull request closed without merging**
