### PR TITLE
Tock 2.0: lsm303 and led matrix update to tock 2.0 api

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request updates the `lsm303xx` and `led_matrix` driver to the Tock 2.0 API.

### Testing Strategy

This pull request was tested using the BBC Microbit v2 board.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
Thanks for the migration to Tock 2.0! Keeping independent changes in separate commits or PRs makes them a bit easier to review, but this doesn't look to complicated so it's fine. :smile:

**Comment by alexandruradovici** [comment]
I made one single PR as they are both used for the microbit and changes are minimal.

**Review by phil-levis — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]

**Comment by alexandruradovici** [comment]
Resolved

**Pull request merged**
