### PR TITLE
doc: finalize time trd after implementation

### PR DESCRIPTION
**Pull request by jettr**
After #2665 landed, finalize the time trd.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by phil-levis** [comment]
I'd like to hold off on finalizing this until everything lands and we've been happy for it for a while. I'd hate to go through this revision process again because we missed a detail.

**Comment by jettr** [comment]
Can we land this PR to finalize the time TRD, or if not, how long to we want to wait to feel comfortable with this changes?

**Comment by phil-levis** [comment]
Let's wait a couple more weeks? I'd like to do a very detailed proofread of the text and the Stanford quarter just started, so I need a little time. So mid-October?

**Comment by hudson-ayers** [comment]
Good thing we waited on this, given https://github.com/tock/tock/issues/2851 :)

**Pull request closed without merging**
