### PR TITLE
Allow board crates to be built with `cargo build`

### PR DESCRIPTION
**Pull request by jwnrt**
### Pull Request Overview

This pull request moves the linker script flag into `build.rs` and sets each board's target triple in a `.cargo/config.toml` file in each of their crate directories.

This allows boards to successfully build using `cargo build -r` in their crates's directories. That also allows commands like `cargo size` and `cargo bloat` to work without needing `make` wrappers.

I'm fully open to this change not being accepted because I'm not sure how useful it is to you. It also adds the trade-off of having each board's target defined in both `TARGET=...` in the Makefile and `target = "..."` in `.cargo/config.toml`.

`make` is of course still the build system. In theory, all the `rustc` flags could be moved to a `boards/.cargo/config.toml` file, but these configs are only used when Cargo is run from under their directories and so it would not apply to out-of-tree boards. See https://github.com/jwnrt/tock/tree/cargo for a branch that demonstrates this.

### Testing Strategy

Applied this diff and ran `make boards`:

```diff
--- a/Makefile
+++ b/Makefile
@@ -142,6 +142,9 @@ allboards boards:
 	@for f in $(ALL_BOARDS);\
 		do echo "$$(tput bold)Build $$f";\
 		$(MAKE) -C "boards/$$f" || exit 1;\
+		pushd "boards/$$f";\
+		cargo build -r;\
+		popd;\
 		done
 
 .PHONY: allcheck check

```

### TODO or Help Wanted

* Is this change desired?
* Do Tock contributors have any issue with just using `make` in the first place?
* If you would like to just use Cargo eventually (including for tests etc.) then some solutions to things to where to put flags would be needed.
* Some Cargo changes would also probably help, e.g. [per-package-target](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#per-package-target) and [artifact-dependencies](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies).
* Is there any way to de-duplicate defining both `TARGET=...` and `target = "..."`? It doesn't seem like Cargo provides an easy way to get the path to a completed binary other than doing builds with `--message-format=json` and parsing JSON.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — CHANGES_REQUESTED** [review]
Unfortunately I'm quite opposed to this change. The reason being that `.cargo` is a hidden directory, and I strongly believe that critical configurations in how software is built should never be hidden.

We've thought about similar changes in the past: https://github.com/tock/tock/pull/2972 https://github.com/tock/tock/pull/2962 but ultimately decided that if we cannot move everything than we shouldn't move some config out of the makefile.

Ideally cargo would just let us use _any_ other filename other than one that starts with a "." for this. I really have no idea why they want this to be hidden. But for new users, having critical flags that affect how software is built be hidden is, in my opinion, an unnecessary roadblock to understanding how the project works. It also presents another hurdle when porting tock, because someone might not even realize they have to change something in a hidden file.

**Comment by bradjc** [comment]
Otherwise I would be in favor of this PR! We just need cargo to let us use `cargo.toml` or something.

**Comment by jwnrt** [comment]
I definitely understand that being an issue, I'll close this PR for now. Perhaps some future Cargo changes might make this nicer.

**Comment by brghena** [comment]
I agree with Brad about hidden files.

However, I do want to weigh various pros and cons. So if there are other reasons why this would be beneficial which might overcome the reasons why it's harmful, it could be worth discussing further.

**Comment by lschuermann** [comment]
I also agree with Brad's concerns. At the same time, Tock's divergence from many of the standard practices around the Rust ecosystem (and in particular it's heavy reliance on Make) can and does irritate newcomers who are otherwise familiar with Rust. There is going to be a tradeoff in the complexities with hidden and scattered configurations, and diverging from standard practices (to be fair -- many of which didn't exist when these parts of Tock were written), and I'm not sure how to strike the right balance.

**Comment by bradjc** [comment]
Our makefile is full of subtlety, and it seems unlikely cargo will ever be able to capture and organize everything we need to do.



> There is going to be a tradeoff in the complexities with hidden and scattered configurations

While I generally want to side with rust and go with convention, this is one thing that I think they are just getting wrong. Already you have to look at rust-toolchain.toml, Cargo.toml, boards/<board>/Cargo.toml, and build.rs, and then Makefile, and Makefile.common to figure out how your code is getting compiled.

**Comment by ppannuto** [comment]
FWIW, @jrvanwhy opened an issue ~4 years ago on this which remains open: https://github.com/rust-lang/cargo/issues/8244 — might be worth nudging upstream again?

**Pull request closed without merging**
