### PR TITLE
RFC: Cortex-M: Use two MPU regions for app memory rather than one

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

Currently the Cortex-M MPU uses a single MPU region for process memory. That region must be a power of two and aligned to its size. In practice, this can lead to a huge amount of wasted memory between the end of the kernel's memory and the start of process memory. For example, on hail with the c_hello app installed, the memory map looks like:

```
tock$ process c_hello
𝐀𝐩𝐩: c_hello   -   [Yielded]
 Events Queued: 0   Syscall Count: 8   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, address: 0x0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20008000═╪══════════════════════════════════════════╝
             │ Grant Ptrs      112
             │ Upcalls         360
             │ Process         880
  0x20007AB8 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20007A6C ┼───────────────────────────────────────────
             │ Unused
  0x20006A04 ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   4200               S
  0x20006A04 ┼─────────────────────────────────────────── R
             │ Data            516 |    516               A
  0x20006800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         128 |   2048
  0x20006780 ┼───────────────────────────────────────────
             │ Unused
  0x20006000 ┴───────────────────────────────────────────
             .....
  0x00040800 ┬─────────────────────────────────────────── F
             │ App Flash      1972                        L
  0x0004004C ┼─────────────────────────────────────────── A
             │ Protected        76                        S
  0x00040000 ┴─────────────────────────────────────────── H
tock$ kernel
Kernel version: 2.1 (build release-2.1-1-gefb03eadb)

 ╔═══════════╤══════════════════════════════╗
 ║  Address  │ Region Name    Used (bytes)  ║
 ╚0x20004470═╪══════════════════════════════╝
             │   BSS         13424
  0x20001000 ┼─────────────────────────────── S
             │   Relocate        0            R
  0x20001000 ┼─────────────────────────────── A
             │ ▼ Stack        4096            M
  0x20000000 ┼───────────────────────────────
             .....
  0x0002B88C ┼─────────────────────────────── F
             │   RoData      26858            L
  0x00024FA2 ┼─────────────────────────────── A
             │   Code        85922            S
  0x00010000 ┼─────────────────────────────── H
```
So between the end of the kernel RAM at 0x20004470 and the start of the process RAM at 0x20006000, there are 7056 bytes of unused memory.

## Question

What, if anything, should we do about the wasted RAM on Cortex-M platforms?

## This PR

This PR switches the MPU to use two regions for app memory, rather than one. The amount of ram given to processes stays the same, it is just split evenly between two regions, so each region is half of the size and therefore aligned to half the size.

```
tock$ process c_hello
𝐀𝐩𝐩: c_hello   -   [Yielded]
 Events Queued: 0   Syscall Count: 8   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, address: 0x0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20007000═╪══════════════════════════════════════════╝
             │ Grant Ptrs      112
             │ Upcalls         360
             │ Process         880
  0x20006AB8 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20006A6C ┼───────────────────────────────────────────
             │ Unused
  0x20005A04 ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   4200               S
  0x20005A04 ┼─────────────────────────────────────────── R
             │ Data            516 |    516               A
  0x20005800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         128 |   2048
  0x20005780 ┼───────────────────────────────────────────
             │ Unused
  0x20005000 ┴───────────────────────────────────────────
             .....
  0x00040800 ┬─────────────────────────────────────────── F
             │ App Flash      1972                        L
  0x0004004C ┼─────────────────────────────────────────── A
             │ Protected        76                        S
  0x00040000 ┴─────────────────────────────────────────── H
tock$ kernel
Kernel version: 2.1 (build release-2.1-2-g204b40400)

 ╔═══════════╤══════════════════════════════╗
 ║  Address  │ Region Name    Used (bytes)  ║
 ╚0x20004470═╪══════════════════════════════╝
             │   BSS         13424
  0x20001000 ┼─────────────────────────────── S
             │   Relocate        0            R
  0x20001000 ┼─────────────────────────────── A
             │ ▼ Stack        4096            M
  0x20000000 ┼───────────────────────────────
             .....
  0x0002B93C ┼─────────────────────────────── F
             │   RoData      26836            L
  0x00025068 ┼─────────────────────────────── A
             │   Code        86120            S
  0x00010000 ┼─────────────────────────────── H
```

This also has the effect of making the subregions half the size, so we get finer-grained protection around the app_brk.

## Downsides

- Adds a little bit more complexity
- Uses up another of the scarce MPU regions

### Testing Strategy

Running apps on hail

### TODO or Help Wanted

Is this worth it? Should we ignore this problem? Anyone have other ideas?

Another question: why stop at two? Fairly easy to implement with two, but we could use more.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by alistair23** [comment]
ls there a reason to save the MPU regions? On RISC-V we use them to protect the kernel, but I don't think ARM can do that right?

**Comment by bradjc** [comment]
> ls there a reason to save the MPU regions? On RISC-V we use them to protect the kernel, but I don't think ARM can do that right?

The reason is because the current IPC implementation needs MPU regions for each shared buffer.

**Comment by alistair23** [comment]
Ah, forgot about that.

Are we hitting the limit on ARM MPU regions? Otherwise the memory savings seem valuable

**Review by hudson-ayers — APPROVED** [review]
I think that the memory savings are worth losing one IPC region

**Review by hudson-ayers — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]

**Review by ppannuto — DISMISSED** [review]
bors r+

I read over this twice, and it all looks correct, but man if there is a place to prioritize effective unit tests, MPU configuration feels like it

**Review by ppannuto — APPROVED** [review]
bors r+

My kingdom for a clearer 'changes since you last viewed' :(

**Pull request merged**
