### PR TITLE
chips: doc: update supported HIL table

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates the chip readme to show changes to the supported HILs for various chips. Just a periodic doc improvement.

### Testing Strategy

This pull request was tested by travis.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ahl** [comment]
@bradjc what would you think about turning this chart into a tri-state? Today "blank" means both "not applicable" and "not yet implemented". We had a version oft his in our fork for ibex/earlgrey/lowrisc:

https://raw.githubusercontent.com/oxidecomputer/tock/opentitan/chips/README.md

This would be helpful as the support for some of these platforms is evolving. If you'd be amenable to something like this, we'd be happy to submit a PR.

**Comment by bradjc** [comment]
> @bradjc what would you think about turning this chart into a tri-state? Today "blank" means both "not applicable" and "not yet implemented".

In general, sounds good to me! I'm not exactly sure how to encode that information for the script, however.

**Comment by ppannuto** [comment]
It might not be necessary to do much to the script. A "N/A" state would never change, so it doesn't really need to be automated. Perhaps just allowing N/A in the table and not allowing the script to overwrite N/A entries is sufficient

**Pull request merged**
