### PR TITLE
Add OSX to Travis-CI.

### PR DESCRIPTION
**Pull request by gendx**
### Pull Request Overview

This pull request adds OSX to the Travis-CI config. This will help detect CI build failures on OSX machines without waiting for manual testing (see for example https://github.com/tock/tock/pull/1393#issuecomment-539723255).

### Testing Strategy

This pull request was tested by waiting for Travis-CI results.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by gendx** [comment]
There is indeed some overhead (11 minutes on OSX vs. 7 minutes for Linux in the current state, for a total latency of 12 minutes). Looks like it was indeed removed 2 years ago (https://github.com/tock/tock/commit/ce0b29eb4503ea49e0196b4a466a1d4f7e2a4bfc).

However, it seems that OS-specific installation steps are not needed anymore, and the OSX build doesn't seem broken as of now. On the other hand, some build steps (most likely only for tests) could break if not manually checked as highlighted by https://github.com/tock/tock/pull/1393#issuecomment-539723255.

So it mostly boils down to the extra (roughly +50%) latency, vs. overhead of manually checking that things still build on OSX.

**Comment by ppannuto** [comment]
Mhm, try the build again around early afternoon pacific time, when both
east and west coast US are active, the Travis queue for running Mac jobs
gets several hours deep:



You can pay for Travis enterprise to get around this problem, but that
doesn’t really seem worth it just for this

**Comment by ppannuto** [comment]
That said, now that we’re using bors to merge and don’t have to babysit
Travis, maybe the latency would matter less.

**Comment by gendx** [comment]
Indeed, the backlog seems quite large at these times, especially since last week: https://www.traviscistatus.com/#month
Makes sense then.

**Comment by bradjc** [comment]
I'm opposed to adding back osx builds (unless travis has changed substantially, but it doesn't seem like that is the case, or if we are finding bugs that only exist on Rust on mac). I care a lot about the overhead of submitting PRs, and since it is very difficult to get a PR review when the PR doesn't build, I have to babysit PRs until travis is happy, and that was annoying when the build took a long time.

**Comment by ppannuto** [comment]
I think we've re-reached the prior consensus again on this so I'm going to close it -- feel free to comment if this warrants more discussion

**Pull request closed without merging**
