### PR TITLE
Extend feature support for lowrisc UART

### PR DESCRIPTION
**Pull request by jon-flatley**
### Pull Request Overview

This PR adds the following to the lowrisc UART implementation

- Parameter validation for baud rate configuration
- Support for different parity modes
- An implementation of `ReceiveAdvanced::receive_automatic()` using the UART's built in `rx_timeout`
- Adds support for a few interrupt driven errors and adds `BreakError` to the UART HIL

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

**Comment by jrvanwhy** [comment]
This is failing in QEMU, but works for me on a cw310.

@alistair23 is this a QEMU inaccuracy or a real issue with the PR?

**Comment by alistair23** [comment]
Hmm.... I might need some help with this one. I don't see how this can work anywhere.

I see these values

```
baud_rate = 115200
self.clock_frequency = 6_000_000
```

Which gives:

```
baud_adj = 120_795_955_200
freq_clk = 6_000_000
uart_ctrl_nco = 20132
uart_ctrl_nco_rem = 3_955_200
```

Which ends up with:

```
40 * uart_ctrl_nco_rem = 158_208_000
39 * freq_clk = 234_000_000
```

Which then goes through the `Remainder is outside the acceptable range, requested baud rate is invalid.` error condition. What am I missing here?

**Comment by jon-flatley** [comment]
Thanks @alistair23, you're absolutely right, the baud rate configuration was indeed failing from my bad math. I've updated the NCO logic and added a couple test cases to sanity check this time. Not sure if you want me to leave those in, I noticed `chips/imxrt10xx/src/gpio.rs` also has a unit test in it.

**Comment by jon-flatley** [comment]
Debugging this made me realize [`MuxUart::initialize()`](https://github.com/tock/tock/blob/50dd293411b63d64ed0250a90a7f0f0d1f5212fc/capsules/core/src/virtualizers/virtual_uart.rs#L203) doesn't pay any attention to the return value of `self.uart.configure()`, so when `ErrorCode::INVAL` was returned when configuring the baud rate things just silently moved forward, and since presumably these registers were already set in the ROM there were no signs of this failing during my testing.

**Review by jrvanwhy — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Comment by alistair23** [comment]
Great to see the QEMU CI catching bugs, even ones that the hardware doesn't catch :)

**Review by twilfredo — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]
Don't have a CW310 to test _just yet_, but changes look good to me otherwise!

**Pull request merged**
