### PR TITLE
opentitan: Reduce RAM usage in linker script

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

Reduce the RAM allocated to Tock so that we have more left over for the
apps.

### Testing Strategy

Run libtock-c apps on top of Tock on OpenTitan.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
Doesn't this reduce the RAM for apps and the kernel? We allocate memory from apps from the ram section in the kernel linker script.

https://github.com/tock/tock/blob/b49c7c9d422ae8efaa8b2fcf29639f529f33dda6/boards/opentitan/src/main.rs#L28-L30

https://github.com/tock/tock/blob/b49c7c9d422ae8efaa8b2fcf29639f529f33dda6/boards/kernel_layout.ld#L292-L303

**Comment by pfmooney** [comment]
Yeah, I think the `APP_MEMORY` sizing should be adjusted up, rather than the linker script.

**Comment by alistair23** [comment]
The problem I'm seeing is that the BSS and Data size from C apps overwrites Tock data. If I configure the linker script so that there are no overlaps then I don't see the overwrite happening.

**Comment by pfmooney** [comment]
What if you adjust `MPU_MIN_ALIGN`, or is it overwriting data in the `Process`/grant space?

**Comment by alistair23** [comment]
I don't think MPU_MIN_ALIGN is related. I think there might be an issue in the linker script though, let me just double check some things. As RISC-V doesn't have relation support it all gets a little more complex.

**Comment by alistair23** [comment]
It just overwrites some values in the kernel (resulting in strange crashes) as it zeroes out the BSS.

**Comment by bradjc** [comment]
There could be bugs in the startup code that aren't caught since there isn't pmp protection.

**Comment by alistair23** [comment]
Also, I think the same thing happens for the Rust apps, just that as they don't have `.data` and the `.bss` is tiny it doesn't matter.

**Comment by alistair23** [comment]
I managed to change the linker script around to not clash, so I'll close this.

**Pull request closed without merging**
