### PR TITLE
OpenTitan: Add support for hardware RSA operations

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This PR builds on top of:
 * https://github.com/tock/tock/pull/2898
 * https://github.com/tock/tock/pull/2892
 * https://github.com/tock/tock/pull/2839

and adds support for RSA hardware operations using the OTBN.

### Testing Strategy

Running the RSA test in this PR on the CW310 FPGA.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Comment by phil-levis** [comment]
Following up on the 11/18 OT call, I started looking into factory methods for key generation to better constrain the types. This is tricky in the context of something like OTBN. The types of keys it can support depends on what programs are loaded into it. So unless OTBN is statically configured, there's no way to be sure what keys it will support. This raises the subsequent issue of possibly passing incorrectly formatted or improper keys to the accelerator. For safety, this suggests to me that Tock should always configure imem statically, or at least directly from kernel code, such that it can change the instructions needed to support a particular key.

**Comment by alistair23** [comment]
Pushed an update to more clearly specify what is/isn't allowed in the buffer length

**Comment by alistair23** [comment]
Ping!

**Comment by alistair23** [comment]
Ping!

**Review by phil-levis — APPROVED** [review]

**Pull request merged**
