### PR TITLE
Add cargo test for chips and archs on ci-travis.

### PR DESCRIPTION
**Pull request by gendx**
### Pull Request Overview

This pull request adds unit testing of the chips to `make ci-travis`, by running `cargo test` on each chip.

This also fixes a bit of code to allow the tests to run:
- Functions using architecture-specific assembly are marked as `target_os = none`, and empty/unimplemented stubs are provided for non-none target_os.
- Some comments are reformatted so that doctests are not confused.

### Testing Strategy

This pull request was tested by running `make ci-travis`, and checking the log.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
This causes the CI build to fail on OS X machines:

```
Test cc26x2
   Compiling tock-registers v0.3.0 (/Volumes/code/helena-project/tock/libraries/tock-register-interface)
   Compiling tock-cells v0.1.0 (/Volumes/code/helena-project/tock/libraries/tock-cells)
   Compiling enum_primitive v0.1.0 (/Volumes/code/helena-project/tock/libraries/enum_primitive)
   Compiling tock_rt0 v0.1.0 (/Volumes/code/helena-project/tock/libraries/tock-rt0)
   Compiling kernel v0.1.0 (/Volumes/code/helena-project/tock/kernel)
   Compiling cortexm v0.1.0 (/Volumes/code/helena-project/tock/arch/cortex-m)
   Compiling cortexm4 v0.1.0 (/Volumes/code/helena-project/tock/arch/cortex-m4)
   Compiling cc26x2 v0.1.0 (/Volumes/code/helena-project/tock/chips/cc26x2)
LLVM ERROR: Global variable '_ZN6cc26x24crt112BASE_VECTORS17hca9d80e98c6172deE' has an invalid section specifier '.vectors': mach-o section specifier requires a segment and section separated by a comma.
error: Could not compile `cc26x2`.
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: Global variable '_ZN6cc26x24crt112BASE_VECTORS17h22806a8481287eb9E' has an invalid section specifier '.vectors': mach-o section specifier requires a segment and section separated by a comma.
error: Could not compile `cc26x2`.

To learn more, run the command again with --verbose.
make: *** [Makefile:55: ci-travis] Error 1
```

Without digging deeply, presumably something just needs to be disabled when running on non-Linux

**Comment by gendx** [comment]
There were two linker issues on OS X:
- Mach-O doesn't like section names like `.vectors`, it requires a pattern `segment,section`. I changed the section name on non-`none` OS to something dummy (I didn't remove the tables, so that syntax/type errors would still be caught on desktop OSes). Maybe the `link_section` attribute could be removed entirely for non-`none`?
- It couldn't find symbols like `_estack`. I restricted the `used` attribute of `BASE_VECTORS` and `IRQS` to the `none` OS, so that the linker just removes these unused tables on OS X.

**Comment by bradjc** [comment]
In general running the tests or doctests is great, but I'm really not excited about all of the `#ifdef`s that have to be added. Even more so that half of them are double negatives. In fact, up until this PR I've always wondered why those existed at all. There isn't a great way to comment what those are doing, and it is very counterintuitive if you aren't deep into how cargo works what those mean or why they are there when compiling an "os".

I played around for a while for a way to avoid having to compile the arch crates or a way to consolidate the hack to make `cargo test` work, but couldn't come up with anything. To me this is broken in cargo, because running tests on a different version of the code than what actually gets used doesn't make sense. Now of course the tests aren't actually testing any of that assembly, but still.

**Comment by gendx** [comment]
I share your concerns regarding `target_os = "none"`, which doesn't look very intuitive. I was trying to follow the current style but here are a few alternatives I can think of:

- Filtering with `target_arch = "foo"` (with the relevant arm/riscv architecture). After all, this is guarding assembly code, which is architecture specific. One caveat could be if we ever have some architecture overlapping between a desktop and a micro-controller, then the tests would compile the assembly instead of the mock (but that may not be problematic then).
- Filtering with `cfg(test)` to enable the mock implementation.
- Filtering with both:
  - if target architecture AND not a test, provide the assembly,
  - if different architecture AND a test, provide the mock,
  - otherwise, don't provide anything, as this isn't expected.
- Filtering with a combination of the above and additionally the `target_os`.

Any thoughts?

**Comment by gendx** [comment]
Friendly bump. Apart from `target_os` (which is already used throughout Tock), do you have any other concerns about this change?

**Comment by bradjc** [comment]
I am opposed to this change. Anyone else supportive?

**Comment by gendx** [comment]
What do you mean by a macro? I'm not sure how a macro in the [common Rust sense](https://doc.rust-lang.org/reference/macros.html) would fit in the syntax here.

A custom feature could be used (as in `cfg(feature = "foo")` - with "foo" a name to be decided, e.g. "mock"), although that would need to be defined in each chip's `Cargo.toml` and probably wouldn't be so intuitive either.

Would `cfg(test)` be clearer?

The main goal of this pull request is to be able to write unit tests in any chip, like in the kernel (e.g. https://github.com/tock/tock/blob/master/kernel/src/common/ring_buffer.rs#L93), or to run tests generated by https://github.com/tock/tock/pull/1410. So marking mock implementations with `cfg(test)` would make sense.

**Comment by alistair23** [comment]
I don't have a great grasp on Rust macros, so it might not be possible here.

`cfg(test)` seems much cleaners, that way it's also explicit why it is there (right now it's not obvious). That is what I meant with replace it with a macro. Basically just replace `target_os` with something that is more descriptive and `cfg(test)` does that.

**Comment by alevy** [comment]
I won't be able to chime in for a few more days. Would appreciate if other @tock/core-wg would take a look since this is a bit controversial.

**Comment by gendx** [comment]
I'm all in to migrate instances of `cfg(target_os = "none")` to `cfg(not(test))` and `cfg(not(target_os = "none"))` to `cfg(test)`. But I want confirmation before making this extra change across Tock's code base.

@bradjc would that be clear enough for you, or do you have other concerns regarding supporting unit tests in the chips?

Of course, the assembly part will never be testable without the actual hardware, but that's not the point of unit tests runable on desktop/laptop/Travis-CI. I think this is really helpful in catching bugs earlier in the dev cycle than after flashing Tock and apps and manually checking that they behave as expected.

Some parts will have to be mocked, but a mock containing `unimplemented` will make sure that the results are not misinterpreted: if the tests actually use the mock, they will fail due to the panic caused by `unimplemented`.

Note that the same concept of mock implementation exists in libtock-rs: https://github.com/tock/libtock-rs/blob/master/src/syscalls_mock.rs

**Comment by alistair23** [comment]
> Of course, the assembly part will never be testable without the actual hardware

Or QEMU :)

**Comment by ppannuto** [comment]
I think we're going to talk about this on the call in a little bit, but I wanted to get some ideas out anyway.

First, I echo the gut check of Brad: a lot of embedded code has historically been a cesspool of `ifdef`s that make it really, really hard to understand what's going on. While it is less bad that this is being proposed only for unit testing (i.e. it should not have an impact for code that will be loaded onto hardware), I start to wonder what unit tests are actually useful for chips in the absence of hardware? I'm afraid that we're going to end up in a situation where we have unit tests that validate the mocked out hardware, but then a kernel that runs the actual hardware implementations, and relatively little coverage of what's actually used.

Now, there _are_ probably parts of the kernel that could be well served with testing, but maybe the approach should be a larger scope? I.e. I have a (long-outdated) branch lying around that looked at supporting a "native" board, that would compile Tock as a linux process. In this there was a "posix chip" that the kernel was running on, but the rest of the kernel was unchanged (well, also posix arch for syscalls). Perhaps the avenue should be a "unit testing chip", or something that keeps this isolated. Right now I see the path forward for this as a pile of `cfg`s getting added to every chip, and that feels like a large addition of code that will never actually run on any chips.

If I'm missing something, one thing that may help would be seeing an example of unit tests isolated to the chips crate that are useful; right now all the mocks are empty stubs (conceptual textual description of what the tests would cover is fine -- no need to implement yet)

**Comment by gendx** [comment]
TockOS's motto is a "**secure** embedded operating system for microcontrollers". I think the security promise would be misleading without at least the possibility of writing unit tests in all components of the code.

Let me give some examples of unit tests in particular for chips, and explain why I think conditional compilation is relevant here.

## 1 What unit tests would be useful?

End-to-end testing of TockOS with a few example apps on real hardware (or qemu, or a Linux target) definitely gives an idea about whether the core logic works. But end-to-end testing also misses a lot of coverage that is easier to catch with unit tests.

### Functional tests

Consider for example the kernel ring buffer (https://github.com/tock/tock/blob/master/kernel/src/common/ring_buffer.rs). There might be an implementation bug that triggers only when the buffer is full, but this condition could be rare enough and the example apps simple enough that this code path wouldn't be triggered. Unit tests however can check if the ring buffer works in these corner cases, and there seemed to be quite a consensus when I added them (https://github.com/tock/tock/pull/1392).

### Tests specific to chips

Another example more specific to the chips folder is whether register mappings are as intended, in particular that gaps between registers are of the right size. This was discussed in https://github.com/tock/tock/pull/1410 and unit tests would be able to check unintended gaps or overlaps between registers.

A last example that comes to mind is `register_bitfields`. For now there is no check that bits indeed fit into the underlying integer type, and it was discussed in https://github.com/tock/tock/pull/1417 that a `u8` was wrongly used instead of a `u32`. As you can see, the first field is already at offset 24 on an 8-bit register! https://github.com/tock/tock/blob/10601d412f34c76c10641af2593635c81b9ff3c7/chips/cc26x2/src/ccfg.rs#L72-L76

This kind of error would be easy to check with unit tests, and I think that not testing it is contrary to Tock's promise of a **secure** embedded OS.

## 2 Conditional compilation

Regarding conditional compilation of mock implementations, I don't really understand the push back against generalizing it. It's already present in Tock, for example I found 26 occurrences of `target_os`:

```bash
$ git grep -n target_os
arch/cortex-m/src/support.rs:3:#[cfg(target_os = "none")]
arch/cortex-m/src/support.rs:12:#[cfg(not(target_os = "none"))]
arch/cortex-m/src/support.rs:16:#[cfg(target_os = "none")]
arch/cortex-m/src/support.rs:23:#[cfg(not(target_os = "none"))]
arch/cortex-m/src/support.rs:27:#[cfg(not(target_os = "none"))]
arch/cortex-m/src/support.rs:35:#[cfg(target_os = "none")]
arch/cortex-m/src/support.rs:50:#[cfg(target_os = "none")]
arch/cortex-m0/src/lib.rs:27:#[cfg(not(target_os = "none"))]
arch/cortex-m0/src/lib.rs:30:#[cfg(target_os = "none")]
arch/cortex-m3/src/lib.rs:31:#[cfg(not(target_os = "none"))]
arch/cortex-m3/src/lib.rs:34:#[cfg(target_os = "none")]
arch/cortex-m3/src/lib.rs:54:#[cfg(not(target_os = "none"))]
arch/cortex-m3/src/lib.rs:57:#[cfg(target_os = "none")]
arch/cortex-m3/src/lib.rs:117:#[cfg(not(target_os = "none"))]
arch/cortex-m3/src/lib.rs:120:#[cfg(target_os = "none")]
arch/cortex-m3/src/lib.rs:150:#[cfg(not(target_os = "none"))]
arch/cortex-m3/src/lib.rs:155:#[cfg(target_os = "none")]
arch/cortex-m4/src/lib.rs:31:#[cfg(not(target_os = "none"))]
arch/cortex-m4/src/lib.rs:34:#[cfg(target_os = "none")]
arch/cortex-m4/src/lib.rs:54:#[cfg(not(target_os = "none"))]
arch/cortex-m4/src/lib.rs:57:#[cfg(target_os = "none")]
arch/cortex-m4/src/lib.rs:117:#[cfg(not(target_os = "none"))]
arch/cortex-m4/src/lib.rs:120:#[cfg(target_os = "none")]
arch/cortex-m4/src/lib.rs:150:#[cfg(not(target_os = "none"))]
arch/cortex-m4/src/lib.rs:155:#[cfg(target_os = "none")]
arch/rv32i/src/support.rs:27:#[cfg(target_os = "none")]
```

If this was really a problem, why keeping these mock implementations which are at the moment confusing and not useful?

I agree that a clearer configuration than `target_os` would be useful (as discussed several comments ago). Additionally, comments in the form of `// Mock implementation for tests on a different architecture (desktop, Travis-CI)` in every occurrence should provide enough context for non-experts reading the code, no? Additionally, leaving the content `unimplemented()` would avoid accidentally using the mock logic.

But rejecting all kinds of ifdefs because they are hard to read sounds a bit extreme too: ifdefs are also a powerful tool which in some cases (like unit testing) can be useful.

**Comment by ppannuto** [comment]
As one of the louder voices in support of the merged functional tests, I think the key distinction that made that an easy win for me was that it was a very "clean" new test -- it modified none of the existing code to operate and the testing code was clearly identifiable as such. That's much less the case here.

With regard to the "existing" conditional compilation, I do not believe that anything actually _uses_ it. All of the `cfg ... ?os` stuff is quite old. It came in from the first major Tock rewrite done by @alevy, and it's been copied around ever since.  I'll speak for myself -- and I strongly suspect @bradjc -- here, but honestly I had never understood its purpose. What I have done is sought to keep it contained until I could figure out what it's doing -- clearly we're at that time.

I _think_ what is further happening here is partially criminally unfortunate timing. In parallel to this discussion, where features probably are the right choice, is [a conversation on tock-dev about the exact scenario where we very much do not want to rely on features](https://groups.google.com/forum/#!topic/tock-dev/S3ncYHyC8fw) (conditional compilation for boards). Having now spent some time to think about this and more importantly to learn how Rust/Cargo runs unit tests, I think the comment made above is the right suggestion: converting to a `cfg(not(test))` for all of the real code, and a `cfg(test)` for where mocks are required. I'm sorry to have been a little thick-headed about this, but every once in a while my roots as a 'knuckle-dragging C programmer' rear their ugly head :)

Still, before moving forward with the labor of cleaning up the (really non-existent) unit testing infrastructure, I'd like to hear more of the @tock/core-wg chime in on their thoughts for the mechanisms for handling unit testing. Either here, or perhaps this is something more efficiently done as the major bullet point for this week's Tock call.

**Comment by niklasad1** [comment]
I'd just want to give you heads up that with additional `dev features` we might end up with https://github.com/rust-lang/cargo/issues/5730, which I think we should be careful about

**Comment by bradjc** [comment]
`cfg(test)` is at least a little more clear as to what the modifier is doing, although it still (I think) raises the question for someone looking at the code as to why it is helpful to test code that isn't being used and not test code that is being used.

More generally, I want to push back whenever it seems we as programmers have to workaround our tools; aren't our tools supposed to be helping us? Is there something we can push for in Cargo or is there anything on the Cargo roadmap that would make this better for us? I would like to see changes suggested to Rust (as we have tried to do with tracking `unsafe` in dependencies) and some sort of workaround (maybe a script) so that we can push all of the complexity to tools, and not burden programmers with fixing a limitation with how `cargo test` works.

**Comment by gendx** [comment]
The reason why some mocks are needed to be able to run tests on a "desktop" platform seems more fundamental than tooling. I don't think it's a limitation of `cargo test` but more a fundamental essence of embedded code.

- Given that we're talking about embedded code for specific architectures, at the end of the day we need some **architecture-specific assembly code**, which can be compiled and run only on that architecture (or an emulator of it). I don't think that modifying Cargo can help with that. Nor that integrating qemu into `cargo test` would be a reasonable way forward (how does one run a snippet of 3 asm instructions in a middle of a program with qemu anyway?).

- We also need specific linker scripts to layout IRQ vectors, flash & RAM memory for both kernel & apps, etc. These **custom linker scripts don't apply to unit tests** (where the linking layout is just e.g. a regular ELF with functions to tests). And for some reason OSX doesn't like section names like ".vectors". I don't think updating the Rust tooling can change that. Nor that updating clang/llvm or OSX itself to accept them is a suitable way forward.

That said, these workarounds may reveal ways in which the current design could be improved. For example, architecture-specific assembly could be moved to a separate module if it makes sense (`#[feature(asm)]` would only be allowed in this module, as opposed to scattered in `archs/`, `chips/`, etc.). Likewise, linker-related components could be centralized to a single file if that's possible and clearer. Such self-contained modules wouldn't have the "desktop" unit tests, but the idea is to contain the "less tested" part to small code that can reasonably be manually reviewed (similarly to `unsafe` blocks which should be limited to a small amount of manually auditable code).

Of course, testing assembly also makes sense (but it's done by flashing Tock on real boards) ; same for the layout, it's tested by running it on boards (although this doesn't always seem up-to-date, e.g. https://github.com/tock/tock/pull/1418 and https://github.com/tock/libtock-rs/pull/98).

**Comment by gendx** [comment]
Regarding features, I agree that we should be careful with those.

- See the other discussions regarding feature propagation in dependencies, it's not always obvious to get right.
- If a feature is really here to separate between test/non-test environments, what if someone mistakenly enables the test feature in production build? Would it be caught?

I think that `cfg(test)` provides a much more natural boundary. With Cargo, you can't really enable the `test` config apart from running `cargo test`, which wouldn't build a binary with the custom linker scripts, but just a unit test binary.

**Comment by ppannuto** [comment]
@bradjc just wanted to bubble this up again to see where your head is at currently regarding `cfg(test)`

**Comment by gendx** [comment]
Friendly ping. Could we discuss this on the Tock call this week?

**Comment by gendx** [comment]
After taking a closer look, it turns out that the `test` configuration is not passed to dependencies by Cargo: https://github.com/rust-lang/rust/issues/59168

Because Tock's code is heavily split into multiple libraries, we cannot rely on `cfg(test)`. For example, `arch/cortex-m/src/support.rs` defines some functions using assembly such as `nop` or `wfi`, for which a mock is necessary. But these functions are used by dependent libraries such as `chips/stm32f4xx`, which need to resolve an implementation.

A possibility would be to manually define a `test` feature and pass it through dependencies, but this seems quite complicated, brittle and unnatural.

So the alternatives are the current `target_os = "none"` filtering or `target_arch = "arm"`. The latter is natural because assembly really is architecture-dependent. The drawback is that in principle one could run the tests on a "desktop" environment based on ARM, in which case this could break if the ARM flavor is somehow incompatible. But I don't see any better solution (aside from combining both `target_os` and `target_arch`).

**Comment by gendx** [comment]
@bradjc Does this look good to you?

**Comment by bradjc** [comment]
I guess I won't stand in the way, but I still believe this is a step in the wrong direction and too invasive just to compile tests. A simple(-ish) script could check for gaps in registers until the testing situation in cargo is improved.

**Comment by gendx** [comment]
I'm really wondering how "simple" and maintainable such a script would be, compared to the current solution. The current solution leverages the Rust compiler to parse the code, check the types, etc. I'm not sure how you would achieve the same result with the same level of reliability with a simpler script.

Apart from that, it seems that all archs have a similar set of specific functions, so maybe a common trait (or a module) would make sense to better encapsulate asm-specific code, and to provide a mock implementation of the trait.

See for example how it is done for syscalls in `libtock-rs` https://github.com/tock/libtock-rs/tree/master/src/syscalls:

- Conditional import of the code: https://github.com/tock/libtock-rs/blob/master/src/syscalls/mod.rs#L1-L7
- ARM implementation: https://github.com/tock/libtock-rs/blob/master/src/syscalls/platform_arm.rs
- Mock implementation: https://github.com/tock/libtock-rs/blob/master/src/syscalls/platform_mock.rs

**Comment by alevy** [comment]
@gendx that's true! For the most part arch crates contain similar functionality, and a single (or a handful) of conditional imports in each chip might be more concise...

I'm really not as offended as @bradjc about the conditional compilation for this specific purpose. I think the benefits are worth it---maybe the register alignment could be tested another way, but this would (a) allow chips to have other, functional tests written and run on Travis as well, and (b) would make it reasonable to run tests for all crates on Travis--we can already run tests for the kernel and capsules, the kernel tests even pass (capsules have doc tests that don't pass).

In the long run, I think having a common way (`cargo test`) to run tests, and actually run them, will mean that we can start requiring tests for important changes, and is ultimately worth some #define grossness (especially if there is maybe a path to cleaning it up)

**Comment by gendx** [comment]
I definitely agree with @alevy.

In my opinion, the register alignment tests are only one possible set of unit tests in boards (although it already affects a large chunk of the boards' code), but other functional unit tests for complex features would definitely be worth it (like the tests that were added to the ring buffer in the kernel for example).

**Comment by ppannuto** [comment]
I sit more in the middle of @bradjc and @alevy: I'm strongly in favor of additional testing and automation. But the necessary framework stuff here is particularly dense and non-intuitive. If this were just in support of running test on the chips crate -- which frankly is a somewhat odd idea (what chip-specific tests can you really run on x86..?) -- I think I would be opposed.

However, I'm more swayed by the argument of running tests on crates that depend on chips. I think it's an unfortunate artifact of the rust unit testing ecosystem that dependent crates limit the ability to do unit tests on units that doesn't actually use the dependency, but that's an issue that we won't be fixing.

My disposition is uneasily in favor of merging.

**Comment by gendx** [comment]
So, is this PR ready for merging or not?

**Comment by gendx** [comment]
@bradjc @alevy @ppannuto anything more to add or is it ready to merge?

**Comment by ppannuto** [comment]
We did talk about this during the Tock call a little over a week ago - the consensus was mixed and the action item was for the rest of the @tock/core-wg to review this PR and add their feedback on GitHub. Hopefully this tag can prompt that a bit. I suspect we're sneaking into the holiday distractions time of year, so maybe still high-latency, but hopefully more folks will be able to chime in with concrete opinions. We need some more voices here.

**Comment by gendx** [comment]
Thanks for the update. As another example where unit tests are useful in `archs/`, see https://github.com/tock/tock/pull/1511#discussion_r359237926.

**Pull request merged**
