### PR TITLE
Add Leon Schuermann to the core developers list.

### PR DESCRIPTION
**Pull request by phil-levis**
### Pull Request Overview

This pull request adds Leon as a member of the core WG. I think he has made foundational contributions to Tock, particularly in his leadership in Tock 2.0. 

This PR is following the membership policy in https://github.com/tock/tock/blob/master/doc/wg/core/README.md

### Testing Strategy

No testing.

### TODO or Help Wanted

Discussion.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by jrvanwhy** [comment]
Leon has made substantial contributions to Tock. His contributions are carefully thought out, and consider Tock's many use cases.

**Review by jrvanwhy — APPROVED** [review]

**Review by brghena — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]

**Review by alevy — APPROVED** [review]

**Review by bradjc — APPROVED** [review]

**Comment by bradjc** [comment]
I think we just need Leon to approve this :)

**Review by lschuermann — APPROVED** [review]
Contributing to and working on Tock is a fun. I'd be delighted to join this team!

**Comment by jrvanwhy** [comment]
I concur with Brad's assessment, and Leon just approved.

**Pull request merged**
