### PR TITLE
RISC-V: OpenTitan Preparation

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This PR does some preperation for adding OpenTitan support (see https://github.com/tock/tock/pull/1460).

This PR does the following:

- Fix the linker script for RISC-V
- Moves the PLIC to the chips directory

> Although the PLIC is specified in the RISC-V ISA, the ISA does not
> specify how the registers should be mapped. Due to this each
> implementation can have it's own register layout. To allow other chips
> to be added in the future more the PLIC from arch to chips.

- Converts the RISC-V Machine timer to allow setting a custom base address.

### Testing Strategy

Runtime tested on the sifive_e machine on QEMU and runtime tested on the OT port.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make formatall`.

### CODE REVIEW

**Comment by alevy** [comment]
This seems reasonable to me, but would be better to have someone more familiar with the RISC-V port sign-off on the changes—-particularly I guess moving the PLIC to the chip crate.

**Comment by DieracDelta** [comment]
Could we use generics here?

To clarify, my current understanding is that the way you handle interrupts with the PLIC still remains as described with by the ISA and only the memory map is the differing. Is this correct @alistair23?

Would it make sense to define a PLIC trait in the arch crate that basically contains a set of getters and setters that you could implement on a per-chip basis, then use a generic arch-specific implementation of the claim/complete PLIC functionality over that trait. Does that make sense? It would save us some copy and paste between different chips.

**Comment by alistair23** [comment]
Right now the two implementations aren't exactly the same. This is mostly related to registers being `Read`/`ReadWrite` between the two.

I suspect that we can work around this for a better long term solution. Assuming there aren't any other major differences between implementations I agree that we can use a more generic solution. Your idea of traits and getters/setters sounds like a good idea.

It sounds like RISC-V interrupts overall need to be improved (https://github.com/tock/tock/issues/1472) so a big update is probably required.

**Comment by alistair23** [comment]
Is this ok to merge now?

**Comment by phil-levis-google** [comment]
Yes -- I think that if you have an approve from Brad and no change requests, you can merge it.

**Comment by alistair23** [comment]
I don't have write permissions, so I can't merge it.

**Comment by alevy** [comment]
@alistair23 Just need to resolve the merge conflict (.lock files are now deleted)

**Pull request merged**
