### PR TITLE
kernel: don't silently drop IPC tasks

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

kernel: don't silently drop IPC tasks

I think #931 got merged prematurely without fixing this.

### Documentation Updated

- [x] Kernel: Updated the relevant files in `/docs`, or no updates are required.
- [x] Userland: Added/updated the application README, if needed.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
The kernel doesn't get any bigger with this?

```
 $ ⮀git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 ~ ⮁ git ⮁ tock ⮁ boards ⮀ hail ⮀                                                                ⮂ master ⮂ d-172-25…
 $ ⮀git pull
Already up to date.
 ~ ⮁ git ⮁ tock ⮁ boards ⮀ hail ⮀                                                                ⮂ master ⮂ d-172-25…
 $ ⮀make
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling hail v0.1.0 (file:///Users/bradjc/git/tock/boards/hail)
    Finished release [optimized + debuginfo] target(s) in 17.43 secs
   text	   data	    bss	    dec	    hex	filename
  84692	   3628	  62204	 150524	  24bfc	target/thumbv7em-none-eabi/release/hail
 ~ ⮁ git ⮁ tock ⮁ boards ⮀ hail ⮀                                                                ⮂ master ⮂ d-172-25…
 $ ⮀git pr 946
From github.com:helena-project/tock
 * [new ref]           refs/pull/946/head -> pr/946
Switched to branch 'pr/946'
 ~ ⮁ git ⮁ tock ⮁ boards ⮀ hail ⮀                                                                ⮂ pr/946 ⮂ d-172-25…
 $ ⮀make
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling hail v0.1.0 (file:///Users/bradjc/git/tock/boards/hail)
    Finished release [optimized + debuginfo] target(s) in 16.56 secs
   text	   data	    bss	    dec	    hex	filename
  84692	   3628	  62204	 150524	  24bfc	target/thumbv7em-none-eabi/release/hail
```

Does that mean this doesn't actually do anything?

**Comment by ppannuto** [comment]
Not in a release build:

"Unlike assert!, debug_assert! statements are only enabled in non optimized
builds by default."

https://doc.rust-lang.org/1.7.0/std/macro.debug_assert!.html

**Comment by bradjc** [comment]
But `make debug` doesn't work, and I don't think anyone does their testing with it? I guess I'm not seeing how this check helps.

**Comment by ppannuto** [comment]
Didn't really internalize that `dev` build wasn't working. Switched to normal assert.

**Comment by niklasad1** [comment]
I would suggest to improve `debug!` with different logging levels similar to RUST_LOG (https://docs.rs/log/0.4.1/log/) instead because the ordinary assert will panic!

**Pull request merged**
