### PR TITLE
boards/apollo3: lora_things_plus: Expose SPI to userspace for SX1262

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This builds on https://github.com/tock/tock/pull/3324 and adds support to communicate with the SX1262 LoRa chip via SPI.

### Testing Strategy

Communicating with SX1262

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
Is the actual communication code in userspace?

**Review by hudson-ayers — APPROVED** [review]

**Comment by alistair23** [comment]
The communication code is in userspace. I'm working on getting the [Semtech library](https://github.com/Lora-net/LoRaMac-node/) working. I'm hoping LoRa is slow enough that we don't hit timing issues

**Review by twilfredo — APPROVED** [review]
cool!

**Review by bradjc — APPROVED** [review]
Approved with a title change

**Comment by alistair23** [comment]
Ping!

**Review by lschuermann — APPROVED** [review]
bors r+

**Pull request merged**
