### PR TITLE
STM32f4xx: Properly support 4MHz SPI rate

### PR DESCRIPTION
**Pull request by LeonMatthesKDAB**
Previously, setting 4MHz as the SPI rate was only supported in the
rate setter, but not the getter.

### Pull Request Overview

This pull request adds support for 4MHz in the spi's set_rate and get_rate functions.
Previously, it was only supported in the set_rate function, but also wasn't documented!

### Testing Strategy

**I am currently not able to test this, I just stumbled across it whilst reading the SPI code.**

### Documentation Updated

- No updates required

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — COMMENTED** [review]
This looks fine but it would be nice if someone can test it, the comments in the original code make me slightly uneasy that this might not work for some reason.

**Comment by alexandruradovici** [comment]
I'll try and test it on an STM32F412g Discovery and an SPI display.

**Review by bradjc — APPROVED** [review]
This looks fine to me. I don't see how this would make anything _worse_, at least.

**Comment by hudson-ayers** [comment]
Fair enough.

bors r+

**Pull request merged**
