### PR TITLE
process_console: fix char deletion handlers

### PR DESCRIPTION
**Pull request by mattmart3**
### Pull Request Overview

This pull request introduces two fixes to the deletion handlers of the process console capsule. Both cases ended up to panic invocations, due to attempts of deleting a character on wrong buffer indexes.  

### Testing Strategy

Tested with a nucelo-f439zi by using the process console with default parameters. The issues were no more reproducible after the respective fixes.

### TODO or Help Wanted

Not sure I covered all cases during tests. If anyone could point out any critical case I could try to cover it.

### Documentation Updated

- [x] No updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
The test script is here: https://github.com/tock/tock/blob/master/tools/check_process_console.py

**Comment by bradjc** [comment]
Can you describe what it takes to get the fault to happen?

**Comment by matteomartelli** [comment]
Following the test sequences to reproduce the issues before my changes:

### Test 1 - Del EscKey on first character of the history cmd

input key strokes:
```
testone<CR><Up><Left><Left><Left><Left><Left><Left><Left><Del>
```

output:
```
Initialization complete. Entering main loop
tock$ testone
Valid commands are: help status list stop start fault boot terminate process kernel reset panic console-start console-stop
tock$ testone
panicked at capsules/core/src/process_console.rs:1307:68:
                                                         attempt to subtract with overflow
        Kernel version release-2.1-2537-g448f54d57

---| No debug queue found. You can set it with the DebugQueue component.

---| Cortex-M Fault Status |---
No Cortex-M faults detected.

---| App Status |---
```


### Test 2 - Backspace on last character of the history cmd

input key strokes:
```
testtwo<CR><Up><BS>
```

output:
```
Initialization complete. Entering main loop
tock$ testtwo
Valid commands are: help status list stop start fault boot terminate process kernel reset panic console-start console-stop
tock$ testtwo
panicked at capsules/core/src/process_console.rs:312:50:
                                                        attempt to subtract with overflow
        Kernel version release-2.1-2537-g448f54d57

---| No debug queue found. You can set it with the DebugQueue component.

---| Cortex-M Fault Status |---
No Cortex-M faults detected.

---| App Status |---
```

After my changes I cannot reproduce the issues anymore.
I also added some additional tests in `tools/check_process_console.py` which in fact do not pass without my commits, but pass after applying my changes. All the other tests pass as well.

Note: I executed the tests (both manual and automated) with a baud rate of 9600 to avoid overruns, however this should not make any difference for this PR since it fixes two bugs in the logic of the process_console.

**Review by bradjc — APPROVED** [review]
Thank you for updating the test script. I can't reproduce this issue with on mac with tockloader, but the changes don't seem to break anything for me either.

**Pull request merged**
