### PR TITLE
libraries/tock-register-interface: Add `set` and `clear` methods for `Field<T, R>`

### PR DESCRIPTION
**Pull request by rajivr**
For manipulating single bit register field. Complements already existing `val` method.

### CODE REVIEW

**Comment by rajivr** [comment]
> I think a change like this has come up before, and we weren't sure it made sense that `set()` would set _all_ bits or just the first bit (same with clear).

Currently `::SET` and `::CLEAR` manipulate single bit and `.val(...)` is used to manipulate multiple bits. 

So, I feel `.set()` and `.clear()` should be used for changing single bit registers. Once there is a consensus on this, I'll update this PR with a README example.

**Comment by ppannuto** [comment]
Is there a way to enforce that .set() and .clear() can only be called on
single bit registers? IIRC, the issue the last time this came up was what
do to if someone called .set() on a multi-bit register

**Comment by rajivr** [comment]
> Is there a way to enforce that .set() and .clear() can only be called on single bit registers? IIRC, the issue the last time this came up was what do to if someone called .set() on a multi-bit register

AFAICT, no. We could mark it `unsafe` (and add `// Safety`) documentation.

BTW, having this API is turning out to be quite useful in refactoring chip crate.

**Comment by bradjc** [comment]
Is there an easy example available? It seems like a register field that has a single bit that can be set should also have a name for that bit, and then `field::BIT::SET` would work.

**Comment by rajivr** [comment]
Sure! Suppose we have reset bit for a peripherals spread across different registers, and we want to provide a "reset" interface, we would do something as below.

The same result can be accomplished by putting the side effect in every match arm (and using `field::BIT::SET` and `field::BIT::CLEAR`).

However by having `.set()` and `.clear()`, we can build up a sum type (`PERIPHERIALRST`, whose variants `PERIPHERALRST1` and `PERIPHERALRST2` would carry `Field<u32, R>`) that captures the side effect. We can then deal with the side effect in one place in the function or pass them around if required.

Basically I want to be able to build data structures of register level side effects and then uniformly deal with those data structures.

```
pub unsafe fn reset_peripheral(&self, peripheral: Peripheral) {
    let peripheralrst = match peripheral {
        Peripheral::UART0 => PERIPHERALRST::PERIPHERALRST1(PERIPHERALRST1::UART0RST),
        Peripheral::UART1 => PERIPHERALRST::PERIPHERALRST1(PERIPHERALRST1::UART1RST),
        Peripheral::UART2 => PERIPHERALRST::PERIPHERALRST1(PERIPHERALRST1::UART2RST),
	    
        Peripheral::SPI0 => PERIPHERALRST::PERIPHERALRST2(PERIPHERALRST2::SPI0RST),
        Peripheral::SPI1 => PERIPHERALRST::PERIPHERALRST2(PERIPHERALRST2::SPI1RST),
        Peripheral::SPI2 => PERIPHERALRST::PERIPHERALRST2(PERIPHERALRST2::SPI2RST),
    };

    match peripheralrst {
        PERIPHERALRST::PERIPHERALRST1(reg_field) => {
            // generate reset signal
            self.registers.peripheralrst1.modify(reg_field.set());

            // release reset signal
            self.registers.peripheralrst1.modify(reg_field.clear());
        },
        PERIPHERALRST::PERIPHERALRST2(reg_field) => {
            // generate reset signal
            self.registers.peripheralrst2.modify(reg_field.set());

            // release reset signal
            self.registers.peripheralrst2.modify(reg_field.clear());
        }
    }
}
```

**Comment by rajivr** [comment]
It looks like I should be able to use `FieldValue` instead of `Field` to accomplish what I was looking to do with `.set()` and `.clear()` methods. Lets put this PR on hold for a few days. I'll close it in case its no longer required.

**Comment by rajivr** [comment]
Closing in favor of #1371 

Also thank you for the push back on this PR. I would not have discovered #1371 approach if not for the push back! :-)

**Pull request closed without merging**
