### PR TITLE
Move boards that have large main stack frames to get_peripherals

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

Found using `make allstack`.

### Testing Strategy

compile

### TODO or Help Wanted

The RPi boards still have large main stack frames (although they are now the second largest).

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]

**Review by phil-levis — APPROVED** [review]

**Review by alistair23 — DISMISSED** [review]

**Comment by phil-levis** [comment]
@bradjc -- Can you fix the CI checks?

**Comment by bradjc** [comment]
done

**Review by lschuermann — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]
bors r+

**Pull request merged**
