### PR TITLE
Undo making the .apps section have content

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

I noticed that using `make program` to load a kernel on to Hail caused my applications to be "erased". I tracked it back to these commits, which cause the `.apps` section from the ELF to be included in the `.bin` file, and that causes the .bin file to be long enough to overwrite the first four bytes of the first app installed, effectively uninstalling all apps.

These commits were added in #1220.

Adding `--remove-section=.apps` to the call to objcopy in Makefile.common also "fixes" this issue, but that feels like a hack. However, I'm not sure what the best route to take is. I don't really understand why the kernel needs to be compiled with four bytes of 0 for apps.

Before:

```
ls target/thumbv7em-none-eabi/release/
total 95624
drwxr-xr-x   4 bradjc  staff   128B May 15 19:46 build
drwxr-xr-x  98 bradjc  staff   3.1K Jun  4 16:17 deps
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 examples
-rwxr-xr-x   2 bradjc  staff   2.5M Jun  4 16:17 hail
-rwxr-xr-x   1 bradjc  staff   128K Jun  4 16:17 hail.bin
-rw-r--r--   1 bradjc  staff   9.7K May 15 19:47 hail.d
-rwxr-xr-x   1 bradjc  staff   2.5M Jun  4 16:17 hail.elf
-rw-r--r--   1 bradjc  staff    41M May 15 19:56 hail.lst
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 incremental
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 native
```

After:

```
ls target/thumbv7em-none-eabi/release/
total 95536
drwxr-xr-x   4 bradjc  staff   128B May 15 19:46 build
drwxr-xr-x  98 bradjc  staff   3.1K Jun  4 16:37 deps
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 examples
-rwxr-xr-x   2 bradjc  staff   2.5M Jun  4 16:37 hail
-rwxr-xr-x   1 bradjc  staff    90K Jun  4 16:37 hail.bin
-rw-r--r--   1 bradjc  staff   9.7K May 15 19:47 hail.d
-rwxr-xr-x   1 bradjc  staff   2.5M Jun  4 16:37 hail.elf
-rw-r--r--   1 bradjc  staff    41M May 15 19:56 hail.lst
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 incremental
drwxr-xr-x   2 bradjc  staff    64B Dec  5 15:00 native
```

### Testing Strategy

This pull request was tested by verifying that `make program` on Hail continues to run pre-existing applications.

### TODO or Help Wanted

Is this the way we want to fix this issue?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by rajivr** [comment]
We need this to order to build a single image with both kernel and apps on STM32 platform by doing something like,

```
arm-none-eabi-objcopy --update-section .apps=$(APP) $(KERNEL) $(KERNEL_WITH_APP)
```

AFAICT, this would be needed for any platform that doesn't support Tockloader.

**Comment by bradjc** [comment]
There must be some other way that doesn't break our existing workflow?

**Comment by rajivr** [comment]
I've never used Tock on a board that supports Tockloader, so I am not familiar with details of the workflow using tockloader.

Since this seems to breaking for a number of users in the community, we need to fix it. Personally I am okay with a _hack_.

Rather than removing `LONG(0)` can we just comment it out with saying this is needed for boards that don't support tockloader?

Then for boards that don't support Tockloader can uncomment it out in their own patch overlay when integrating user-space apps.

**Comment by bradjc** [comment]
I think we should add tockloader support for the nucleo boards.

Do you happen to know if https://github.com/ntfreak/openocd/blob/master/tcl/board/st_nucleo_f4.cfg works for openocd?

**Comment by bradjc** [comment]
If everything is easy then installing tockloader from this branch should work: https://github.com/tock/tockloader/compare/nucleo

Then installing an app looks like:

    tockloader install --board nucleo --openocd

**Comment by rajivr** [comment]
I've not looked into tockloader recently, but if I recall from our previous [discussion](https://github.com/tock/tock/pull/1220#discussion_r239302338) on STM32F446RE, since there are varying sector/page sizes, it would have take some effort to make tockloader work.

**Comment by bradjc** [comment]
Ah yes I remember that now. Luckily that only applies to using the serial bootloader interface with Tockloader. To remedy the current situation I'm proposing using tockloader essentially as an openocd wrapper...and letting openocd worry about page sizes and all of that.

**Comment by bradjc** [comment]
Let me push this again. Adding the zeros to the apps section causes flashing the kernel on at least the imix and hail boards to erase all apps. This PR gets us back to normal, which makes working on Tock _much_ more pleasant.

As for why the section was added, that could be resolved with some sort of script that pads and concatenate binaries, or by flashing apps with openocd to the correct address, or just by using tockloader. A version of tockloader that _might_ work is in the `nucleo` branch. I don't have a board so I can't test it.

**Comment by rajivr** [comment]
@bradjc Sorry, I've not been able to test your tockloader openocd nucleo code. I might also not be able to get to it in near term. Right now I am bit tied up with Rust futures and Tock userland.

In our use-case, we don't use tockloader as a way to integrate user-space apps. We use monolithic image with A/B update. 

If possible I would request that we leave a comment somewhere for the need to have `LONG(0)` for boards that don't support Tockloader workflow.

**Comment by ppannuto** [comment]
Okay, so I played around with this a bit, and I believe the magic is that you have to convert the `.apps` section from a `NOBITS` (which is what it's marked as without the `LONG(0)`) to a `PROGBITS` section before doing the copy, in particular, running

    arm-none-eabi-objcopy --rename-section .apps=.apps,alloc,readonly,load test.elf

before running objcopy a second time to `--update-section` seems to do the right thing [the key is the addition of `load`]. I think this should be the best of both worlds, allowing us to eliminate the `LONG(0)` and still allowing the creation of a single image.

@rajivr can you confirm that running the above command before concatenating fixes for you?

**Comment by rajivr** [comment]
Thanks @ppannuto. This seems to work. However I am getting

```
warning: allocated section `.apps' not in segment
```
when I do `--update-section` during build and also when I open the elf file in gdb. Following are snippets on how the warning looks.

During build

```
[...]

    Finished dev [optimized + debuginfo] target(s) in 0.01s
arm-none-eabi-objcopy --rename-section .apps=.apps,alloc,readonly,load /home/tos-user/work/src/tock/boards/nucleo_f446re/target/thumbv7em-none-eabi/debug/nucleo_f446re
arm-none-eabi-objcopy --update-section .apps=../../../app0-async-await/app/target/tab/app/cortex-m4.tbf /home/tos-user/work/src/tock/boards/nucleo_f446re/target/thumbv7em-none-eabi/debug/nucleo_f446re /home/tos-user/work/src/tock/boards/nucleo_f446re/target/thumbv7em-none-eabi/debug/nucleo_f446re-app.elf
arm-none-eabi-objcopy: /home/tos-user/work/src/tock/boards/nucleo_f446re/target/thumbv7em-none-eabi/debug/nucleo_f446re-app.elf: warning: allocated section `.apps' not in segment
```

In gdb.

```
Reading symbols from target/thumbv7em-none-eabi/debug/nucleo_f446re-app.elf...

warning: Loadable section ".apps" outside of ELF segments
>>>
```

**Comment by ppannuto** [comment]
Okay, so, after learning about _segments_ and how they differ from _sections_ in ELF, I'm back with a new solution. This is a compromise point that effectively adds the `LONG(0)` to the `main.rs` of the nucleo board. It should allow the nucleo workflow to remain unchanged (I've validated that the resulting elf is the same [well, strictly the same would be a `u32` rather than a `u8`, but the section gets replaced anyway]) while not affecting the other Tock platforms.

**Comment by rajivr** [comment]
Thanks @ppannuto.

This seems to work well. I tested it on Nucleo-446RE. Could you also please make the changes to `boards/nucleo_f446re`?

**Comment by ppannuto** [comment]
👍 , updated to do both nucleo boards

**Comment by bradjc** [comment]
Merge?

**Pull request merged**
