### PR TITLE
Move userland to libtock-c

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request removes the userland folder from the tock kernel repository and updates various documentation to point to libtock-c.

My major concern with this was that it makes it harder for new users to get started. To remedy this, tockloader 1.0 adds a _very_ basic app store, so installing an app is as easy as `tockloader install blink`.

### Testing Strategy

n/a

### TODO or Help Wanted

- Some documentation in /docs needs to be moved to libtock-c. I don't want to do that until this is merged so that the commit history in libtock-c continues to match this repository. But I promise to do it.
- What should we do with the tutorials? I could see them moving to libtock-c as they are all userland specific (and use c).
- The courses are probably the main issue. The apps won't compile because userland isn't there. 

### Documentation Updated

- [ ] Kernel: Updated the relevant files in `/docs`, or no updates are required.
- [x] Userland: Added/updated the application README, if needed. ha

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
> The courses are probably the main issue. The apps won't compile because
userland isn't there.

As we're getting near a new cycle of courses, I really think it's fine to
update the beginnings to say: "This is an older course, and not everything
may align with modern Tock. To try out this course, please first `git
checkout courses-sosp17`". It would be more an issue if we had *no*
courses, but at most that'll only be the case for a month or few until the
new courses are ready

**Comment by brghena** [comment]
What is the benefit of moving userland to its own repo?

On the con list, it makes starting out with Tock and loading applications more difficult and more confusing (you have to find and clone an extra repository).

What are the pros? I don't think it will reduce the size of the repo when cloning since it's still in the history, right? I guess it also ensures that there are no dependencies between userland and the kernel, but I don't think we've really had that problem in over a year (barring `Makefile-app` which was an intentional kludge).

**Comment by bradjc** [comment]
Well starting out is now `tockloader install blink` (and we can add any app) to get an app running. That is hopefully easier, and if someone is coming from the rust world they don't need to worry about compiling c.

Also,
- it puts c on par with our rust userland, which isn't in the repo
- code reviews and travis can be done separately
- it helps emphasize the interface and abstraction between the kernel and userland

These are pretty compelling to me, but yeah I don't have a clear technical reason. It seems like it is time to graduate userland to its own thing, as any os would likely do.

**Comment by alevy** [comment]
I think we can work on `tockloader` to be a more general-purpose "app store" fairly simply. For example, if it was able to take, as an argument for the TAB file, an file path _or_ a URL, it would be fairly trivial to have:

```
tockloader install https://apps.tockos.org/examples/[some app currently in userland]
```

and we could fairly trivially setup travis to always publish all compiled example apps there. Then we wouldn't have to special-case the `blink` app.

Anyone could publish their app anywhere on the web.

But.... that's an issue for a different repository :)

**Comment by bradjc** [comment]
> Then we wouldn't have to special-case the blink app.

The blink app isn't special cased, but the URL is. Any app here can be installed that way: https://github.com/tock/tock-www/tree/master/assets/tabs

But yeah I agree specifying a full URL should be supported.

**Comment by bradjc** [comment]
Let's do last call, but not super urgently as there is fixup that has to be done after this is merged.

**Pull request merged**
