### PR TITLE
Optional cell enhancements

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

This pull request adds some additional methods to `OptionalCell`s that will be needed.

### Testing Strategy

Compiling.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by alevy** [comment]
> Are these all of the methods that are needed? Or are there more?

There are probably more. It wouldn't be _bad_ to have more functionality implemented, except of course that in the case of safety-sensitive code, it's never great to have functionality that's not really used (cause bad bugs are less likely to be caught).

I don't think _adding_ functions has the same kind of affect on backwards stability as _changing_ existing functions, and so don't think we should block on _finishing_ the API.

> Should all of the Cell types have a relatively uniform [...] API?

No. Different "cell" types are pretty semantically different, so I don't think it makes a ton of sense to combine their APIs

**Comment by ppannuto** [comment]
Good call on both. Updated.

**Comment by ppannuto** [comment]
I don't think so. A TakeCell holds a `T`, and OptionalCell holds an `Option<T>`

**Comment by ppannuto** [comment]
@phil-levis Do you have any remaining issues with this PR? I can start patching up the other OptionalCell PRs once this goes through.

**Comment by bradjc** [comment]
@phil-levis

**Pull request merged**
