### PR TITLE
Fix secondary alarm from firing immediately during alarm callback

### PR DESCRIPTION
**Pull request by jettr**
If you have two alarms and one sets the other in its callback, and the
second alarm is later in the linked list of virtual alarms, then the
second alarm callback will fire immediately.

### Pull Request Overview

We need get the latest "now" when comparing the reference time while
going through the list of virtual alarms, otherwise the assumption
that reference is always in the past breaks down and falsely
triggers alarms set during previous alarms callback.

### Testing Strategy

-  [x] Tested on real device that was exibiting this incorrect behavior
-  [x] Added unit test that verifes new behavior (failed without new change in this PR)

### Documentation Updated

- [x] None

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by phil-levis — APPROVED** [review]
Looks good. Makes sense. Nice  catch!

**Review by bradjc — APPROVED** [review]

**Comment by bradjc** [comment]
This seems like a bug fix we can merge for rc1.

**Review by ppannuto — APPROVED** [review]
+1 for including in 2.1 release

**Pull request merged**
