### PR TITLE
boards: update `let _` syntax

### PR DESCRIPTION
**Pull request by twilfredo**
### Pull Request Overview

Since rust 1.59, we can simplify the use of an unused return value from `let _ = bar()` to just `_ = bar()`.

### Testing Strategy

Compiling each target

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]
This looks fine to me, I honestly don't really have a preference between the two different approaches.

**Review by lschuermann — COMMENTED** [review]
I don't feel strongly about this. On the one hand I think forcefully changing this doesn't give us any advantage whatsoever and actually prevents us from using code outside of the context of the project on older Rust compiler versions. On the other hand, we are happily taking advantage of newly introduced `rustc` features elsewhere without worrying about this. So I'm indifferent.

**Comment by bradjc** [comment]
Does this feature have a name?

**Comment by twilfredo** [comment]
> Does this feature have a name?

Think it's just called `Ignored pattern binding`, the operator that is. Not sure if there a 'feature' name for it.

**Comment by ppannuto** [comment]
I don't have a strong feeling one way or the other on this, but is there a clippy lint that will ensure we are consistent with this?

**Comment by bradjc** [comment]
I don't understand why rust needs two nearly identical ways to do the same thing. If we can add a clippy lint to effectively enforce this (as we do with something like not explicitly calling `return` at the end of a function), which suggests this is or would become Rust Standard Style TM, then let's make the change. Otherwise, I'm opposed to this PR.

**Review by bradjc — CHANGES_REQUESTED** [review]
Requesting clippy lint so we have a goal we are working towards rather than arbitrary code syntax changes.

**Comment by twilfredo** [comment]
I couldn't find any clippy options for this, does anyone know if there are any? if not, it's probably best to just close this one off.

**Comment by hudson-ayers** [comment]
I don't think such a lint exists, so I am going to close this for now. If a lint is created that would let us favor one approach or the other and enforce that throughout the codebase, we can revisit

**Pull request closed without merging**
