### PR TITLE
Tock 2.0: buzzer driver update

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request updates the buzzer to the Tock 2.0 driver API.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by phil-levis — APPROVED** [review]

**Comment by alexandruradovici** [comment]
Resolved

**Pull request merged**
