### PR TITLE
Led HIL for LedMarix

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request adds the ability to use single LEDs from the LedMatrixDriver with the Led HIL.

This is useful for drivers that want to control LEDs that are within an Led matrix.

### Testing Strategy

This pull request was tested using a micro:bit v2 board.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — DISMISSED** [review]

**Review by hudson-ayers — DISMISSED** [review]

**Review by lschuermann — APPROVED** [review]
Looks good in general, with two minor comments:

- it might make sense to use the introduced helper methods not only in the `LedMatrixLed` but also in the `kernel::Driver` implementation, to avoid duplicating the logic there.
- I'm entirely convinced we'd need a macro in `components` to construct an `LedMatrixLed` (since it's just a wrapper around a static-init'ed `LedMatrixLed::new`), but I'm also not opposed to it.

**Review by alistair23 — DISMISSED** [review]

**Comment by hudson-ayers** [comment]
> * I'm not entirely convinced we'd need a macro in `components` to construct an `LedMatrixLed` (since it's just a wrapper around a static-init'ed `LedMatrixLed::new`), but I'm also not opposed to it.

When I'm looking for how to add a capsule to a board I will often go straight to the component, so I consider this helpful

**Comment by alexandruradovici** [comment]
> Looks good in general, with two minor comments:
> 
>     * it might make sense to use the introduced helper methods not only in the `LedMatrixLed` but also in the `kernel::Driver` implementation, to avoid duplicating the logic there.
> 
Can you please be more specific, I'm not sure what you are referring to.

>     * I'm not entirely convinced we'd need a macro in `components` to construct an `LedMatrixLed` (since it's just a wrapper around a static-init'ed `LedMatrixLed::new`), but I'm also not opposed to it.

**Comment by lschuermann** [comment]
If I'm not mistaken you're implementing functions such as `read` and `toggle`, which might also be usable as part of the `command` implementation. Here it's not a big deal, it's fine as it is now.

**Comment by alexandruradovici** [comment]
> If I'm not mistaken you're implementing functions such as `read` and `toggle`, which might also be usable as part of the `command` implementation. Here it's not a big deal, it's fine as it is now.

You are right, I modified it.

**Review by hudson-ayers — APPROVED** [review]
bors r+

**Pull request merged**
