### PR TITLE
stm: improve app programming

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request changes the makefile and readme files for STM32 boards to improve the app programming.

It uses the same methods as used for the Raspberry Pi Pico board. It defines a command line variable `APP` that contains the path to a TBF.

### Testing Strategy

This pull request was tested using STM32F412g Discovery and Nucleo429zi boards.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
Why don't we use tockloader?

**Comment by alexandruradovici** [comment]
STM32F412g has a strange Flash layout, the kernel breaks when apps are loaded. Let me try with the rest of them.

**Review by hudson-ayers — APPROVED** [review]
These changes seem fine if we want to get something in before the release, but `tockloader` support should probably be a priority for these boards.

Could we just lie to tockloader about the page size being 128 kB? That appears to be the largest page size for that chip, depending on where you are in flash. It would make flashing slower than the optimal case but thats not a huge deal

**Comment by bradjc** [comment]
> Could we just lie to tockloader about the page size being 128 kB? That appears to be the largest page size for that chip, depending on where you are in flash. It would make flashing slower than the optimal case but thats not a huge deal

Is the start of apps on some sort of page boundary? If so `--bundle-apps` was intended to address issues like this, as that flag tells tockloader to write all apps as one large write every time. But if the page overlaps with the kernel then I don't know what to do.

**Comment by hudson-ayers** [comment]
> > Could we just lie to tockloader about the page size being 128 kB? That appears to be the largest page size for that chip, depending on where you are in flash. It would make flashing slower than the optimal case but thats not a huge deal
> 
> Is the start of apps on some sort of page boundary? If so `--bundle-apps` was intended to address issues like this, as that flag tells tockloader to write all apps as one large write every time. But if the page overlaps with the kernel then I don't know what to do.

It looks like currently the kernel/app boundary is halfway through a page -- we should just move it later. I'll submit a PR

**Comment by alevy** [comment]
@alexandruradovici keep this around or close it? Reopen if you want

**Comment by alexandruradovici** [comment]
Thanks

**Pull request closed without merging**
