### PR TITLE
deprecate launchxl, cc26x2

### PR DESCRIPTION
**Pull request by ppannuto**
### Pull Request Overview

This pull request deprecates the LaunchXL and CC26x2, moving them to tock-archive.

This is not intended as a statement one way or another on this chip or board, rather just a recognition that this board has not seem much uptake, and maintenance is lagging (e.g. #1101).

See the companion PR here: https://github.com/tock/tock-archive/pull/2

### Testing Strategy

Compiling.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
We have https://github.com/tock/tock/blob/master/doc/Design.md#merge-aggressively-archive-unabashedly

**Comment by ppannuto** [comment]
We also talked about archiving this board during the 1.5 release window, then just didn't get around to actually doing it after the release.

**Comment by hudson-ayers** [comment]
whoops, the benchmarks action fails if you remove a board, because it builds it for current master and then finds nothing to compare it to. It won't block merging though as it is not a required status.

**Comment by bradjc** [comment]
@tock/core-wg

**Comment by andresblanco06** [comment]
I am interested in developing on the CC26xx and CC13xx platform. Are there instruction on getting it work?

**Comment by hudson-ayers** [comment]
There are instructions here, though you will be running an older version of Tock: https://github.com/tock/tock-archive/blob/bcb4e3872dd921ff42b3b8053815e969287d269b/launchxl/README.md .

In order to get flashing to work, you will likely need to follow the instructions here: https://github.com/tock/tock-archive/tree/bcb4e3872dd921ff42b3b8053815e969287d269b/launchxl/boards/launchxl

**Pull request merged**
