### PR TITLE
multiple boards: refactored GET_PERIPHERALS

### PR DESCRIPTION
**Pull request by RaresCon**
### Pull Request Overview

This pull request refactors all appearances of the `get_peripherals()` function to `create_peripherals()`.
Issue: https://github.com/tock/tock/issues/3270

### Testing Strategy

This pull request was not tested being only refactoring.

### TODO or Help Wanted

This pull request still needs feedback / code review.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by twilfredo — APPROVED** [review]
lgtm

**Review by lschuermann — APPROVED** [review]
Don't have any strong feelings about this change, but not opposed to it.

**Review by hudson-ayers — APPROVED** [review]
Brad was anti-churn on this in the original issue, but I think this is worth the added clarity at the cost of 46 lines changed.

**Review by alistair23 — APPROVED** [review]

**Pull request merged**
