### PR TITLE
Tock 2.0: update hd44780 driver to 2.0 api

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request updates the hd44780 driver to use the 2.0 API.

NOTE: this driver is somehow deprecated, I think we should merge #2079. I will make the changes to adapt it for 2.0 and submit a new PR with it.

### Testing Strategy

This has been tested using a Nucelo 429ZI board.

### TODO or Help Wanted

 - [x] @teonaseverin please test this PR using https://github.com/tock/libtock-c/pull/152

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Looks good once tested! Thanks for taking this on

**Comment by teonaseverin** [comment]
I tested it, it works!

**Comment by hudson-ayers** [comment]
#2079 is merged, and I merged `master` into `tock-2.0-dev` again so those changes are now included in `tock-2.0-dev`. This will need to be updated to fix the `text_screen` hil as that is now where the system call driver is

**Comment by hudson-ayers** [comment]
replaced by #2335

**Pull request closed without merging**
