### PR TITLE
Finalizing TRD 101.

### PR DESCRIPTION
**Pull request by phil-levis**
### Pull Request Overview

TRD 101 has been pretty stable for a while now, but we never finalized it. This PR finalizes it.

It might not be ready -- I encourage people to re-read the TRD and make sure everything is correct.

### Testing Strategy

NA

### TODO or Help Wanted

Careful read-throughs.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Comment by phil-levis** [comment]
Had to fix formatting of authors block.

**Review by bradjc — DISMISSED** [review]

**Comment by lschuermann** [comment]
A few things I've noticed while reading through it, none of it critical:
- spelling error, "overlow" -> "overflow"
- the document states that an `AlarmClient` must also be an `OverflowClient` (`trait AlarmClient: OverflowClient`), though that is not the case in Tock as of now. I'm also not sure whether all alarm hardware implementations would support that.
- one might want to explicitly document that `set_alarm(` sets the alarm, replacing any previously set alarm (such that the client will know it won't get two callbacks), though that is already kind of obvious?
- a Timer is referred to a software implementation, whereas at least `LiteX` builds an `Alarm` on top of a hardware `Timer`, as opposed to the other way around

**Review by lschuermann — APPROVED** [review]

**Comment by phil-levis** [comment]
> A few things I've noticed while reading through it, none of it critical:
> 
>     * spelling error, "overlow" -> "overflow"
> 
>     * the document states that an `AlarmClient` must also be an `OverflowClient` (`trait AlarmClient: OverflowClient`), though that is not the case in Tock as of now. I'm also not sure whether all alarm hardware implementations would support that.
> 
>     * one might want to explicitly document that `set_alarm(` sets the alarm, replacing any previously set alarm (such that the client will know it won't get two callbacks), though that is already kind of obvious?
> 
>     * a Timer is referred to a software implementation, whereas at least `LiteX` builds an `Alarm` on top of a hardware `Timer`, as opposed to the other way around

Addressed all 4.

**Comment by hudson-ayers** [comment]
@phil-levis it looks like your latest changes did not get pushed (unless this is some sort of caching issue on my end)

**Comment by ppannuto** [comment]
Did a quick pass; tried to break them into tiny commits to minimize conflict with whatever changes might still be on @phil-levis's machine.

**Comment by phil-levis** [comment]
> @phil-levis it looks like your latest changes did not get pushed (unless this is some sort of caching issue on my end)

Ooops.

**Review by bradjc — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Pull request merged**
