### PR TITLE
Tock 2.0: deleted unused ft6x06 and st77xx drivers

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request deletes the `Driver` trait implementation from `ft6x06` and `st77xx`. Both driver should be used through their respective generic drivers (touch and screen)

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]

**Comment by bradjc** [comment]
Can we just merge this into master? I don't think this is a 2.0 change is it?

**Comment by alexandruradovici** [comment]
> Can we just merge this into master? I don't think this is a 2.0 change is it?

Sure, should I open a new pull request?

**Comment by bradjc** [comment]
Yeah if PRs don't allow you to change the target.

**Comment by hudson-ayers** [comment]
I changed the target, but the PR was based on the 2.0 branch so there are a ton of unwanted changes..you could cherry-pick the commits onto master and force push to here, or just open a new PR. Whatever is easiest.

**Pull request closed without merging**
