### PR TITLE
pconsole: support a "hibernation" mode

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates the process console to include a "hibernation" mode where the process console is still listening but doesn't respond to any commands or show the prompt. This allows the process console to get out of the way of an app that is using the console (particularly interactive apps).

This adds two pconsole commands:
- `console-start`
- `console-stop`

to implement this.

Boards can choose which mode to default to by calling either `pconsole.start()` or `pconsole.start_hibernated()`.

Additionally:
- Format the process console doc (in its own commit!)
- Add the commands to the doc
- Remove `rx_in_progress` which was set but never read

### Testing Strategy

Using the pconsole with an interactive app.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by brghena — COMMENTED** [review]
I like the idea here.

How does this work in practice with an interactive application? Does the `pconsole` win all user text input unless it's hibernating?

**Comment by bradjc** [comment]
> How does this work in practice with an interactive application? Does the `pconsole` win all user text input unless it's hibernating?

In practice from a user's point of view, if pconsole is active it works exactly as it does today. If pconsole is hibernating it works exactly as if the pconsole was not started or not included on the board.

**Comment by bradjc** [comment]
Example, with breaks I added manually
```
tock$ start kv_interactive
Process kv_interactive resumed.

/// BOTH RUNNING

tock$ KV: unknown command
start
tock$ KV: unknown command
list
 PID    ShortID    Name                Quanta  Syscalls  Restarts  Grants  State
 0      Unique     kv_interactive           0       432         0   1/15   Yielded
KV: unknown command
 1      Unique     kv_system            98550        26         0   1/15   Running
 2      Unique     kv_system            98548        26         0   1/15   Running
tock$ set a 34
Valid commands are: help status list stop start fault boot terminate process kernel reset panic console-start console-stop
tock$ Setting a=34
Error setting key -11
get b 894
Valid commands are: help status list stop start fault boot terminate process kernel reset panic console-start console-stop
tock$ Getting b
Could not get key: -11
console-stop
Disabling the process console.
KV: unknown command
Run console-start to reactivate.

/// PCONSOLE STOPPED

list
KV: unknown command
get a 123
Getting a
Could not get key: -11
set b 456
Setting b=456
Error setting key -11
help
KV: unknown command
list
KV: unknown command
start
KV: unknown command
stop
KV: unknown command
console-start

/// BOTH RUNNING

tock$ KV: unknown command
list
 PID    ShortID    Name                Quanta  Syscalls  Restarts  Grants  State
 0      Unique     kv_interactive           0       888         0   1/15   Yielded
KV: unknown command
 1      Unique     kv_system           100400        26         0   1/15   Running
 2      Unique     kv_system           100399        26         0   1/15   Running
tock$
```

**Review by brghena — APPROVED** [review]

**Comment by alevy** [comment]
This looks good to me. I think there is maybe a slightly more elegant version that (a) uses control sequences (which might require special support from tockloader, I'm not sure) and (b) hides input from apps and app output from the console when pconsole is active.

But this is better than what we have and I like it!

**Review by alevy — APPROVED** [review]

**Review by alexandruradovici — APPROVED** [review]

**Review by lschuermann — APPROVED** [review]

**Pull request merged**
