### PR TITLE
[WIP] SHA Softdevice implementation

### PR DESCRIPTION
**Pull request by danielrutz**
### Pull Request Overview

This pull request adds a software implementation of a softdevice for the SHA-1, SHA-224 and SHA-256 hash functions that adheres to the hash abstraction layer as defined in #1727. 

### Security warning

IMPORTANT: The authors make no claims of it being secure, bug-free or safe to use in any environment. The authors cannot be made liable in case of any damage resulting from this code.

On a personal note: I am no cryptography expert. While writing this we didn't try to be clever at any stage. This is loosely based on the [RFC Implementation](https://tools.ietf.org/html/rfc6234). We strongly believe that a software SHA implementation benefits the kernel massively, especially in terms of application portability. Please check this carefully before merging anything.

### Testing Strategy

This pull request was tested by compiling. This implementation in an earlier version was tested some time ago. We are planning to test this implementation once a driver has been written.

### TODO or Help Wanted

This pull request still needs...

- [ ] #1727 merged
- [ ] further testing
- [ ] documentation improvements

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
Now that there is a HIL, can this software implementation implement it?

**Comment by bradjc** [comment]
I think we should be open about accepting capsules, and adding this seems like a good idea to me. But, in a practical sense, I think it needs to support the HIL interface to be usable in Tock.

**Comment by lschuermann** [comment]
@bradjc I also think it'd be a great idea to have this. It makes sense that we have a HIL included, and we should try to adapt this to it. #1727 was our (as part of a joint research project) idea on creating such a HIL, which didn't make it in.

If @danielrutz wants to continue to take the lead in this PR and try to get it into Tock (along with adapting to the HIL in upstream) he is of course welcome to do so. Otherwise I can offer to give it a try. :smile:

**Comment by bradjc** [comment]
Timing out, but happy to revisit if anyone wants to update this to the current Tock interfaces.

**Pull request closed without merging**
