### PR TITLE
Add support for USB bulk/interrupt on the nrf52 chip.

### PR DESCRIPTION
**Pull request by gendx**
### Pull Request Overview

This pull request updates the USB HIL and implements it on the nrf52 chip. There are still unimplemented parts (isochronous endpoints, handling of "USB events"), but I tested it on the USB [echo app](https://github.com/tock/libtock-c/tree/master/examples/tests/usb) for bulk endpoints, and some interrupt endpoints (example not public yet, though the logic in the chip is pretty much the same for interrupt and bulk).

Notable changes to the HIL in order to support this chip as well as interrupt endpoints:
- The `UsbController` and `Client` traits now take a lifetime parameter. This is ultimately to use lifetime-bound buffers, as previously discussed in https://github.com/tock/tock/pull/1427.
- Unified the `endpoint_*_enable` methods to take the transfer type as parameter. This avoids code duplication down the road, as interrupt and bulk endpoints are handled very similarly by the nrf52 chip. Similarly, `bulk_*` methods in the USB client are replaced by `packet_*` methods. And `Bulk(In|Out)Result` enums are generalized to interrupts as well.
- Added a possibility to enable an endpoint both for IN and OUT directions. Some protocols such as USB-HID have such bi-directional endpoints.
- Split `endpoint_bulk_resume` into `endpoint_resume_in` and `endpoint_resume_out` functions, to specify which direction should be resumed, given that an endpoint can now be both IN and OUT directions.
- Due to the way nrf52 triggers USB events, I had to remove the `delayed_in` check in `capsules/src/usb/usbc_client.rs`, otherwise the driver never initiates IN transactions (from the device to the host). I had a look at the sam4l code and this doesn't seem problematic ("superfluous" resumes are ignored).

I propagated these changes on the sam4l, but not implementing the new combinations there as I don't have a board to test on. Code compiles though.

Isochronous endpoints are left un-implemented.

Another thing to note: some revisions of the nrf52840 chip need many more errata to function properly. As I don't have the hardware to test, and to keep things simple, these extra errata are not implemented. If one enables the USB stack on such chip, it will panic, given that the rest of the code will be unstable on these chips.

### Testing Strategy

This pull request was tested by:
- Running the USB bulk-echo test [app](https://github.com/tock/libtock-c/tree/master/examples/tests/usb) with the [host test program](https://github.com/tock/tock/tree/master/tools/usb/bulk-echo).
- Testing a USB-interrupt-based (HID) protocol.

### TODO or Help Wanted

This pull request still needs:
- ~~The interrupt service to listen to USB (https://github.com/tock/tock/pull/1505).~~
- Adding the `usb_user` driver to the board. It's what I added on top of this pull-request to test bulk-echo, and I can integrate it to this pull-request if needed.
- There are still a few things to implement, but given how big USB is, I don't think a single pull-request should implement it all (similarly to sam4l). The goal is to give a basis to experiment and iterate on.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by gendx** [comment]
> I just looked over the code but it looks good.
> 
> The only thing I don't quite understand is the `'a &self` in `Client` as I don't think we have to do that anywhere else.

The definition of the `Usbd` on nrf52's chip takes a lifetime parameter.

```rust
pub struct Usbd<'a> {
    registers: StaticRef<UsbdRegisters<'a>>,
    state: OptionalCell<UsbState>,
    dma_pending: Cell<bool>,
    client: OptionalCell<&'a dyn hil::usb::Client<'a>>,
    descriptors: [Endpoint<'a>; NUM_ENDPOINTS],
}
```

This is because the `UsbdRegisters` take a lifetime themselves, as we discussed in #1427.

```rust
#[repr(C)]
struct UsbdRegisters<'a> {
    ...
    /// - Address: 0x600 - 0x6A0
    epin: [detail::EndpointRegisters<'a>; NUM_ENDPOINTS],
    /// - Address: 0x6A0 - 0x6B4
    isoin: detail::EndpointRegisters<'a>,
    _reserved13: [u32; 19],
    /// - Address: 0x700 - 0x7A0
    epout: [detail::EndpointRegisters<'a>; NUM_ENDPOINTS],
    /// - Address: 0x7A0 - 0x7B4
    isoout: detail::EndpointRegisters<'a>,
    ...
}

...

#[repr(C)]
pub struct EndpointRegisters<'a> {
    ptr: VolatileCell<*const u8>,
    maxcnt: ReadWrite<u32, Count::Register>,
    amount: ReadOnly<u32, Amount::Register>,
    // padding
    _reserved: [u32; 2],
    // Lifetime marker.
    _phantom: PhantomData<&'a [u8]>,
}

impl<'a> EndpointRegisters<'a> {
    pub fn set_buffer(&self, slice: &'a [VolatileCell<u8>]) {
        self.ptr.set(slice.as_ptr() as *const u8);
        self.maxcnt.write(Count::MAXCNT.val(slice.len() as u32));
    }
}
```

Now, this means that `hil::usb::UsbController` must take a lifetime parameter for the `endpoint_set_buffer` function (so that the `buf` parameter has the same lifetime as `Usbd`'s lifetime).

```rust
impl<'a> hil::usb::UsbController<'a> for Usbd<'a> {
    fn endpoint_set_buffer(&self, endpoint: usize, buf: &'a [VolatileCell<u8>]) {
        if buf.len() < 8 {
            panic!("Endpoint buffer must be at least 8 bytes");
        }
        if !buf.len().is_power_of_two() {
            panic!("Buffer size must be a power of 2");
        }
        if endpoint >= NUM_ENDPOINTS {
            panic!("Endpoint number is too high");
        }
        self.descriptors[endpoint].slice.set(buf);
    }
   ...
}
```

Once `UsbController` takes a lifetime, implementing `hil::usb::Client` for `Client` in `capsules/src/usb/usbc_client.rs` requires linking this lifetime to `self`.

If instead I write the following:

```rust
impl<'a, C: hil::usb::UsbController<'a>> hil::usb::Client for Client<'a, C> {
    fn enable(&self) {
        // Set up the default control endpoint
        self.client_ctrl.enable();
        ...
    }
    ...
}
```

I get the following error:

```
    Checking capsules v0.1.0 (/tock/capsules)
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
   --> /tock/capsules/src/usb/usbc_client.rs:115:26
    |
115 |         self.client_ctrl.enable();
    |                          ^^^^^^
    |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 113:5...
   --> /tock/capsules/src/usb/usbc_client.rs:113:5
    |
113 | /     fn enable(&self) {
114 | |         // Set up the default control endpoint
115 | |         self.client_ctrl.enable();
116 | |
...   |
123 | |         self.controller().endpoint_out_enable(TransferType::Bulk, 2);
124 | |     }
    | |_____^
note: ...so that reference does not outlive borrowed content
   --> /tock/capsules/src/usb/usbc_client.rs:115:9
    |
115 |         self.client_ctrl.enable();
    |         ^^^^^^^^^^^^^^^^
note: but, the lifetime must be valid for the lifetime `'a` as defined on the impl at 112:6...
   --> /tock/capsules/src/usb/usbc_client.rs:112:6
    |
112 | impl<'a, C: hil::usb::UsbController<'a>> hil::usb::Client for Client<'a, C> {
    |      ^^
    = note: ...so that the types are compatible:
            expected kernel::hil::usb::UsbController<'_>
               found kernel::hil::usb::UsbController<'a>
```

It seems a bit tricky, but in particular the following line:

```
note: but, the lifetime must be valid for the lifetime `'a` as defined on the impl at 112:6...
```

indicates that `&self` in the `enable()` function must have lifetime (bound by) `'a`, i.e. the `Client` trait must explicitly mention `fn enable(&'a self)`, to bind `UsbController`'s lifetime to `Client`'s lifetime.

In the end, all these lifetimes are `'static`, but as discussed in https://github.com/tock/tock/issues/1074 generic lifetimes are preferable (and IIRC more expressive - allowing to use `static_init` in complex cases).

All in all, the fact that these explicit lifetimes are new is due to putting lifetimes in registers (which wasn't done before), and as discussed with @alevy in https://github.com/tock/tock/pull/1427.

But I don't think this extra bit of verbosity is problematic, it works and goes in the direction of https://github.com/tock/tock/issues/1074.

**Comment by bradjc** [comment]
This changes a HIL, but since USB is not really used, I think of this like networking and risc-v support where we should merge aggressively. Anyone want to take a look at this?

**Comment by gendx** [comment]
> bors d+
> 
> I gave this a quick lookover as well. There's a bunch of debugging stuff in here that would want to be cleaned up in the future, but isn't worth the overhead to pull in and out mid-implementation I don't think.

I mostly tried to be consistent with the sam4l implementation, which is also somewhat WIP.

https://github.com/tock/tock/blob/5eae46f82e527e99cac3bc78dbdc9752811198c1/chips/sam4l/src/usbc/mod.rs#L22-L48

> Some of that errata stuff looked rough, hopefully it was just following datasheet directives and not too much debugging.

The relevant datasheet for these errata is here (I also double-checked them with the SDK): https://infocenter.nordicsemi.com/topic/errata_nRF52840_EngC/ERR/nRF52840/EngineeringC/latest/err_840_new.html
I also just noticed that errata 187 had some code located in `disable()` instead of `enable()` - now fixed that.

> We do have a bunch of other errata handling in the `init` in `chips/nrf52/src/crt1.rs`. That's currently a lot of old-world C-like embedded code. Perhaps we should have something more principled for errata, but that's a mission for another day.

Indeed, a more principled approach to errata may be useful, although not in scope for this pull-request.

**Comment by ppannuto** [comment]
I don't really understand why, but bors seems to be missing a non-trivial number of messages lately :/

**Pull request merged**
