### PR TITLE
A few OpenTitan fixes for 2.0

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

A few fixes based on 2.0 release testing.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by phil-levis — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]
bors r+

**Comment by alistair23** [comment]
Argh, something is down

**Pull request merged**
