### PR TITLE
processbuffer: fix miri issue with transmuting &u8 to &Cell<u8>

### LINKED ISSUE #2882: Unsoundness transmuting &[u8] to &[Cell<u8>] when handling read-only memory
kernel/src/processbuffer.rs defines `impl<'a> From<&'a [u8]> for &'a ReadableProcesSlice` which contains only a transmute. However, this is unsound because `ReadableProcessByte`, of which `ReadableProcessSlice` is a slice of, is `Cell<u8>`, enabling interior mutability. Transmuting from a shared read-only reference to a shared read-write reference is UB regardless of whether you write or not, because you can violate the constness invariant of other shared references that may exist at the time with safe code (other than the `transmute`).

If you add the following to the bottom and run `cargo miri test`, it will fail:
```rust
#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_ro_slice_into_readable_process_slice() {
        let data = [10u8; 10];
        let out: &ReadableProcessSlice = (&data[..]).into();
    }
}
```

The failure:
```
test processbuffer::test::test_ro_slice_into_readable_process_slice ... error: Undefined Behavior: trying to reborrow for SharedRea
dWrite at alloc96722, but parent tag <241883> does not have an appropriate item in the borrow stack                                
   --> kernel/src/processbuffer.rs:620:18                                                                                          
    |                                                                                                                              
620 |         unsafe { core::mem::transmute(val) }                                                                                 
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for SharedReadWrite at alloc96722, but parent tag <241883> does
 not have an appropriate item in the borrow stack                                                                                  
    |                                                                                                                              
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still e
xperimental                                                                                                                        
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information     
```

Maybe instead of using interior mutability, we can somehow force the index operations to cast to a raw pointer before read, disabling optimizations? Another fix would be to change all use of `&[u8]` to `&[Cell<u8>]` directly.

I'd also like to suggest that all uses of `unsafe` require unit tests running under Miri, regardless of a reviewer scan for soundness.

### PR DESCRIPTION
**Pull request by jettr**
### Pull Request Overview

Miri check for UB, and it complains that we are casting an immutable `&u8`
to a `&Cell<u8>` since the `Cell` will allow for mutation (even though the
code we have in process buffer will not mutable it). It is safer to
store the read only process buffer in a normal immutable `&[u8]` slice
than a `&[Cell<u8>]` since we cannot accidentally update the data in
which we have an immutable reference.

This fixes #2882 

### Testing Strategy

- [x] `cargo miri test` does not complain anymore

### Documentation Updated

- [x] None. This has the same external API

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by jettr** [comment]
@lschuermann FYI since you assigned the issue to yourself.

I did try to get rid of `ReadableProcesByte` entirely by replacing it with `u8` and required touching a lot more files and the external API for process buffers. I think it is cleaner to switch it is `u8` directly but I also don't want to change churn between released. What are your thoughts?

**Comment by lschuermann** [comment]
@jettr Thanks! I replied on the original issue, it seems better to have all discussion regarding this particular problem in one place. :)

**Comment by jettr** [comment]
> @jettr Thanks! I replied on the original issue, it seems better to have all discussion regarding this particular problem in one place. :)

Agreed, let's discuss strategy there and then we can come back here when we feel good with the direction

**Comment by phil-levis** [comment]
Bump?

**Comment by jettr** [comment]
Bumped conversation on #2882

**Comment by jettr** [comment]
Closing based on [feedback][0] that this would be unsound.

[0]:https://github.com/rust-lang/unsafe-code-guidelines/issues/303#issuecomment-1016639879

**Pull request closed without merging**
