### PR TITLE
[WIP] e310x: Implement SPI controller

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview
This adds a driver for the SiFive SPI controller, present in the E310-G000, E310-G002 and U540 chips.

This is still very much in progress and **_entirely untested_**. I don't own a HiFive1 board, hence I have no real hardware to test this on. This has only been tested against my very own QEMU implementation, which may be faulty as well. As discussed with @bradjc [on Slack](https://app.slack.com/client/TCC37NGVB/CCCVDSNUX/thread/CCCVDSNUX-1584191410.076200), I'm looking for volunteers to test this and get this upstreamed.

If no one is able to test / invest time or it turns out that the code is garbage, I'll buy a HiFive1 board myself.

### Testing Strategy

The primary testing strategy has been *praying*. Otherwise, the Rust compiler was used and the driver works using a QEMU virtual device implementation. No tests on real hardware have been conducted.

A valid testing strategy would be connecting an SD card (for verifying basic functionality), or connecting to a logic analyzer to verify clock speed, SCK behavior, phase, etc.

### TODO or Help Wanted

This pull request still needs
- [ ] tests on real hardware
- [ ] **all todos stated in the driver comments**
- [ ] a careful look over the FIFO handling to avoid race conditions

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
Looks like a good start!

**Comment by lschuermann** [comment]
@bradjc I pretty much forgot about `cell_update`, I just wanted to test it and remove afterwards. It's not really required, but does look nicer than doing a `.get()` and `.set()`, the latter one I often tend to forget and need to debug. I'm fine either way, feature removed or not.

**Comment by bradjc** [comment]
I would like to try to work on this.

**Comment by alistair23** [comment]
+1 I would love to see the SPI device in QEMU. If you could share your device model that would be great.

**Comment by lschuermann** [comment]
> If you could share your device model that would be great.

Hahaha yes, this is my very first experiement with QEMU internals, so the codebase is pretty embarassing :sweat_smile: . I'll see what I can do, maybe polish it a bit and push it somewhere. :)

**Comment by bradjc** [comment]
This would still be good to merge, but the hifive1b is so painful to use. Maybe someone will come along and be willing to test this, since I clearly haven't actually done it.

**Comment by lschuermann** [comment]
Unfortunately I didn't feel comfortable enough in my understanding of QEMU source to polish & publish my half-baked implementation of SPI (which, for all we know, could be entirely wrong as I've never touched the HiFive hardware).

Given the hardware constraints on the HiFive 1 which make it a target not well suited for Tock, the fact that I don't have a usecase for this anymore, and that this might not even work at all, I'm fine either way: someone tests this (I'd be willing to polish & fix the Tock driver in this case) or we close this. What do you think @bradjc?

I guess the primary use case for this is currently running with QEMU. I've got working VirtIO support on a local branch and looking forward to port to the (purely virtual) `virt` machine type in qemu-riscv32. Maybe that could then be a more interesting target for QEMU too, along with block device and networking support?

**Comment by alistair23** [comment]
Can you post the QEMU code somewhere? I think it would at least be nice to have it public, there are still only a few 32-bit RISC-V embedded boards available so the HiFive still have some use cases.

You have VirtIO support in Tock? That's awesome! That would be really cool, can we get that merged?

**Comment by bradjc** [comment]
Timing out this PR, happy to re-open if anyone has a way to test this and wants to increase support for the e310 chip. Since the hifive1b is so RAM limited interest in supporting the chip is a bit low.

**Pull request closed without merging**
