### PR TITLE
Remove @niklasad1 from Core Working Group

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview
Per @alevy, Niklas isn't planning on being actively involved in Tock, and no longer needs to be on the Core WG. This is helpful because of our PR merging and release process, which expects all core members to sign off on certain things.

### Testing Strategy

n/a

### TODO or Help Wanted

This is a strange PR to create. Maybe we should create at least a "past members" list?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by niklasad1 — APPROVED** [review]
thanks

**Comment by alevy** [comment]
@niklasad1 thanks for all your contributions over the years and your continued feedback! :heart:

**Review by alevy — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Review by brghena — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]

**Comment by bradjc** [comment]
Haha breaking procedure on a procedure PR.

**Comment by alevy** [comment]
> Haha breaking procedure on a procedure PR.

:rofl: 

Well, we've already started merging #2446, which is the actual kind of PR where this would matter, so... yeah. Also, technically, I don't think our "procedure" requires us to block on the whole core team to remove someone who approves themselves. I think we're legally in the clear on this one.

**Comment by bradjc** [comment]
Hmm, I guess we can leave whether legally speaking the unanimous approval or a week time provision applies in this case as unsettled. :)

**Review by jrvanwhy — APPROVED** [review]
+1 to creating a past members list.

**Pull request merged**
