### PR TITLE
components/{gpio,button}: support both referenced and owned GPIO pins

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

Before this change the `gpio_component_helper!` and `button_component_helper!` macros could only take references to GPIO pins. This works fine for most boards, which will have a fixed number of GPIO pins which are statically allocated within the respective chip crate.

However, it is also useful for the `{gpio,button}_component_helper!` macro to support passing in owned GPIO pins, which are then internally allocated through `static_init!`. Specifically, dynamic platfoms such as LiteX do not have a fixed number of GPIOs on every board or even in different configurations. Thus it is not trivial to preallocate all GPIO pins within the board crate and take a reference to them. Instead, GPIO pin instances are created on the fly and passed to the caller as owned objects (holding a reference to the GPIO controller). This can also reduce resource usage, as unused GPIO pins will not consume a significant amount of memory.

To support easy instantiation of a GPIO or button driver using such owned GPIO pin structs, this adds support to indicate whether the passed GPIO instances are references or owned values. This is done by placing the `ref` keyword before the GPIO pin type information, in case references are being passed in. For owned values, the `{gpio,button}_component_helper!` will allocate memory to store them internally.

### Testing Strategy

This pull request was tested by compiling all boards

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
Ok, I have to be the one to ask: why not just add a new macro for this case?

**Comment by lschuermann** [comment]
> Ok, I have to be the one to ask: why not just add a new macro for this case?

We can do that, of course! I thought this was nice syntactically, but I do admit it makes the macros slightly more complex.

**Comment by bradjc** [comment]
I'm generally opposed to introducing more complexity for hardware boards to support soft cores. Having a second macro would mean the current boards don't have to change, yet we still get the support you are looking for. Just my 2c

**Comment by lschuermann** [comment]
@bradjc that makes sense. While it may be possible that even a hardware board might make use of this functionality in the future, it's currently just the LiteX SoCs and so we can just introduce a `{gpio,button}_component_helper_owned!` macro.

**Review by hudson-ayers — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Review by bradjc — APPROVED** [review]

**Pull request merged**
