### PR TITLE
kernel/debug: Option-alize `panic` function parameters

### PR DESCRIPTION
**Pull request by rajivr**
### Pull Request Overview

This function is useful when working with boards that don't have an LED
available for `panic!` to use or during board bring up before GPIO module is
written.

### Testing Strategy

Manually tested

### TODO or Help Wanted

N/A

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
Quick note from phone, please change “wo” to “without”, we try to avoid
abbreviations generally

**Comment by rajivr** [comment]
> Quick note from phone, please change “wo” to “without”, we try to avoid abbreviations generally

Renamed the function to `panic_without_led` for now. I am not fully convinced that it is a good name. See below.

I was also wondering if it makes sense to rename current `panic` function to `panic_with_led_and_uart` and refactor the common code?

There are three scenarios that I can think of.

1. When both LEDs and UART is available then we can use `panic_with_led_and_uart`
2. Only UART is available then we can use `panic_with_uart`
3. No UART or LED is available, then we would just do `intrinsics::abort` in a simple `panic` function in `io.rs`.

**Comment by ppannuto** [comment]
Alternatively, perhaps it should just be one panic that takes an `Option`al
UART and LED reference and does the best it can? Not so sure there's value
in multiple functions here.

**Comment by rajivr** [comment]
Please let me know what you think.

When using with `None` parameter, the API will require us to use turbofish.

```
debug::panic(
    None::<&mut [&mut kernel::hil::led::LedHigh]>,
    Some(writer),
    info,
    &cortexm4::support::nop,
    &PROCESSES,
)

or

debug::panic::<kernel::hil::led::LedHigh, _>(
    None,
    Some(writer),
    info,
    &cortexm4::support::nop,
    &PROCESSES,
)
```

**Comment by ppannuto** [comment]
The turbofish is disappointing, but not the end of the world, and easy enough copy-pasted / googled. I think the Option interface is still the best choice.

@alevy any Rust magic we're missing that might obviate needing to explicitly specify the type of `None`?

**Comment by brghena** [comment]
Maybe I missed a conversation somewhere, but could you explain what your use case for this is? Generally, GPIO is the very first driver written for a chip.

**Comment by brghena** [comment]
Okay, that sounds pretty sensible as we're thinking about production-level boards. Mostly, my concern is just making the interface more difficult for everyone (see turbofish) if it's not going to matter except for some very special case. Although, I guess in this case the turbofish is only needed if you are the special case and need to provide `None`.

**Comment by bradjc** [comment]
On one hand, given this is just a debugging API anyway, I think this is a good change. Makes it a little more flexible. On the other, this would mean changing every board. I think I would rather see more functions added to `debug.rs` so that existing boards don't have to change.

**Comment by rajivr** [comment]
> On one hand, given this is just a debugging API anyway, I think this is a good change. Makes it a little more flexible. On the other, this would mean changing every board. I think I would rather see more functions added to `debug.rs` so that existing boards don't have to change.

@bradjc My feeling is its relatively straightforward to implement the change onto other boards. Its a much simpler change to implement when compared to hil changes! :-)

I didn't do that yet because I wanted to get an agreement on the API. I'll be happy to make the required changes to other boards in the final PR.

If the decision is to go with a newer API in `debug.rs`, I am okay with that too. I would however lean on an API change to `debug::panic`.

**Comment by ppannuto** [comment]
I'm also on the side of generalizing the API to panic.

**Comment by bradjc** [comment]
>@bradjc My feeling is its relatively straightforward to implement the change onto other boards. Its a much simpler change to implement when compared to hil changes! :-)

Yep, definitely not that hard. It is just annoying for all of the boards that are not in the main tree. If this made bringing up a board possible that wasn't before, or provided a benefit to the developers who have to update after a `git pull`, or was part of a larger goal (e.g. tracking issue) then I'd be all for it. But to have to change all boards to make a short window of bringing up a new board easier doesn't seem like enough.

**Pull request closed without merging**
