### PR TITLE
Remove const_fn_trait_bound feature and update nightly (Mar 2022)

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

https://github.com/rust-lang/rust/pull/93827 was merged, so there should soon be a nightly that allows us to remove `const_fn_trait_bound` feature. It seems like some of the tools we use aren't working right now, but this PR is a placeholder for when we can update to a new enough nightly.

After this, our list of features looks like:

```
arch/cortex-m/src/lib.rs:#![feature(asm_sym)]
arch/cortex-m/src/lib.rs:#![feature(naked_functions)]
arch/cortex-m0/src/lib.rs:#![feature(asm_sym, naked_functions)]
arch/cortex-m0p/src/lib.rs:#![feature(naked_functions)]
arch/rv32i/src/lib.rs:#![feature(asm_sym, naked_functions)]
boards/esp32-c3-devkitM-1/src/main.rs:#![feature(custom_test_frameworks)]
boards/nano_rp2040_connect/src/main.rs:#![feature(naked_functions)]
boards/opentitan/src/main.rs:#![feature(custom_test_frameworks)]
boards/pico_explorer_base/src/main.rs:#![feature(naked_functions)]
boards/raspberry_pi_pico/src/main.rs:#![feature(naked_functions)]
chips/earlgrey/src/lib.rs:#![feature(naked_functions)]
chips/esp32-c3/src/lib.rs:#![feature(naked_functions)]
chips/litex_vexriscv/src/lib.rs:#![feature(asm_const)]
chips/lowrisc/src/lib.rs:#![feature(const_mut_refs)]
chips/swervolf-eh1/src/lib.rs:#![feature(naked_functions)]
doc/courses/rustconf/application.md:#![feature(alloc)]
kernel/src/lib.rs:#![feature(core_intrinsics)]
libraries/riscv-csr/src/lib.rs:#![feature(asm_const)]
libraries/tock-cells/src/lib.rs:#![feature(const_mut_refs)]
```

### Testing Strategy

travis

### TODO or Help Wanted

Need a version of nightly with all valid tools.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
Pretty cool.

Regarding the tock-registers changes: IIRC this reduces all unstable features from the `tock_registers` crate, which has (a) been requested in #2982 and (b) should allow us to pretty painlessly extract this crate into it's own repository. I've been working on a strategy with @ppannuto on the latter, and would like to -- if possible -- include things such as a solution to #2941 before splitting it out and releasing a tock-registers `1.0`. Thus I propose to, after this makes it in, release a `tock-registers` 0.9.1 with this as the sole change. It gives us a few more weeks to get in the final changes for 1.0, potentially in it's own repository.

**Review by alistair23 — DISMISSED** [review]
Exciting!

**Comment by bradjc** [comment]
Hm, it's not clear to me if anyone is going to fix RLS on nightly. There has been an issue open for a month with no attention: https://github.com/rust-lang/rust/issues/94284

The tracking issue for making rust-analyzer default hasn't been closed, but it seems to indicate the delay in the switchover is procedural and not technical https://github.com/rust-analyzer/rust-analyzer/issues/4224.

Maybe we just drop RLS and see if anyone notices?

**Comment by hudson-ayers** [comment]
I am not using RLS and am generally of the opinion that anyone who is would be better off switching to rust-analyzer at this point, so in support of letting it go.

**Comment by alistair23** [comment]
Agreed!

**Review by alistair23 — DISMISSED** [review]

**Review by ppannuto — DISMISSED** [review]

**Review by hudson-ayers — DISMISSED** [review]

**Comment by lschuermann** [comment]
I've rebased this and fixed the additional doc comments. We probably shouldn't wait too long before merging to avoid collisions with other PRs.

**Review by hudson-ayers — APPROVED** [review]

**Comment by lschuermann** [comment]
Given we've already approved and tried to merge this previously, I'd say we just give it another go:

bors r+

**Pull request merged**
