### PR TITLE
Kernel: add comments

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request:

- Adds comments to data structures in the kernel.
- ~~Removes the need for `Callback` to be `mut` (which has ramifications for the capsules).~~
- ~~Removes the need for `Allocator` to be `mut`.~~

~~Blocked on #1115.~~

### Testing Strategy

This pull request was tested by compiling.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
> I think changes to the kernel that require every board, chip, and capsule to change require a design discussion before an implementation and pull request.

I tried. I got zero direct responses: https://github.com/tock/tock/issues/985#issuecomment-400760284

**Comment by brghena** [comment]
@phil-levis It's pretty hard to have any take on this PR right now. It's blocked on changes that are actually in #1115, which in turn is blocked on changes that are actually in #1113. So a good first step would be to go to #1113 and take a look at that PR.

If you do take a look, you'll see that #1113 is based on a design discussion we had in #985. Once we handle both of those blocking commits, then we should revisit this PR and see how much it actually affects.

**Comment by bradjc** [comment]
Ok ready to review! This PR now just adds comments to the kernel crate.

**Pull request merged**
