### PR TITLE
opentitan: Bump the OpenTitan bitstream SHA and enable ePMP

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This PR updates the OpenTitain bitstream to use a new SHA.

As part of this update the:
 - Interrupt mappings have updated
 - The PLIC memory addresses have been updated
 - The HMAC memory address has been updated and a bug was fixed
 - The I2C device has been changed to i2c0
 - The README has been updated

This PR also enables ePMP on Tock as that is now supported in OpenTitan.

### Testing Strategy

Tested by running a few libtock-c apps on OT.

### TODO or Help Wanted

- [x] Update QEMU
- [x] Address failing test cases:
    - [X] earlgrey_nexysvideo_blink
    - [X] earlgrey_nexysvideo_c_hello_and_printf_long
    - [X] earlgrey_nexysvideo_blink_and_c_hello_and_buttons
    - [X] earlgrey_nexysvideo_console_recv_short
    - [X] earlgrey_nexysvideo_console_timeout
    - [X] earlgrey_nexysvideo_stack_size_test1
    - [X] earlgrey_nexysvideo_stack_size_test2
    - [X] earlgrey_nexysvideo_mpu_stack_growth
    - [x] earlgrey_nexysvideo_mpu_walk_region
    - [X] earlgrey_nexysvideo_multi_alarm_test

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
Looks good so far (although I couldn't test it). You aren't yet updating the URL of the Google-hosted OpenTitan snapshot. Is that still coming or not required?

**Comment by alistair23** [comment]
Ideally we would update the snapshot, but we don't have to as the ROM doesn't use interrupts. As it requires a manual update from someone at lowRISC (I'm not sure who) I'm just going to leave it.

**Comment by alistair23** [comment]
This is ready to go!

**Review by bradjc — APPROVED** [review]

**Pull request merged**
