### PR TITLE
Enable RISC-V bitmanip extensions for OpenTitan

### PR DESCRIPTION
**Pull request by jwnrt**
### Pull Request Overview

This pull request enables RISC-V bitmanip extension support when compiling OpenTitan.

Ibex in OpenTitan supports all the bitmanip extensions in addition to the IMC already enabled. The ratified subset of these extensions is supported upstream in LLVM but not exposed in any of the default Rust targets. We can manually enable them via this flag.

I'm not sure how important these extensions are for Tock but the `.text` size did reduce by 1024 bytes.

### Testing Strategy

This pull request was tested by compiling for OpenTitan. I haven't run any proper tests.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by lschuermann — DISMISSED** [review]

**Comment by lschuermann** [comment]
This looks good, but the QEMU CI tests and invocations in the board's Makefile should be adjusted to enable those extensions (I'm assuming they're supported?).

**Comment by alistair23** [comment]
The OpenTitan machine in QEMU uses a vendor CPU, so we can't just enable the extensions from the command line.

I have sent a patch to QEMU to enable the extensions. We just have to wait until the QEMU merge window opens again.

**Comment by lschuermann** [comment]
I think that sounds like a good plan!

 I do want to mention that -- should this be critical to OpenTitan or take a very long time to merge in QEMU -- we should probably not delay such changes that work on real hardware, but not in simulation. However, this seems like an easy enough patch to simply either way a bit and maintain downstream, or work around in CI.

**Review by alevy — APPROVED** [review]

**Comment by alistair23** [comment]
Considering that this was merged into OT in 2021 and we have only just been notified, I think we can wait a few more weeks :)

**Comment by jwnrt** [comment]
FYI we have a fork of Tock with support for the bitmanip extensions (plus a bunch of other things OpenTitan uses) in case that's useful to you

https://github.com/lowRISC/qemu/tree/ot-earlgrey-8.0.2

**Comment by alevy** [comment]
@jwnrt did you mean a fork of qemu?

**Comment by jwnrt** [comment]
Sorry, yes :)

**Comment by lschuermann** [comment]
> FYI we have a fork of ~Tock~ QEMU with support for the bitmanip extensions (plus a bunch of other things OpenTitan uses) in case that's useful to you

I think that we'd generally be happy to accept an additional CI workflow that runs on that fork, if that is of interest. In particular, if upstream QEMU doesn't support features or is less faithful of emulating a given HW revision, I'd say that this would be an acceptable vehicle to run tests on, in addition to the couple we run on upstream QEMU.

**Comment by alevy** [comment]
It looks like this was accepted upstream: https://gitlab.com/qemu-project/qemu/-/commit/06fb3bda6aadeb190be09a1513f1f0d31d119d16 but didn't make it into 9.1.0.

Are we waiting for this to be released in 9.1.1? (presumably in a few days)

**Comment by jwnrt** [comment]
Rebased on top of #4214 to include @alistair23's patch.

**Comment by jwnrt** [comment]
It doesn't work locally (which I should have checked first). I'll try to debug.

**Comment by alevy** [comment]
@jwnrt What's the status of this?

**Comment by jwnrt** [comment]
Had a look at this today, QEMU is faulting on a `cpop` instruction which comes from `Zbb`.
I haven't yet worked out why QEMU doesn't like it. Maybe I messed up the QEMU upgrade and `Zbb` wasn't enabled after all.

**Comment by alistair23** [comment]
The fix isn't in QEMU 9.1.1, which is why it isn't working.

It's probably worth just updating to the current master branch

**Comment by jwnrt** [comment]
I couldn't seem to get it working locally on the latest `master` of QEMU either.

Sorry for the great big delay on this, it's very busy here at the moment, I'll try come back to this when I can.

**Review by lschuermann — APPROVED** [review]

**Comment by lschuermann** [comment]
@jwnrt all good, thanks for pushing this forward!

**Review by alevy — APPROVED** [review]

**Pull request merged**
