### PR TITLE
Add support for the MLX90614 IR Temperature Sensor

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

This PR adds support for the MLX90614 IR Temperature sensor which uses SMBus.

### Testing Strategy

Communicating with the sensor.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

### CODE REVIEW

**Comment by brghena** [comment]
Awesome! What board are using the MLX90614 with? Do you have an application in mind?

**Comment by alistair23** [comment]
I tested it with the Apollo3.

My main goal was to test SMBus, but it's also useful as a remote temperature sensor :)

**Comment by bradjc** [comment]
Can you add an entry to capsules/README.md real quick?

**Comment by alistair23** [comment]
Done

**Pull request merged**
