### PR TITLE
Ambient light 2.0

### PR DESCRIPTION
**Pull request by phil-levis**
### Pull Request Overview

This pull request updates the ambient light syscall capsule to use the Tock 2.0 API.

### Testing Strategy

This pull request was tested by running the imix test app on imix.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by lschuermann** [comment]
On an unrelated note: the CI failure of Netlify was fixed on master some time ago already. I took the liberty to merge master into tock-2.0-dev and would offer to this is on a more regular basis, to avoid massive merge commits that are harder to get right.

**Review by lschuermann — DISMISSED** [review]
LGTM. However this also includes the changes of #2279, so blocking with a "change request" to avoid merging the other PR implicitly with this one.

**Comment by phil-levis** [comment]
bors try

**Pull request merged**
