### PR TITLE
Add utility for inspecting process state

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request adds a new introspection module in the kernel that provides functions that can allow a capsule to see key stats about the processes on the board.

This is likely still a work in progress, but we need it for the sensys demo so I at least wanted to get it in front of people.

### Testing Strategy

I have only compiled this code.

### TODO or Help Wanted

I think this is a start, but changes are likely necessary.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
I realized that I originally wrote this before capabilities had been merged. Since I doubt we want arbitrary capsules from being able to see this state, I added the `ProcessManagementCapability` to the signature for each function.

Also, it seems like this new module should be in `docs/`, but I couldn't think of or see an obvious place for it to go. Anyone have any ideas?

**Comment by phil-levis** [comment]
I'd suggest calling the Capability `ProcessInspection` since it's only data acquisition. Process management (which is probably a subtype of ProcessInspection) will include starting/stopping processes.

**Comment by bradjc** [comment]
Compiling on master:

```
Build nordic/nrf52dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf52dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling nrf52 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf52)
   Compiling nrf52dk_base v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk_base)
    Finished release [optimized + debuginfo] target(s) in 18.32s
   text    data     bss     dec     hex filename
  69180    1636   39324  110140   1ae3c target/thumbv7em-none-eabi/release/nrf52dk
rm target/thumbv7em-none-eabi/release/nrf52dk.elf
Build nordic/nrf51dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf51dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf51dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm0 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m0)
   Compiling nrf51 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf51)
    Finished release [optimized + debuginfo] target(s) in 15.26s
   text    data     bss     dec     hex filename
  59272    1484   14196   74952   124c8 target/thumbv6m-none-eabi/release/nrf51dk
rm target/thumbv6m-none-eabi/release/nrf51dk.elf
Build nordic/nrf52840dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf52840dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52840dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling nrf52 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf52)
   Compiling nrf52dk_base v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk_base)
    Finished release [optimized + debuginfo] target(s) in 17.91s
   text    data     bss     dec     hex filename
  73916    1892  260252  336060   520bc target/thumbv7em-none-eabi/release/nrf52840dk
rm target/thumbv7em-none-eabi/release/nrf52840dk.elf
Build launchxl
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling cc26x2 v0.1.0 (file:///Users/bradjc/git/tock/chips/cc26x2)
   Compiling launchxl v0.1.0 (file:///Users/bradjc/git/tock/boards/launchxl)
    Finished release [optimized + debuginfo] target(s) in 14.92s
   text    data     bss     dec     hex filename
  52764    1236   47916  101916   18e1c target/thumbv7em-none-eabi/release/launchxl
rm target/thumbv7em-none-eabi/release/launchxl.elf
Build hail
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling hail v0.1.0 (file:///Users/bradjc/git/tock/boards/hail)
    Finished release [optimized + debuginfo] target(s) in 24.84s
   text    data     bss     dec     hex filename
  84464    4440   61096  150000   249f0 target/thumbv7em-none-eabi/release/hail
Build ek-tm4c1294xl
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling tm4c129x v0.1.0 (file:///Users/bradjc/git/tock/chips/tm4c129x)
   Compiling ek-tm4c1294xl v0.1.0 (file:///Users/bradjc/git/tock/boards/ek-tm4c1294xl)
    Finished release [optimized + debuginfo] target(s) in 14.95s
   text    data     bss     dec     hex filename
  53484    1680   16752   71916   118ec target/thumbv7em-none-eabihf/release/ek-tm4c1294xl
rm target/thumbv7em-none-eabihf/release/ek-tm4c1294xl.elf
Build imix
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling imix v0.1.0 (file:///Users/bradjc/git/tock/boards/imix)
    Finished release [optimized + debuginfo] target(s) in 26.32s
   text    data     bss     dec     hex filename
 138216    5780   35176  179172   2bbe4 target/thumbv7em-none-eabi/release/imix
rm target/thumbv7em-none-eabi/release/imix.elf
```

and on this PR:

```
Build nordic/nrf52dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf52dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling nrf52 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf52)
   Compiling nrf52dk_base v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk_base)
    Finished release [optimized + debuginfo] target(s) in 15.75s
   text    data     bss     dec     hex filename
  68212    1632   39328  109172   1aa74 target/thumbv7em-none-eabi/release/nrf52dk
rm target/thumbv7em-none-eabi/release/nrf52dk.elf
Build nordic/nrf51dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf51dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf51dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm0 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m0)
   Compiling nrf51 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf51)
    Finished release [optimized + debuginfo] target(s) in 14.38s
   text    data     bss     dec     hex filename
  58572    1480   14184   74236   121fc target/thumbv6m-none-eabi/release/nrf51dk
rm target/thumbv6m-none-eabi/release/nrf51dk.elf
Build nordic/nrf52840dk
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling nrf52840dk v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52840dk)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling nrf5x v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf5x)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling nrf52 v0.1.0 (file:///Users/bradjc/git/tock/chips/nrf52)
   Compiling nrf52dk_base v0.1.0 (file:///Users/bradjc/git/tock/boards/nordic/nrf52dk_base)
    Finished release [optimized + debuginfo] target(s) in 15.51s
   text    data     bss     dec     hex filename
  73044    1888  260256  335188   51d54 target/thumbv7em-none-eabi/release/nrf52840dk
rm target/thumbv7em-none-eabi/release/nrf52840dk.elf
Build launchxl
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling cc26x2 v0.1.0 (file:///Users/bradjc/git/tock/chips/cc26x2)
   Compiling launchxl v0.1.0 (file:///Users/bradjc/git/tock/boards/launchxl)
    Finished release [optimized + debuginfo] target(s) in 13.56s
   text    data     bss     dec     hex filename
  51996    1228   47924  101148   18b1c target/thumbv7em-none-eabi/release/launchxl
rm target/thumbv7em-none-eabi/release/launchxl.elf
Build hail
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling hail v0.1.0 (file:///Users/bradjc/git/tock/boards/hail)
    Finished release [optimized + debuginfo] target(s) in 19.13s
   text    data     bss     dec     hex filename
  83724    4436   61096  149256   24708 target/thumbv7em-none-eabi/release/hail
Build ek-tm4c1294xl
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling tm4c129x v0.1.0 (file:///Users/bradjc/git/tock/chips/tm4c129x)
   Compiling ek-tm4c1294xl v0.1.0 (file:///Users/bradjc/git/tock/boards/ek-tm4c1294xl)
    Finished release [optimized + debuginfo] target(s) in 13.54s
   text    data     bss     dec     hex filename
  53660    1680   16752   72092   1199c target/thumbv7em-none-eabihf/release/ek-tm4c1294xl
rm target/thumbv7em-none-eabihf/release/ek-tm4c1294xl.elf
Build imix
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
   Compiling imix v0.1.0 (file:///Users/bradjc/git/tock/boards/imix)
    Finished release [optimized + debuginfo] target(s) in 22.28s
   text    data     bss     dec     hex filename
 139040    5780   35176  179996   2bf1c target/thumbv7em-none-eabi/release/imix
rm target/thumbv7em-none-eabi/release/imix.elf
```

**Comment by bradjc** [comment]
Seven days, no objections

**Pull request merged**
