### PR TITLE
tock-cells: change `OptionalCell::map` to pass a copy into the closure

### PR DESCRIPTION
**Pull request by lschuermann**
### Pull Request Overview

This pull request changes the semantics of `OptionalCell::map` to move a copy of the internal `Option`'s value into the provided closure. Proving a mutable reference to a copy that is then immediately discarded is very confusing.

An alternative design would remove the `map` APIs and add a `get()` method, which returns an `Option<T>`. Then we can use the `map*` methods on that returned type.

### Testing Strategy

This pull request was tested by compiling.

### TODO or Help Wanted

This pull request still needs porting of the rest of the kernel to this new interface. This should be mostly mechanical changes.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Comment by kupiakos** [comment]
On the call, we also discussed renaming the `extract` field to `get`. Should that be in a different PR or this one? I brought up my reasoning for calling it `get` [on the original PR that named it `extract`](https://github.com/tock/tock/pull/2531#issuecomment-1625703637).

**Comment by lschuermann** [comment]
@kupiakos It's simple enough to be tacked onto here, but given there's already a history behind that (#2531, #2531), having the discussion in a separate PR seems reasonable. Happy to be the one to take the blame here and creating the PR, given I initially introduced `get()` and then also renamed it `extract()`. :laughing: 

Apart from that, I do think that these changes are mostly orthogonal, right?

**Comment by lschuermann** [comment]
I implemented this change throughout the Tock codebase. Most of these changes have been done mechanically through `sed(1)` magic, and then verified in the git diff.

Unsurprisingly, the diff confirms that we've been dereferencing the closure parameter almost everywhere, implicitly copying it. This confirms that this change more closely reflects the intended behavior.

The actual change to `OptionalCell` is quite small; here's a link to avoid having to scroll through the diff: https://github.com/tock/tock/pull/3535/files#diff-8e0f1d8c375dc7a41a4ffd6511e8029fc478ba6425c80cd455710f54e2b75188L188-R210

**Comment by lschuermann** [comment]
For context, this has been brought up by @kupiakos on the call today, and was also the source of confusion for some OpenTitan developers.

**Review by hudson-ayers — APPROVED** [review]
Yeah, this is definitely better

**Review by bradjc — APPROVED** [review]
Yeah I never understood why we needed the `*` there and just did what the compiler told me to.

**Pull request merged**
