### PR TITLE
WiFiNNA (Arduino WiFi) HIL and capsule

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request is a RFC for defining a WiFi HIL.

Boards like the Arduino Connect RP 2040 have an integrated WiFi chip. This handles all the WiFi connectivity and socket tasks. We are not sure how to design ths HILs required so we are looking for a lot of feedback.

### Testing Strategy

N/A

### TODO or Help Wanted

We are lloking for a lot of feedback on how to design the HILs for WiFi.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
I haven't thought a lot about what a wifi hil should look like, or how a wifi hil would fit into a more generic network stack, but this looks like a reasonable start. I think the main consideration for wifi is continuing what you have done so far and separating the specific tasks (i.e. control, scan, tx, rx) into separate traits.

I suppose it likely makes sense to not include the actual data channel in this HIL, since different wifi chips/stacks will provide different abstractions. Likely we need something like an HTTP HIL that would be used for actual data communication, and this hil would only be for connection and setup.

**Comment by brghena** [comment]
@alexandruradovici Is your team still working with this? It would be a good target for a Network working-group call sometime. If not, we could close this draft for now until we're collectively ready to get back to it.

If it's going to stay open, at the minimum this needs a rebase on master so the changes are readable. It seems to have picked up a lot of irrelevant commits somewhere.

**Comment by alexandruradovici** [comment]
Sadly, not at the moment. I'm trying to get a student to pick it up :)

**Comment by brghena** [comment]
Closing this draft PR for now, although feel free to open it again if work resumes.

Created a tracking issue for WiFi support: https://github.com/tock/tock/issues/3946

**Pull request closed without merging**
