### PR TITLE
Update nightly ~~September~~ October 2022

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

Placeholder PR to update the nightly after the release.

We're actually not on too old of a version, but September will be keeping with our approximate two month cadence.

Needed a patch to clippy first, which didn't land until October.

### Testing Strategy

travis

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by alistair23 — APPROVED** [review]

**Comment by bradjc** [comment]
1. I tried to get a newer nightly, but it appears miri hasn't been available for a couple weeks:

2. This nightly doesn't work because of:

    ```
    $ make
       Compiling esp32-c3-board v0.1.0 (/Users/bradjc/git/tock/boards/esp32-c3-devkitM-1)
    error: linking with `rust-lld` failed: exit status: 1
      |
      = note: "rust-lld" "-flavor" "gnu" "/var/folders/_4/n3tmwxks3318tsb36d913f600000gn/T/rustcTA0cjJ/symbols.o" "/Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps/esp32_c3_board-cc095587c204838f.esp32_c3_board.61e0b048-cgu.0.rcgu.o" "--as-needed" "-L" "/Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps" "-L" "/Users/bradjc/git/tock/target/release/deps" "-L" "/Users/bradjc/.rustup/toolchains/nightly-2022-08-26-x86_64-apple-darwin/lib/rustlib/riscv32imc-unknown-none-elf/lib" "-Bstatic" "/Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps/libcompiler_builtins-176bfe12cc139d74.rlib" "-Bdynamic" "-znoexecstack" "-L" "/Users/bradjc/.rustup/toolchains/nightly-2022-08-26-x86_64-apple-darwin/lib/rustlib/riscv32imc-unknown-none-elf/lib" "-o" "/Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps/esp32_c3_board-cc095587c204838f" "--gc-sections" "-L/Users/bradjc/git/tock/boards/esp32-c3-devkitM-1" "-Tlayout.ld" "-nmagic" "-icf=all"
      = note: rust-lld: warning: section type mismatch for .stack_buffer
              >>> /Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps/esp32_c3_board-cc095587c204838f.esp32_c3_board.61e0b048-cgu.0.rcgu.o:(.stack_buffer): SHT_PROGBITS
              >>> output section .stack: SHT_NOBITS

              rust-lld: error: /Users/bradjc/git/tock/target/riscv32imc-unknown-none-elf/release/deps/esp32_c3_board-cc095587c204838f.esp32_c3_board.61e0b048-cgu.0.rcgu.o:(.rodata.cst16): offset is outside the section


    error: could not compile `esp32-c3-board` due to previous error
    ```

    I tried playing around with sizes and linker constants and nothing changed the error. I can't explain why it only seems to affect this board. I didn't see anything unusual about the linker setup for this board.

**Comment by hudson-ayers** [comment]
The root of the ICE is the constant we create on this line: https://github.com/tock/tock/blob/2685c145d660c885598e8e83f6f460bcafac1015/boards/components/src/sched/round_robin.rs#L27 . I posted an MCVE to the clippy and rust repositories so hopefully a compiler dev will be able to quickly fix this bug, but if not we could probably get around it by making this initialization macro more complex (read: recursive) instead of using the use a "constant to get around the array initialization shortcomings" trick.

**Comment by bradjc** [comment]
> we could probably get around it by making this initialization macro more complex (read: recursive) instead of using the use a "constant to get around the array initialization shortcomings" trick.

Luckily we are in no hurry, our last update was in July so we are right on schedule. But, this is exactly why we update the nightly every two months.

**Comment by bradjc** [comment]
I'm a little concerned about our ability to update rust at this point.

**Comment by bradjc** [comment]
I tried the latest nightly, but it doesn't seem the fix is included yet.

**Comment by bradjc** [comment]
I think we are waiting on clippy changes to be upstreamed, which will hopefully happen in the next week.

**Comment by bradjc** [comment]
https://github.com/rust-lang/rust/pulls?q=is%3Apr+%22Update+Clippy%22+

**Comment by bradjc** [comment]
Ok this should finally be ready!

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Pull request merged**
