### PR TITLE
boards/opentitan: Add support for the LED HIL

### PR DESCRIPTION
**Pull request by alistair23**
### Pull Request Overview

Add the LED HIL to the OpenTitan board.

### Testing Strategy

This was tested by running the blink libtock-rs app on OT.

### TODO or Help Wanted

All good :))

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make formatall`.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
We have a generic component for LED initialization now, and I think it would be great if we could use it moving forward whenever we add LEDs to new boards :) If there is a reason its not good to use here that would also be useful feedback.

The component is defined in `boards/components/src/led.rs`, and Hail, Imix, and the nrf52x boards all use it (and can be used as examples).

**Comment by alistair23** [comment]
Ah, I didn't realise there are different ways of doing it. You mean something similar to this instead? https://github.com/tock/tock/blob/862452b77ae0fc160231a2250de385dc7c358ef7/boards/hail/src/main.rs#L299

**Comment by hudson-ayers** [comment]
> Ah, I didn't realise there are different ways of doing it. You mean something similar to this instead?

Yep exactly! Ideally we will move all boards over to using this approach eventually, but I've only moved over boards that I have hardware I can test on.

**Comment by alistair23** [comment]
I pushed an update using the new LED component

**Pull request merged**
