### PR TITLE
DRAFT rust: disable frame pointers in the Tock kernel

### PR DESCRIPTION
**Pull request by mcy**
### Pull Request Overview

Disabling frame pointer accounting in rustc has a significant impact on
binary size. For ARM cores, this tends to drop text size by 2-3%, but on
RISC-V cores, we see size improvements of 9-10%. Full results below:
```
board            | before   | after    | Δ   | %Δ
----------------------------------------------------
imix              159.0K     154.5K     4.5K  2.83%
acd52832           61.5K      60K       1.5K  2.44%
nucleo_f446re      58.501K    57.501K   1.0K  1.71%
nucleo_f429zi      58.501K    57.501K   1.0K  1.71%
hifive1            52.5K      47.0K     5.5K  10.48%
nrf52dk            88.5K      86.0K     2.5K  2.82%
nrf52840dk        113.0K     110.0K     3.0K  2.65%
nrf52840_dongle   107.5K     105.5K     2.0K  1.86%
arty-e21           56.5K      51.0K     5.5K  9.73%
opentitan          61.9893K   56.4893K  5.5K  8.87%
hail               97.5K      94.5K     3.0K  3.08%
launchxl           62.5K      61.5K     1.0K  1.60%
```

This change disables frame pointers, which appear to be otherwise
unused, as a binary sliming measure.

The most egregious example is the following before/after pair:
```S
// Before.
20000294:       1141                    addi    sp,sp,-16
20000296:       c606                    sw      ra,12(sp)
20000298:       c422                    sw      s0,8(sp)
2000029a:       0800                    addi    s0,sp,16
2000029c:       4422                    lw      s0,8(sp)
2000029e:       40b2                    lw      ra,12(sp)
200002a0:       0141                    addi    sp,sp,16
200002a2:       8082                    ret

// After.
20000294:       8082                    ret
```

Mind, there is the separate concern that LLVM isn't inlining and eliminating these functions, which is a separate investigation I'm undertaking.

### Testing Strategy

This change is currently untested; I'm not familiar with Tock's debugging story, so I'm not sure what would be impacted by this change. This is a draft right now, and I welcome suggestions for ensuring I haven't broken anything.

### TODO or Help Wanted

I'm hoping to test the waters on whether this is tenable, at least for RISC-V cores, where the impact is outsized. I don't know if frame pointers are used at all by Tock's debugging strategy, and I'm hoping to get feedback on that.

At the very least, the OpenTitan project is looking for ways to slim its use of the Tock kernel, and the 8.8% .text shrinkage is very attractive to us in production builds.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by ppannuto** [comment]
I'm not terribly familiar with what this is doing under the hood, but my
guess is it's part of backtrace generation / a debugging tool?

Is this something we should leave enabled in debug builds and cut in
release builds?

There's some tension to doing things like that in the embedded space where
debug builds become unusable as they end up never fitting on hardware in
practice.

I guess by question is:
> which appear to be otherwise unused

What are these normally used for (in Rust more broadly)?

**Comment by mcy** [comment]
It depends a lot. The main use is in finding where the stack frames are during debugging, and yeah, this is totally something that can be debug-only. I don't know if Tock actually takes advantage of it, and we should figure out if we'd like to or if we'd like to just discard it all.

**Comment by bradjc** [comment]
If we aren't using this, and I don't think we are, I would say we just remove it and if someone wants to do something with it in the future we can re-evaluate including the flag on just debug builds or something.

**Comment by mcy** [comment]
I second letting this sit. I also would like to hear feelings about testing the change, and maybe restricting it to RISC-V targets (since ARM targets hardly get any benefit).

**Comment by alistair23** [comment]
Does this have any effect on the backtrace?

**Comment by mcy** [comment]
Unclear, that's part of what I'd like to figure out (again, underscoring that I don't have a background in how Tock does debugging). The naive frame-pointer-chasing scheme doesn't work if you don't have frame pointers, obviously, but if that's a problem we can just include frame pointers in debug builds. If you can tell me if this completely breaks your workflow, that would be great.

I'd honestly prefer to have a somewhat less blunt tool than "turn off *all* frame pointers". As I mentioned in the OP, I think we may need to examine other things, such as more aggressive inlining.

**Comment by labbott** [comment]
I'm traveling and my setup isn't working at the moment so I can't give this a real test until Tuesday probably. What I'd like to verify is if we still get backtraces with QEMU + gdb (attach via gdb server, break, bt)

**Comment by alistair23** [comment]
I just did some testing on the FPGA and this patch doesn't seem to negatively affect GDB backtraces.

**Comment by alevy** [comment]
Can  we wait on getting an OK from @labbott? I trust that @alistair23's experience with the FPGA will translate to QEMU, but I'd prefer to wait an extra day or two to make sure this doesn't negatively impact development in the short term.

**Comment by labbott** [comment]
LGTM (forgot to post this earlier, I appreciate you waiting)

**Comment by alevy** [comment]
I resolved the remaining conflict and approved. Waiting for the build to come back green again.

**Pull request merged**
