### PR TITLE
Update nightly 2018 11

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request updates Tock to a new nightly.

We won't pull this until after 1.3, but good to get it out there if people want to see what has changed in ~3 months (not much actually).

### Testing Strategy

This pull request was tested by running on Hail.

### TODO or Help Wanted

There are some other places the version has to be fixed up, but sometimes it's a pain to do that too early.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by niklasad1** [comment]
Well, in the new version of Rust we can use `extern crate foo` directly and don't have to this anymore:

```rust
extern crate foo;
use foo;
```

**Comment by bradjc** [comment]
> Well, in the new version of Rust we can use extern crate foo directly and don't have to this anymore:

Where do we have this duplication? I looked in a few boards and the capsules crate and didn't see anything.

**Comment by niklasad1** [comment]
For example the following `use` could be removed

```bash
$ git --no-pager grep "^use kernel;$"
arch/cortex-m/src/syscall.rs:use kernel;
arch/cortex-m/src/systick.rs:use kernel;
arch/cortex-m4/src/mpu.rs:use kernel;
boards/imix/src/components/button.rs:use kernel;
boards/imix/src/components/console.rs:use kernel;
boards/imix/src/components/crc.rs:use kernel;
boards/imix/src/components/fxos8700.rs:use kernel;
boards/imix/src/components/isl29035.rs:use kernel;
boards/imix/src/components/nonvolatile_storage.rs:use kernel;
boards/imix/src/components/process_console.rs:use kernel;
boards/imix/src/components/radio.rs:use kernel;
boards/imix/src/components/rng.rs:use kernel;
boards/imix/src/components/si7021.rs:use kernel;
boards/imix/src/components/udp_6lowpan.rs:use kernel;
boards/imix/src/components/usb.rs:use kernel;
capsules/src/ble_advertising_driver.rs:use kernel;
capsules/src/si7021.rs:use kernel;
chips/cc26x2/src/chip.rs:use kernel;
chips/cc26x2/src/uart.rs:use kernel;
chips/nrf51/src/chip.rs:use kernel;
chips/nrf51/src/radio.rs:use kernel;
chips/nrf52/src/chip.rs:use kernel;
chips/nrf52/src/radio.rs:use kernel;
chips/nrf52/src/uart.rs:use kernel;
chips/nrf5x/src/aes.rs:use kernel;
chips/nrf5x/src/temperature.rs:use kernel;
chips/tm4c129x/src/uart.rs:use kernel;
```
I'm not saying that we need to remove them in this PR but could save some lines :P

**Comment by bradjc** [comment]
Ok this is ready!

**Pull request merged**
