### PR TITLE
Upgrade the version of Rust before the release

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview
This PR bumps the version of rustc we are using and addresses all of the new warnings and subsequent formatting changes that result from that.

### Testing Strategy

travis

### TODO or Help Wanted

This is just a placeholder for now so its on our radar. These commits likely are not mergable any more, and I want to wait until more PRs are merged to place the burden on this PR and not others.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by niklasad1** [comment]
@bradjc how close is this from being mergeable? 

It looks like you need to run `make format all`

It would be good if we could remove the [maybeuninit feature](https://github.com/tock/tock/blob/master/libraries/tock-cells/src/lib.rs#L3)

**Comment by bradjc** [comment]
Not at all? We need to merge #1297 and #1345 before it is worth making progress on this.

**Comment by niklasad1** [comment]
Ok, I see

**Comment by DieracDelta** [comment]
Just wanted to weigh in with my two cents (as mentioned on the tock call). I've been using nightly-2019-07-10 locally and aside from warnings I haven't encountered any bugs. I've found that more recent versions (specifically 7-28) had bugs with inline assembly (jalr, for example, seemed broken). I've been doing most of my work with 7-10, and haven't encountered additional bugs. 7-16 seems like a good choice (although I haven't personally tested it).

**Comment by DieracDelta** [comment]
Also, another researcher in our lab also tested tock on the nightly 7-14 build, and said it was stable on ARM. She also tried the 7-28 build and mentioned encountering bugs with the no_std alloc library.

**Comment by bradjc** [comment]
Well we would, at this point, like to skip to something closer to `nightly-2019-08-20` (or later).

**Pull request merged**
