### PR TITLE
remove ek-tm4c1294xl

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This board has seen no development since it was originally merged, and it isn't clear that anyone is using it. Also no core developers have the hardware, and it wasn't tested for the 1.3 release.

I don't propose getting rid of this code entirely, but rather moving it to a new repo (tock-archive). It would compile there against version 1.3, and if anyone wants to use it it would still be ready to go, and if development resumes then there is no reason it couldn't be added back to Tock proper.

### Testing Strategy

n/a

### TODO or Help Wanted

Thoughts?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by Malex92** [comment]
As I originally ported TockOS to the EK-TM4C1294XL board I want to test the latest release 1.3 against the board. As I do not have enough time to support the further development on my own it makes sense that it goes into the archive.  Is there any way that the board will be supported by the core developers as the board is not expensive or they want to focus more on their own hardware?

**Comment by bradjc** [comment]
If you could test a few apps that would be great. As for ongoing development, I think in some sense "the proof is in the pudding" and there just hasn't been development on that platform and I don't expect that anyone is looking to pick it up.

Also, since cargo makes it easy to compile tock boards against crates in other repos, it should be easy for someone to use the boards in tock-archive, and if development does resume then it should also be easy to merge the platform back in.

**Comment by alevy** [comment]
I agree with @bradjc. Having it in tock-archive is basically communicating the state of affairs, which is that it exists, but isn't maintained as actively as the other boards in the main repo. It seems overall worse to have a board that doesn't work as expected with the current master, than a board that works as expected at least with a tagged older version, and clear path to get it up to speed.

**Comment by Malex92** [comment]
Thanks for all the answers and I understand that the 1.3 release is the latest version where the board is included as there is no active development on it.  For the further development of apps and peripherals of the EK-TM4C1294XL I will use release 1.3 and when the code is stored in the tock-archiv repo everyone has the possibility to pick up the development.

**Pull request merged**
