### PR TITLE
Update screen driver syscalls to Tock 2.0

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request changes the screen driver to Tock 2.0

### Testing Strategy

This pull request was tested using an STM32F412g discovery board.

### TODO or Help Wanted

N/A

I am not exactly sure where to update the user space API, as the libtock-c branch https://github.com/tock/libtock-c/tree/tock-2.0-dev does not seem to have the userspace return codes implemented. Maybe I am missing something.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Thanks!

**Comment by phil-levis** [comment]
> I am not exactly sure where to update the user space API, as the libtock-c branch https://github.com/tock/libtock-c/tree/tock-2.0-dev does not seem to have the userspace return codes implemented. Maybe I am missing something.

Good point -- we are behind on that. I updated things for `memop`, but they have very limited return values. I'll update the low-level routines in libtock-c.

**Comment by alexandruradovici** [comment]
> > I am not exactly sure where to update the user space API, as the libtock-c branch https://github.com/tock/libtock-c/tree/tock-2.0-dev does not seem to have the userspace return codes implemented. Maybe I am missing something.
> 
> Good point -- we are behind on that. I updated things for `memop`, but they have very limited return values. I'll update the low-level routines in libtock-c today/tomorrow.

Let me know if I can help in any way.

**Comment by phil-levis** [comment]
> Let me know if I can help in any way.

Thanks! I think I'm all set. Here's the PR for libtock-c: https://github.com/tock/libtock-c/pull/131

**Pull request merged**
